#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

check="$(yarn lint)"
if [ $? -ne 0 ]; then
  echo "\n====== eslint did not pass ======\n" 
  echo "$check"
  exit 1
fi

check="$(yarn test:ci)"
if [ $? -ne 0 ]; then
  echo "\n====== vitest did not pass ======\n" 
  echo "$check"
  exit 1
fi

check="$(rubocop 2>/dev/null)"
if [ $? -ne 0 ]; then
  echo "\n====== rubocop did not pass ======\n" 
  echo "$check"
  exit 1
fi

check="$(rspec)"
if [ $? -ne 0 ]; then
  echo "\n====== respec did not pass ======\n" 
  echo "$check"
  exit 1
fi
