#!/bin/sh
#
# To enable this hook, copy to .gin/hooks

check="$(yarn lint)"
if [ $? -ne 0 ]; then
  echo "\n====== eslint did not pass ======\n" 
  echo "$check"
  exit 1
fi

check="$(yarn test:ci)"
if [ $? -ne 0 ]; then
  echo "\n====== vitest did not pass ======\n" 
  echo "$check"
  exit 1
fi

check="$(rubocop 2>/dev/null)"
if [ $? -ne 0 ]; then
  echo "\n====== rubocop did not pass ======\n" 
  echo "$check"
  exit 1
fi

check="$(bundle exec rspec)"
if [ $? -ne 0 ]; then
  echo "\n====== respec did not pass ======\n" 
  echo "$check"
  exit 1
fi
