AllCops:
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'support/**/*'
  NewCops: enable
  SuggestExtensions: false

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]

Metrics/AbcSize:
  Max: 25
  CountRepeatedAttributes: false
  Exclude:
    - 'spec/**/*'
    - 'app/models/scenarios/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'spec/**/*'
    - 'app/models/scenarios/**/*'

Layout/LineLength:
  Max: 100
  Exclude:
    - 'Gemfile'

Metrics/MethodLength:
  Max: 12
  Exclude:
    - 'app/models/scenarios/**/*'

Style/WordArray:
  Exclude:
    - 'app/models/scenarios/**/*'

Style/SymbolArray:
  Exclude:
    - 'app/models/scenarios/**/*'

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma