AllCops:
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'tmp/logo.rb'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Metric/BlockLength:
  Exclude:
    - 'spec/**/*'

Metric/MethodLength:
  Max: 12