AllCops:
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'support/**/*'

Lint/AmbiguousBlockAssociation:
  AllowedMethods: [change]

Metric/AbcSize:
  CountRepeatedAttributes: false

Metric/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'

Metric/ClassLength:
  Exclude:
    - 'spec/**/*'
    - 'app/models/scenarios/**/*'

Metric/LineLength:
  Max: 100
  Exclude:
    - 'Gemfile'

Metric/MethodLength:
  Max: 12
  Exclude:
    - 'app/models/scenarios/**/*'

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma