# frozen_string_literal: true

module Scenarios
  class Scenario324 < Base
    ID = "324"
    NAME = "The Longest Night"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 6, 6].freeze
    LAYOUT = [32, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [4, :usa_leader_6_1],
        [8, :usa_paratroop_s],
        [2, :usa_m1918_bar],
        [4, :usa_decoy_leader6],
        [8, :usa_decoy_squad5_s],
        [2, :usa_decoy_weapon0],
      ] },
      "2": { list: [
        [2, :usa_leader_6_1],
        [4, :usa_paratroop_s],
        :usa_m1918_bar,
        [2, :usa_decoy_leader6],
        [4, :usa_decoy_squad5_s],
        :usa_decoy_weapon0,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_5_1,
        [7, :ger_volksgrenadier_s],
        [4, :ger_mg_34],
        [2, :ger_sdkfz_251_1],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Vierville, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: [
            "allied_random_drop_0", "allied_random_drop_2", "allied_hidden_units",
            "allied_hidden_leader_morale_6", "allied_hidden_infantry_morale_4",
          ],
        }
      end

      def description
        [
          "The U.S. 101st Airborne Division performed a parachute combat
          assault drop early in the morning of D-Day as part of the Allied
          invasion of Normandy. Five hours ahead of the D-Day landings, 6,928
          paratroopers jumped from 443 C-47 Skytrain troop-carrier planes into
          the southeast corner of France's Cotentin Peninsula. The troops were
          meant to land in an area of roughly 15 square miles, but were
          scattered by bad weather and German ground fire over an area twice
          as large, with some being dropped as far as 20 miles away.",
          "The division took most of its objectives on D-Day, but required
          four days to consolidate its scattered units and complete its
          mission of securing the left flank and rear of the U.S. VII Corps.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 1, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [7, 18, 2], [16, 6, 2], [26, 8, 2], [19, 17, 2], [13, 15, 2], [19, 9, 2], [17, 13, 2],
            [8, 6, 2], [27, 16, 2],
          ],
          allied_setup: {
            "0" => [
              ["1-30", "1-21"],
            ],
            "2" => [
              ["1-30", "1-21"],
            ],
          },
          axis_setup: {
            "0" => [
              ["*", "0-22"],
            ],
          },
          night: true,
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2] },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "g", b: "b", be: [3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
          ],
          [
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g", b: "b", be: [2] },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "f" },
            { t: "o", st: { sh: "c", s: "u" }, d: 2 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2] },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
          ],
          [
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
          ],
          [
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
          ],
          [
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "f" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "g" },
          ],
          [
            { t: "o", b: "b", be: [2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "x", s: "u" }, d: 2 },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2] },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
        ]
      end
    end
  end
end
