# frozen_string_literal: true

module Scenarios
  class Scenario424 < Base
    ID = "424"
    NAME = "Wawa Dam"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 3, 4].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_6_1,
        :usa_leader_5_2,
        :usa_leader_5_1,
        [2, :usa_leader_4_1],
        [2, :usa_engineer_s],
        [12, :usa_rifle_s],
        [2, :usa_m1_mortar],
        [6, :usa_m1918_bar],
        :usa_radio_155mm,
        [2, :usa_ft],
        [2, :usa_sc],
        [2, :usa_m20_greyhound],
        [2, :usa_m3a1_stuart_ft],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_1,
        [2, :jap_leader_4_1],
        [8, :jap_a_division_s],
        [2, :jap_type_92_hmg],
        [2, :jap_type_96_lmg],
        :jap_type_97_81mm,
        [4, :jap_crew_t],
        [2, :jap_10cm_type_92],
        [2, :jap_15cm_type_89],
        [2, :jap_sc],
        [3, :jap_type_89_gren_l],
        :sniper4,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Montalban, Philippines",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Wawa Dam was part of the Battle of Manila, intended
          to secure the vital water sources east of the capital. It was the
          longest continuous combat during the Liberation of the Philippines,
          lasting more than three months. It also proved critical in
          neutralizing the Imperial Japanese Army's Shimbu Group, which
          controlled the Sierra Madre mountain range east of Manila in
          Southern Luzon.",
          "Japanese forces created a network of tunnels and artillery sites
          with strong points at Mounts Oro, Pacawagan, Mataba, and Yabang. The
          tunnels and caves had retractable 105mm and 155mm artillery pieces
          which would cover the Marikina Valley and lower hills, supported by
          machine gun nests.  The American and Philippine forces relied on
          aerial and ground assaults on these strong points. US Army Air Force
          skip bombed these tunnels by releasing napalm bombs at a low
          altitude, bouncing the bombs into the cave entrances, and ground
          troops followed up these attacks with explosive shells, white
          phosphorus mortars, and flamethrower units.",
          "The 6th Division began their assault on Japanese positions from the
          low-lying areas near Montalban, and focused on the capture of Mount
          Pacawagan and Mount Mataba. The former would provide a commanding
          view of the Marikina Valley and the Wawa Gorge, while Mount Mataba
          would be the second objective that would link the effort from
          Antipolo to Wawa Dam. The fighting was brutal, with the 6th Infantry
          Division only gaining a foothold on both mountains and later on had
          to give up those positions due to stiff Japanese resistance.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [1, "rain"],
          wind: [3, 5, true],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [18, 1, 2], [12, 11, 2], [3, 22, 2], [18, 6, 2], [16, 6, 2], [18, 12, 2], [13, 16, 2],
            [9, 14, 2], [16, 20, 2], [17, 10, 2], [19, 15, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-6", 0], ["0-5", 1], ["0-6", 2], ["0-5", "3-6"], ["0-4", "7-10"], ["0-3", "11-12"],
              ["0-2", "13-14"], ["0-1", "15-16"], [0, 17], ["0-1", 18], [0, "19-20"],
            ],
          },
          axis_setup: {
            "0" => [
              ["11-22", 0], ["10-22", "1-2"], ["9-22", 3], ["10-22", 4], ["9-22", "5-6"],
              ["8-22", 7], ["7-22", 8], ["6-22", "9-10"], ["5-22", "11-12"], ["4-22", "13-14"],
              ["3-22", 15], ["4-22", 16], ["3-22", "17-18"], ["2-22", "19-20"], ["1-22", "21-22"],
            ],
          },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "y" },
            { t: "y" },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "v", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "y" },
            { t: "y" },
            { t: "y", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "y" },
            { t: "o", h: 1, r: { t: "d", d: [5, 6] } },
            { t: "y" },
            { t: "f", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 3, 6] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "y" },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "y" },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "f", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "y" },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "y" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "y" },
            { t: "y", r: { t: "d", d: [3, 6] } },
            { t: "y" },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 3 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "f", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "y" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "p" },
            { t: "p" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4, 5] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "v", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
          ],
          [
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "p" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
            { t: "v", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 4 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
          ],
          [
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "p" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 4 },
            { t: "v", h: 4 },
            { t: "f", h: 5 },
            { t: "f", h: 5 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 5 },
            { t: "f", h: 5 },
            { t: "f", h: 5 },
            { t: "f", h: 5 },
            { t: "f", h: 4 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "v", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "v", h: 4 },
            { t: "f", h: 5 },
            { t: "f", h: 5 },
            { t: "f", h: 4 },
            { t: "v", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "p" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "p" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "f", h: 5 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [5, 6] } },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "p" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "v", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
          ],
          [
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 4, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 2] } },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "v", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "p" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [2, 3] } },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
          ],
          [
            { t: "y", r: { t: "d", d: [3, 5] } },
            { t: "y" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "p", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
          ],
          [
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "p" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "v", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "v", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o" },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o" },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "y" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
        ]
      end
    end
  end
end
