# frozen_string_literal: true

module Scenarios
  class Scenario413 < Base
    ID = "413"
    NAME = "No Safe Ground"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 2, 18].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_5_1,
        [2, :usa_leader_4_1],
        [7, :usa_rifle_s],
        [2, :usa_m1919_browning],
        :usa_m2_mortar,
        [2, :usa_ft],
        :usa_radio_8inch,
        [2, :usa_sc],
      ] },
      "2": { list: [
        :usa_leader_5_2,
        [2, :usa_leader_4_1],
        [6, :usa_marine_rifle_s],
        [3, :usa_m1918_bar],
        :usa_radio_155mm,
        :usa_lvta_1,
        :usa_lvta_2,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_1,
        :jap_leader_4_1,
        [6, :jap_b_division_s],
        [2, :jap_crew_t],
        [3, :jap_type_92_hmg],
        :jap_75mm_type_94,
        :jap_37mm_type_1,
        [5, :trench],
        :sniper4,
      ] },
      "3": { list: [
        [2, :jap_leader_5_1],
        [6, :jap_b_division_s],
        [2, :jap_type_99_lmg],
        [2, :jap_type_89_gren_l],
        :jap_ft,
        [2, :jap_type_95_ha_go],
      ] },
      "4": { list: [
        :jap_b_division_s,
        :jap_type_99_lmg,
      ] },
      "5": { list: [
        :jap_b_division_s,
        :jap_sc,
      ] },
      "6": { list: [
        :jap_b_division_s,
        :jap_type_99_lmg,
      ] },
      "7": { list: [
        [2, :jap_b_division_s],
        :jap_sc,
      ] },
      "8": { list: [
        :jap_b_division_s,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Eniwetok, Marshall Islands",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Eniwetok was fought over the Enewetak Atoll in the
          Marshall Islands. The invasion was a three-phase operation involving
          the invasion of the three main islands. Eniwetok Island itself is a
          long, narrow island, widest at the southwestern end, and very narrow
          on the northeastern end, and defense in depth was impossible. Most
          of the Japanese defenses were foxholes and trenches.  Work had begun
          on some concrete pillboxes, but they were not complete by the time
          of the invasion.",
          "The initial landings immediately ran into problems. The short naval
          bombardment left many Japanese positions intact, and the American
          LVTs could not easily scale the sand dune just inland. These early
          problems were quickly overcome, and the Americans soon reached the
          island's ocean shore. A Japanese counter-attack hit the western part
          of the American line, but the attack failed to break the
          Americans.",
          "After that, the Marines landed and pushed towards the southwestern
          end of the island. By nightfall, they had reached the west corner of
          the island.  The Marine commander, Colonel Ayers, ordered that the
          attack continue through the night to eliminate the remaining
          Japanese pockets. Another Japanese counterattack was repulsed, but
          not before it reached the Marine battalion command post. The attack
          continued to the south along the east coast, but many Japanese
          spider hole defensive positions were intact, with heavy undergrowth
          providing good defensive cover. Progress was slow, as the spider
          holes had to be eliminated one-by-one.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [4, 2, true],
          hexes:,
          layout:,
          allied_dir: 6.5,
          axis_dir: 3.5,
          victory_hexes: [
            [3, 7, 2], [16, 14, 2], [16, 7, 2], [20, 4, 1], [4, 17, 2], [11, 5, 2], [3, 11, 2],
            [9, 12, 2], [11, 16, 2],
          ],
          allied_setup: {
            "0" => [
              ["17-22", "0-1"], ["18-22", "2-3"], ["19-22", "4-5"], ["20-22", "6-7"],
              ["21-22", "8-9"], [22, "10-11"],
            ],
            "2" => [["10-22", "0-1"], ["11-19", 2]],
          },
          axis_setup: {
            "0" => [
              ["11-16", 3], ["9-17", 4], ["4-17", 5], ["0-18", "6-7"], ["0-19", "8-9"],
              ["0-20", "10-11"], ["0-21", "12-13"], ["*", "14-22"],
            ],
            "3" => [[0, "*"]],
            "4" => [[21, 9], [19, 11], [9, 12], [5, 13], [16, 14], [11, 16], [4, 17]],
            "5" => [[21, 9], [19, 11], [9, 12], [5, 13], [16, 14], [11, 16], [4, 17]],
            "6" => [[21, 9], [19, 11], [9, 12], [5, 13], [16, 14], [11, 16], [4, 17]],
            "7" => [[21, 9], [19, 11], [9, 12], [5, 13], [16, 14], [11, 16], [4, 17]],
            "8" => [[21, 9], [19, 11], [9, 12], [5, 13], [16, 14], [11, 16], [4, 17]],
          },
          base_terrain: "d",
        }
      end

      def hexes
        [
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
          ],
          [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1, st: { sh: "t", s: "u" }, d: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "s" },
          ],
          [
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "w" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
        ]
      end
    end
  end
end
