# frozen_string_literal: true

module Scenarios
  class Scenario028 < Base
    ID = "028"
    NAME = "Hungarian Redoubt"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 1, 9].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_6_1,
        [3, :ussr_leader_4_1],
        [5, :ussr_rifle_s],
        [5, :ussr_smg_s],
        [3, :ussr_dp_27],
        [3, :ussr_sc],
        :ussr_radio_152mm,
        [2, :ussr_is_2],
        [2, :ussr_isu_152],
        [2, :ussr_m9_half_track],
      ] },
      "3": { list: [
        :ussr_leader_4_1,
        [2, :ussr_assault_s],
        :ussr_dp_27,
        :ussr_ft,
        [2, :ussr_is_2],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_5_1,
        [2, :ger_leader_4_1],
        [2, :ger_ss_s],
        [10, :ger_rifle_s],
        :ger_elite_crew_t,
        [5, :ger_mg_42],
        :ger_12cm_grw_42,
        [2, :ger_panzerfaust],
        [2, :ger_panzerschreck],
        :ger_8_8cm_pak_43,
        [2, :ger_stug_iii_f_g],
        :ger_jagdtiger,
        [6, :wire],
        [4, :mines10],
        [2, :trench],
        :sniper4,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Budapest, Hungary",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["winter"],
        }
      end

      def description
        [
          "The Siege of Budapest or Battle of Budapest, was a major battle
          fought between Soviet and Romanian forces and Hungarian and German
          forces for the Hungarian capital of Budapest, near the end of World
          War II. The Budapest Offensive began on October 29 1944, while the
          siege lasted from December 26 1944 to February 13, 1945. The Soviets
          began advancing into the suburbs of Pest in November and encircled
          Budapest on December 26. The besieged defenders resisted the Soviets
          for approximately fifty days, although they had already exhausted
          most of their supplies in the first days of the fighting. The city
          unconditionally surrendered on February 13, 1945. It was a major
          strategic victory for the Allies in their push towards Berlin.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 1, true],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [10, 18, 2], [4, 15, 2], [6, 19, 2], [10, 10, 2], [8, 3, 2], [3, 9, 2], [3, 3, 2],
            [14, 9, 2], [16, 13, 2],
          ],
          allied_setup: { "0" => [["20-22", "*"]], "3" => [[22, "*"]] },
          axis_setup: { "0" => [["0-16", "*"]] },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
          ],
          [
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
          ],
          [
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 5]] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
          ],
          [
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[2, 4]] } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" }, rr: { d: [[1, 4]] } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" }, rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" }, rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
          ],
          [
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "t", s: "u" }, d: 2 },
            { t: "o", st: { sh: "t", s: "u" }, d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o" },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
