# frozen_string_literal: true

module Scenarios
  class Scenario426 < Base
    ID = "426"
    NAME = "Bloody Nose Ridge"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 10, 30].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :usa_leader_5_1],
        [2, :usa_leader_4_1],
        [9, :usa_rifle_s],
        [4, :usa_m1918_bar],
        [2, :usa_m1919_browning],
        [2, :usa_ft],
        [2, :usa_sc],
      ] },
      "2": { list: [
        :usa_leader_4_1,
        [3, :usa_rifle_s],
        [2, :usa_m1918_bar],
        :usa_radio_155mm,
        [2, :usa_m4_sherman],
      ] },
      "3": { list: [
        :usa_leader_4_1,
        [3, :usa_rifle_s],
        [2, :usa_m1918_bar],
        [2, :usa_m4_sherman_flame],
      ] },
      "5": { list: [
        :usa_leader_5_1,
        [3, :usa_rifle_s],
        [2, :usa_m1918_bar],
        [2, :usa_sc],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [3, :jap_leader_5_1],
        [7, :jap_b_division_s],
        [3, :jap_type_92_hmg],
        :jap_type_2_12cm,
        :jap_type_97_150mm,
        [3, :jap_sc],
        [2, :jap_crew_t],
        [2, :jap_type_1_47mm],
        [4, :wire],
        [2, :mines8],
        :sniper5,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Peleliu, Palau Islands",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["axis_cave_movement"],
        }
      end

      def description
        [
          "The Battle of Peleliu, codenamed Operation Stalemate II by the US
          military, was fought between the United States and Japan during the
          Mariana and Palau Islands campaign on the island of Peleliu. US
          marines of the 1st Marine Division and then soldiers of the US
          Army's 81st Infantry Division fought to capture an airfield and then
          clear the rest of the small coral island of Peleliu. The battle was
          part of a larger offensive campaign known as Operation Forager.",
          "Major General William Rupertus, the commander of the 1st Marine
          Division, predicted that the island would be secured within four
          days. However, after repeated Imperial Japanese Army defeats in
          previous island campaigns, Japan had developed new island-defense
          tactics and well-crafted fortifications which resulted in stiffer
          resistance than expected, and the battle ended up lasting more than
          two months.",
          "After taking most of the island amid horrendous casualties, the
          Marines were relieved by the 81st Infantry Division to reduce the
          remaining pocket on Bloody Nose Ridge. By this point, having secured
          the southernmost end of the ridge, the Americans had started using
          bulldozers and flamethrower tanks to methodically destroy Japanese
          positions, now pushing into the ridges from the north. American
          fighters also continuously performed dive-bombing missions from the
          newly captured airfield on the island, firing rockets into open cave
          entrances and burning away the vegetation with napalm.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [4, 5, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [9, 11, 2], [8, 10, 2], [4, 17, 2], [3, 16, 2], [7, 15, 2], [7, 7, 2], [11, 6, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-4", 2], ["0-3", "3-4"], ["0-2", "5-6"], ["0-1", "7-8"], [0, "9-10"], ["*", "0-1"],
            ],
            "2" => [["*", 0]],
            "3" => [["*", 0]],
            "5" => [["*", 0]],
          },
          axis_setup: {
            "0" => [
              ["5-13", 4], ["4-13", 5], ["4-14", 6], ["3-14", "7-8"], ["2-14", "9-10"],
              ["1-14", 11], ["*", "12-22"],
            ],
          },
          base_terrain: "b",
        }
      end

      def hexes
        [
          [
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", r: { t: "d", d: [3, 5, 6] } },
            { t: "x" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "y" },
            { t: "s" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "j", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 6] } },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "y" },
            { t: "s" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "x" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 5, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "s" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "x" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o" },
          ],
          [
            { t: "s" },
            { t: "o", r: { t: "d", d: [3, 5, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "r", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "j", r: { t: "d", d: [1, 5] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [2, 6] } },
            { t: "b", h: 4 },
            { t: "r", h: 3 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "x" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [3, 5] } },
            { t: "b", h: 4 },
            { t: "r", h: 3 },
            { t: "v", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "v", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "r", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "j" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "r", h: 2 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o" },
            { t: "j" },
          ],
          [
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "r", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "b", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "v", h: 2 },
            { t: "r", h: 3 },
            { t: "b", h: 4 },
            { t: "o", h: 5 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "r", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "v" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 4 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 5] } },
            { t: "r", h: 1 },
            { t: "o" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "r", h: 3 },
            { t: "o", h: 4 },
            { t: "v", h: 4 },
            { t: "o", h: 5 },
            { t: "r", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "r", h: 3 },
            { t: "o", h: 4 },
            { t: "r", h: 5 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "v", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "b", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "v", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "b", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 2 },
            { t: "r", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o", h: 2 },
            { t: "r", h: 3 },
            { t: "b", h: 4 },
            { t: "o", h: 5 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "r", h: 1 },
            { t: "o", h: 2 },
            { t: "v", h: 1 },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "j" },
          ],
          [
            { t: "r", h: 3 },
            { t: "o", h: 4 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "b", h: 4 },
            { t: "o", h: 5 },
            { t: "v", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 5] } },
            { t: "r", h: 3 },
            { t: "b", h: 3 },
            { t: "r", h: 2 },
            { t: "v", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "y" },
          ],
          [
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [2, 6] } },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "y" },
          ],
          [
            { t: "o", h: 4 },
            { t: "r", h: 5 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "y", s: { t: "s", d: [2, 5] } },
            { t: "y" },
          ],
          [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
        ]
      end
    end
  end
end
