# frozen_string_literal: true

module Scenarios
  class Scenario606 < Base
    ID = "606"
    NAME = "Burning Grounds"
    ALLIES = ["chi"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"

    DATE = [1942, 4, 17].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": {
        list: [
          [2, :chi_leader_4_1],
          [10, :chi_regular_s],
          [2, :chi_czeck_lmg],
          [3, :chi_m3_stuart],
        ],
      },
    }.freeze

    AXIS_UNITS = {
      "0": {
        list: [
          :jap_leader_5_1,
          :jap_leader_4_1,
          [8, :jap_b_division_s],
          :jap_crew_t,
          [2, :jap_type_96_lmg],
          :jap_70mm_type_92,
        ],
      },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_setup: 2,
          first_move: 1,
          date:,
          location: "Yenangyaung, Burma",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Yenangyaung, fought during the Burma Campaign, was a
          critical Allied effort to rescue the trapped British 1st Burma
          Division from encirclement by Japanese forces. As the Japanese
          advanced to seize Burma's vital oil fields near Yenangyaung, British
          and Indian troops were cut off and in danger of destruction.",

          "A Chinese expeditionary force under General Sun Li-jen launched a
          bold relief operation, coordinating with British units. After
          several days of fierce fighting in intense heat and difficult
          terrain, the Chinese forces broke through Japanese lines and
          successfully extracted the trapped division. Though the Allies had
          to destroy the oil installations during their withdrawal, the battle
          was a successful Anglo-Chinese joint operation, delaying the
          Japanese advance deeper into Burma.",

          "Fog in this scenario represents smoke from the burning oil fields.
          Fun fact: \"Yenangyuang\" literally means \"stream of oil\" in Burmese.",
        ]
      end

      def map_data
        {
          start_weather: 1,
          base_weather: 1,
          precip: [0, 2],
          wind: [0, 6, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [3, 2, 1], [5, 4, 1], [4, 7, 1], [2, 9, 2], [3, 13, 2], [2, 17, 2], [9, 18, 2],
          ],
          allied_setup: { "0" => [["*", "0-7"]] },
          axis_setup: { "0" => [["*", "14-22"]] },
          base_terrain: "g",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
          ], [
            { t: "o" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 3, 6] } },
            { t: "o", d: 3, st: { sh: "h", s: "f" } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
          ], [
            { t: "o" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", d: 3, st: { sh: "h", s: "f" } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
          ], [
            { t: "o" },
            { t: "y" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ], [
            { t: "o" },
            { t: "y" },
            { t: "d", d: 3 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", d: 3, st: { sh: "h", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "y", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { d: [3, 5] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ], [
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4, 6] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, d: 3, st: { sh: "h", s: "f" } },
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1, d: 3, st: { sh: "h", s: "f" } },
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o", h: 1, d: 3, st: { sh: "h", s: "f" } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o", h: 1, d: 3, st: { sh: "h", s: "f" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "h", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
        ]
      end
    end
  end
end
