# frozen_string_literal: true

module Scenarios
  class Scenario020 < Base
    ID = "020"
    NAME = "Commissar's House"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 11, 13].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :ussr_leader_4_1],
        [5, :ussr_rifle_s],
        [2, :ussr_militia_s],
        [2, :ussr_pm_m1910],
        :ussr_dshk,
        :ussr_120_pm_38,
        [2, :ussr_ampulomet],
        [2, :ussr_decoy_leader6],
        [5, :ussr_decoy_squad4_s],
        [2, :ussr_decoy_squad3_s],
        :ussr_decoy_weapon2,
        [4, :ussr_decoy_weapon1],
        :sniper4,
      ] },
      "3": { list: [
        :ussr_leader_5_1,
        :ussr_leader_4_1,
        [3, :ussr_guards_rifle_s],
        [2, :ussr_guards_smg_s],
        [2, :ussr_dp_27],
        [2, :ussr_sc],
        [2, :ussr_decoy_leader6],
        [5, :ussr_decoy_squad5_s],
        [4, :ussr_decoy_weapon0],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        [2, :ger_leader_4_1],
        [8, :ger_rifle_s],
        :ger_leader_5_1,
        [4, :ger_mg_34],
        [2, :ger_stuh_42],
        :ger_radio_15cm,
        [4, :ger_decoy_leader6],
        [8, :ger_decoy_squad4_s],
        [5, :ger_decoy_weapon0],
        :sniper4,
      ] },
      "2": { list: [
        :ger_leader_6_1,
        [2, :ger_leader_5_1],
        [2, :ger_pionier_s],
        [4, :ger_rifle_s],
        [2, :ger_sc],
        :ger_ft,
        [2, :ger_mg_34],
        [3, :ger_decoy_leader6],
        [2, :ger_decoy_squad5_s],
        [4, :ger_decoy_squad4_s],
        [4, :ger_decoy_weapon0],
        :ger_decoy_weapon1,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Stalingrad, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["allied_hidden_units", "axis_hidden_units"],
        }
      end

      def description
        [
          "The Commissar's House was a large building that the held out
          against a number of German attacks, inflicting significant losses on
          the attackers in the process, as the Russians had fortified the
          building with a significant garrison. The Germans finally decided to
          mount a decisive attack, but this time with more firepower support.",
          "The germans bombarded the building all morning with artillery and
          mortars, then sent in assault guns at close range. The bombardment
          set the building on fire and forced the surviving defenders into the
          basement. Once they made it inside the building, it took the germans
          more than three hours to clear it. Only ten defenders escaped, but
          the Germans suffered around 100 casualties in the process.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 4, true],
          hexes:,
          layout:,
          allied_dir: 1.5,
          axis_dir: 4.5,
          victory_hexes: [
            [8, 9, 1], [6, 13, 1], [9, 15, 1], [10, 13, 1], [11, 11, 1], [10, 4, 1], [2, 19, 1],
            [3, 3, 2], [5, 17, 1],
          ],
          allied_setup: {
            "0" => [
              ["12-14", 0], ["11-14", "1-2"], ["10-14", "3-4"], ["9-14", "5-6"], ["8-14", "7-8"],
              ["7-14", "9-10"], ["6-14", "11-12"], ["5-14", "13-14"], ["4-14", "15-16"],
              ["3-14", "17-18"], ["2-14", "19-20"], ["1-14", "21-22"],
            ],
            "3" => [[14, "10-21"], ["10-14", 22]],
          },
          axis_setup: {
            "0" => [
              ["0-10", 0], ["0-9", "1-2"], ["0-8", "3-4"], ["0-7", "5-6"], ["0-6", "7-8"],
              ["0-5", "9-10"], ["0-4", "11-12"], ["0-3", "13-14"], ["0-2", "15-16"],
              ["0-1", "17-18"], [0, "19-20"],
            ],
            "2" => [["0-5", 0], [0, "1-10"]],
          },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "x" },
            { t: "o", st: { sh: "l", s: "u" }, d: 4.5 },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "c" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "x" },
            { t: "x" },
          ],
          [
            { t: "x" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "c" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "c" },
            { t: "x" },
          ],
          [
            { t: "x" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "x" },
            { t: "x" },
            { t: "o" },
            { t: "x" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "x" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "c" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "x" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "x" },
            { t: "o" },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "c" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "c" },
            { t: "o", st: { sh: "l", s: "u" }, d: 4.5 },
            { t: "x" },
            { t: "o" },
          ],
          [
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "c" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 4.5 },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "bs3", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "x" },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm2", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
          ],
          [
            { t: "d", d: 3 },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bic1", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "d", d: 3 },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "c" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "bs3", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o" },
            { t: "c" },
            { t: "x" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm2", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bic2", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "c" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "c" },
            { t: "c" },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
          ],
          [
            { t: "c" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "x" },
            { t: "o", st: { sh: "l", s: "u" }, d: 4.5 },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o" },
            { t: "c" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "x" },
            { t: "x" },
          ],
          [
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 4.5 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o" },
            { t: "x" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "x" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 4.5 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [1, 4, 6], c: "l", r: 2 } },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
