# frozen_string_literal: true

module Scenarios
  class Scenario206 < Base
    ID = "206"
    NAME = "The Long Climb"
    ALLIES = ["bra"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"

    DATE = [1944, 11, 29].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": {
        list: [
          :usa_leader_5_1,
          [2, :usa_leader_4_1],
          [10, :usa_green_s],
          [3, :usa_m1918_bar],
          :usa_radio_155mm,
          [3, :usa_m4_sherman],
        ],
      },
    }.freeze

    AXIS_UNITS = {
      "0": {
        list: [
          :ger_leader_5_1,
          :ger_leader_4_1,
          [6, :ger_conscript_s],
          [2, :ger_conscript_t],
          [2, :ger_mg_42],
          :ger_7_5cm_leig_18,
          :ger_7_5cm_pak_40,
          [2, :bunker],
        ],
      },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_setup: 2,
          first_move: 1,
          date:,
          location: "Monte Castello, Italy",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Monte Castello, fought between November 1944 and
          February 1945, was a key engagement in the northern Apennine
          Mountains during the final phase of the Italian Campaign in World
          War II. It was most notably the first major battle for the Brazilian
          Expeditionary Force (FEB), which had joined the Allied effort in
          Italy alongside American and British forces. Monte Castello was a
          strategically important height held by well-entrenched German forces
          as part of the Gothic Line, blocking the Allied advance toward the
          Po Valley.",

          "The Brazilians, fighting in difficult winter conditions, launched
          multiple assaults against the mountain beginning in November 1944,
          but were repelled each time by determined German defenders and harsh
          terrain. It wasn't until February 21, 1945, after weeks of
          preparation and coordination with American artillery and armor, that
          the FEB successfully seized Monte Castello. The victory marked a
          significant moment for Brazil's role in the war, showcasing the
          determination and growing combat effectiveness of its forces. For
          the Brazilian people, Monte Castello became a powerful symbol of
          national pride and sacrifice.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [3, 2],
          wind: [0, 4, true],
          hexes:,
          layout:,
          allied_edge: "b",
          axis_edge: "t",
          victory_hexes: [
            [9, 3, 2], [6, 6, 2], [10, 7, 2], [8, 8, 2], [12, 9, 2], [9, 16, 2], [7, 20, 1],
          ],
          allied_setup: { "0" => [["*", "18-22"]] },
          axis_setup: { "0" => [["*", "0-16"]] },
          base_terrain: "g",
        }
      end

      def hexes
        [
          [
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { d: [4, 5] } },
            { t: "o", h: 2, r: { d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ], [
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { d: [4, 5] } },
            { t: "o", h: 2, r: { d: [1, 2] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
          ], [
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [2, 4] } },
            { t: "o", h: 2, r: { d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
          ], [
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { d: [2, 5] } },
            { t: "o", h: 2, d: 2, st: { sh: "l", s: "f" } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { d: [2, 4] } },
            { t: "o", h: 2, r: { d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ], [
            { t: "f", h: 3, r: { d: [1, 4] } },
            { t: "f", h: 3, r: { d: [1, 4] } },
            { t: "o", h: 3, r: { d: [1, 5] } },
            { t: "f", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 5 },
            { t: "f", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ], [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3, r: { d: [2, 5] } },
            { t: "f", h: 4 },
            { t: "f", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { d: [2, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
          ], [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3, r: { d: [2, 5] } },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 3, r: { d: [4, 6] } },
            { t: "o", h: 3, r: { d: [1, 4] } },
            { t: "o", h: 3, r: { d: [1, 4] } },
            { t: "o", h: 2, r: { d: [1, 3, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3, r: { d: [2, 4] } },
            { t: "o", h: 3, r: { d: [1, 4] } },
            { t: "o", h: 3, r: { d: [1, 4] } },
            { t: "o", h: 3, r: { d: [1, 3] } },
            { t: "o", h: 3, d: 1, st: { sh: "l", s: "f" } },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [2, 5] } },
            { t: "o", h: 1, d: 2, st: { sh: "l", s: "f" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { d: [2, 5] } },
            { t: "o", h: 1, d: 2, st: { sh: "l", s: "f" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5] } },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5] } },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [4, 6] }  },
            { t: "o", h: 1, r: { d: [1, 4] }  },
            { t: "o", h: 1, r: { d: [1, 4] }  },
            { t: "o", h: 1, r: { d: [1, 4] }  },
            { t: "o", h: 1, r: { d: [1, 2, 5] } },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { d: [2, 6] } },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, d: 3, st: { sh: "l", s: "f" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { d: [3, 6] } },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { d: [3, 5] } },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 6] } },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
        ]
      end
    end
  end
end
