# frozen_string_literal: true

module Scenarios
  class Scenario425 < Base
    ID = "425"
    NAME = "Waltzing Matildas"
    ALLIES = ["aus"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 11, 24].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [3, :uk_leader_4_1],
        [8, :uk_line_s],
        [4, :uk_bren_lmg],
        :uk_vickers_mg,
        :uk_ml_3inch_mortar,
        :uk_radio_114mm,
        [2, :uk_matilda_ii],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :jap_leader_4_1],
        [5, :jap_b_division_s],
        [2, :jap_type_96_lmg],
        :jap_type_92_hmg,
        :jap_type_97_81mm,
        [2, :jap_sc],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Sattelberg, Papua New Guinea",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Sattelberg was part of the Huon Peninsula campaign in
          Papua New Guinea as the Allies fought to eject the Japanese from the
          region. The fighting centered on the Sattelberg Mission which was on
          top of a hill about 900 metres above sea level, approximately 8
          kilometers inland from Finschhafen, New Guinea. By this point, the
          Allied technological and industrial advantage was starting to tell,
          and the Japanese were hampered by a lack of supplies and
          reinforcements due to Allied interdiction efforts at sea and in the
          the air.",
          "Following the Australian landing at Scarlet Beach a large force of
          Japanese had retreated inland towards Sattelberg. The Japanese
          position on the high ground threatened the Australian lines of
          communication as they advanced south towards Finschhafen. The
          Australian 26th Brigade was sent to neutralize this threat. Over the
          course of 10 days they advanced west from Jivevaneng up the southern
          approaches to the mission, reducing the Japanese position with
          armor, artillery, and air support. The Japanese, running low on
          supplies, finally abandoned Sattelberg and withdrew north to
          Wareo.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 6, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [9, 8, 2], [5, 15, 2], [6, 11, 2], [8, 6, 2], [16, 18, 2], [10, 20, 2], [11, 6, 2],
          ],
          allied_setup: { "0" => [["18-22", "*"]] },
          axis_setup: { "0" => [["0-16", "*"]] },
        }
      end

      def hexes
        [
          [
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "p", h: 5 },
            { t: "p", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o", h: 4 },
            { t: "p", h: 4 },
            { t: "p", h: 4 },
            { t: "o", h: 4 },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "p", h: 4 },
            { t: "p", h: 3 },
            { t: "p", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o", h: 3 },
            { t: "p", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", st: { sh: "h", s: "f" }, d: 1, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "p", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p" },
            { t: "j" },
          ],
          [
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "h", s: "f" }, d: 1, h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1, h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p" },
          ],
          [
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "d", d: [4, 6] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 4, 5] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 3] }, h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "o", r: { t: "d", d: [2, 6] }, h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1, h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "o", st: { sh: "l2", s: "u" }, d: 1.5, h: 2 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 2 },
            { t: "p", h: 2 },
            { t: "o", st: { sh: "h", s: "f" }, d: 3, h: 2 },
            { t: "o", h: 2 },
            { t: "p", h: 2 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "p", h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1.5, h: 2 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1, h: 2 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "p", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 2 },
            { t: "o", r: { t: "d", d: [1, 3, 5] }, h: 2 },
            { t: "o", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 2, h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 2, h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "h", s: "f" }, d: 1, h: 2 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
          ],
          [
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 5, h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 5, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
          ],
          [
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2, h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 2, h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 2, h: 2 },
            { t: "o", h: 2 },
            { t: "p", h: 2 },
            { t: "o", r: { t: "d", d: [2, 6] }, h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "p", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 5, h: 2 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 5, h: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "d", d: [3, 5] }, h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1, h: 2 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1, h: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "j", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 3 },
            { t: "p", h: 3 },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 1 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "p", h: 2 },
            { t: "p", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "p", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3, st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "p", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 3, st: { sh: "h", s: "f" }, d: 1 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
          ],
        ]
      end
    end
  end
end
