# frozen_string_literal: true

module Scenarios
  class Scenario610 < Base
    ID = "610"
    NAME = "Chaos at Khasan"
    ALLIES = ["ussr"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1938, 8, 2].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [3, :ussr_leader_4_1],
        [8, :ussr_rifle_s],
        [2, :ussr_pm_m1910],
        [2, :ussr_dp_27],
        :ussr_82_bm_37,
        [2, :ussr_t_26_m38],
        [2, :ussr_bt_7],
        :ussr_kht_26,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_1,
        :jap_leader_4_1,
        [6, :jap_a_division_s],
        [2, :jap_type_96_lmg],
        [2, :jap_elite_crew_t],
        [2, :jap_70mm_type_92],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Lake Khasan, Soviet Far East",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Lake Khasan was an attempted military incursion by
          Manchukuo, a Japanese puppet state, into territory claimed and
          controlled by the Soviet Union. The incursion was justified by the
          Japanese belief that the Soviet Union had misinterpreted the
          established boundary between Imperial Russia and Qing China, and had
          subsequently tampered with the border markers.  Additionally, the
          Japanese were encouraged by intelligence indicating the poor state
          of Soviet Far Eastern forces and the recent purges of army officers.",
          "After the Japanese initially overran Soviet garrisons along the
          border, the Soviets gathered tanks and assault guns at Lake Khasan
          for a counterattack.  The chief of the Far East Front, Vasily
          Blücher, arrived at the front lines and under his command,
          the forces were moved up and attacked the Japanese.  Such was
          the disparity of forces that one Japanese artillery commander
          observed that the Soviets fired more shells in one day than the
          Japanese did in the two-week affair.  Despite this, the Japanese
          defenders organized an anti-tank defense, with disastrous results
          for the poorly coordinated Soviets, whose attacks were defeated with
          many casualties. Thousands of Soviet troops were killed or wounded
          and numerous tanks were knocked out but eventually numbers told and
          the Japanese withdrew, satisfied that the incident had been brought
          to an \"honorable\" conclusion.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 1, true],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [12, 4, 1], [17, 9, 2], [10, 17, 2], [14, 17, 2], [7, 17, 2], [20, 17, 2], [8, 10, 2],
            [18, 4, 1], [14, 13, 2],
          ],
          allied_setup: { "0" => [["*", "0-5"]] },
          axis_setup: { "0" => [["*", "7-22"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "m" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "m" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
          ],
          [
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
          ],
          [
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "m" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w", s: { t: "s", d: [3, 6] } },
          ],
          [
            { t: "o", h: 1 },
            { t: "m" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "m" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [2, 3, 6] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "m" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "m" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "m" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "f" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [2, 5, 6] } },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 5] } },
            { t: "b", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5, 6] } },
            { t: "f" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "b", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [2, 5] } },
            { t: "b", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "b", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 5] } },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 3, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
        ]
      end
    end
  end
end
