# frozen_string_literal: true

module Scenarios
  class Scenario311 < Base
    ID = "311"
    NAME = "Tip of the Spear"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"

    DATE = [1944, 9, 19].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_6_2,
        :usa_leader_5_1,
        [2, :usa_engineer_s],
        [5, :usa_rifle_s],
        [2, :usa_m2_browning],
        :usa_m2_mortar,
        :usa_radio_155mm,
        [2, :usa_m3a1_half_track],
        [4, :usa_m4_sherman],
        [2, :usa_m18_hellcat],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_5_1,
        :ger_leader_3_1,
        [9, :ger_conscript_s],
        [3, :ger_mg_42],
        :ger_panzerschreck,
        [5, :ger_panther_a_g],
        [2, :ger_jagdpanzer_iv],
        [2, :ger_stug_iv],
        :ger_sdkfz_234_1,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_setup: 1,
          first_move: 2,
          date:,
          location: "Arracourt, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: %i[axis_green_armor axis_fragile_vehicles],
        }
      end

      def description
        [
          "As the U.S. Third Army advanced through Lorraine, the Germans assembled a
          force to counter-attack at Arracourt.  While the 11th Panzer
          Division was experienced, it was short of tanks, having lost most of
          them in previous battles.  The other two brigades assembled had new
          Panther tanks, but were very green having only received two weeks of
          training, and that training was additionally limited by fuel
          shortages.  But forces were needed quickly, whether or not they had
          any proficiency in maneuver, combined arms operations, or even
          properly reading maps.",
          "The 5th Panzer Army outnumbered the defending Combat Command A of
          the 4th Armored Division, and the Panther tanks were superior the
          the M4 Shermans of the Americans (at least in terms of guns and
          frontal armor), but would they be able to take advantage?  On the
          flip side, the Americans had an overwhelming advantage in close air
          support, but fog limited air operations at the beginning of the
          battle.  And the German fuel supply issues were dire.",
        ]
      end

      def map_data
        {
          start_weather: 1,
          base_weather: 1,
          precip: [0, 2],
          wind: [1, 3, true],
          hexes:,
          layout:,
          allied_edge: "l",
          axis_edge: "r",
          victory_hexes: [
            [4, 18, 1], [7, 15, 1], [8, 13, 1], [9, 16, 1], [10, 14, 1], [12, 19, 1],
            [14, 2, 2], [16, 3, 2], [19, 8, 2], [19, 16, 2], [20, 15, 2],
          ],
          allied_setup: { "0": [["0-12", "10-22"]] },
          axis_setup: { "0": [["*", "0-4"], ["18-22", "*"]] },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1] },
          ], [
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "s" } },
            { t: "o", d: 4, st: { sh: "s" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o", d: 1, st: { sh: "c" } },
            { t: "o", d: 4, st: { sh: "l" } },
            { t: "o", r: { d: [4, 6], t: "t" } },
            { t: "o", r: { d: [1, 3, 4], t: "t" } },
            { t: "o", r: { d: [1, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "g", b: "f", be: [5, 6] },
            { t: "g", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [6] },
            { t: "o" },
            { t: "o", b: "f", be: [1, 6] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "o", d: 1, st: { sh: "s" } },
            { t: "o", d: 4, st: { sh: "s" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "o", s: { d: [3, 6] } },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 6] },
            { t: "g" },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "o", s: { d: [3, 6] } },
          ], [
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 6] },
            { t: "g" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 6, 5] },
            { t: "g", b: "f", be: [6] },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [4, 5] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2] },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [6] },
            { t: "b" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 6] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [4, 5] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "o" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 6] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 6] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" }, s: { d: [6, 4] } },
            { t: "o", s: { d: [1, 3] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "b" },
            { t: "o", b: "f", be: [5] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6, 1] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [6] },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [1, 6, 5] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", s: { d: [3, 5] } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", s: { d: [2, 6] } },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [4, 6], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
            { t: "o", b: "f", be: [5, 6] },
          ], [
            { t: "f" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "l" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "s" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [3, 5] } },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 6, st: { sh: "s" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", s: { d: [2, 5] } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "l" } },
            { t: "o", r: { d: [3, 4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 5], t: "t" } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [4, 6] } },
            { t: "o", s: { d: [1, 2, 5] } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "x", s: "f" } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 1, st: { sh: "s" } },
            { t: "o", d: 4, st: { sh: "s" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", s: { d: [4, 6] } },
            { t: "o", b: "f", be: [5, 6], s: { d: [1, 4] } },
            { t: "o", b: "f", be: [5, 6], s: { d: [1, 4] } },
            { t: "o", b: "f", be: [6], s: { d: [1, 3] } },
            { t: "o", r: { d: [4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" }, s: { d: [2, 5] } },
            { t: "o", r: { d: [1, 2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o", s: { d: [2, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
          ], [
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "o", s: { d: [4, 6] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "w", s: { d: [1, 4] } },
            { t: "w", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 3] } },
            { t: "f" },
            { t: "o" },
            { t: "o", s: { d: [2, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", r: { d: [2, 5], t: "t" }, s: { d: [1, 3] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w", s: { d: [2, 5] } },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
