# frozen_string_literal: true

module Scenarios
  class Scenario428 < Base
    ID = "428"
    NAME = "Hacksaw Ridge"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 4, 11].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :usa_leader_5_1],
        [2, :usa_leader_4_1],
        [10, :usa_rifle_s],
        [2, :usa_m1918_bar],
        :usa_m2_browning,
        :usa_m1_mortar,
        [2, :usa_ft],
        [2, :usa_sc],
        :usa_radio_155mm,
        [3, :usa_m4a3e2_sherman],
        :usa_m4105_sherman,
      ] },
      "2": { list: [
        [2, :usa_leader_6_1],
        [4, :usa_rifle_s],
        [2, :usa_m1918_bar],
        :usa_ft,
        :usa_sc,
        :usa_radio_8inch,
        [2, :usa_m4_sherman_flame],
      ] },
      "5": { list: [
        :usa_leader_6_1,
        [4, :usa_rifle_s],
        [2, :usa_m1918_bar],
        :usa_ft,
        :usa_sc,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :jap_leader_4_1],
        [6, :jap_b_division_s],
        :jap_type_92_hmg,
        [2, :jap_type_96_lmg],
        [2, :jap_type_97_90mm],
        [2, :jap_sc],
        :jap_radio_10cm,
        [2, :jap_crew_t],
        :jap_type_92_70mm,
        :jap_type_1_47mm,
        [6, :wire],
        [2, :mines8],
        [2, :bunker],
        :sniper4,
      ] },
      "5": { list: [
        [2, :jap_leader_5_1],
        [6, :jap_a_division_s],
        [3, :jap_type_99_lmg],
        [3, :jap_type_97_chi_ha],
        [3, :jap_sc],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 10,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Maeda Ridge, Okinawa",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["axis_cave_movement"],
        }
      end

      def description
        [
          "Most of the Japanese defenders of Okinawa concentrated in the
          rugged terrain north of Naha in the southern part of the island. The
          Japanese commanders were headquartered in Shuri Castle, and the town
          of Shuri formed the nucleus of a series of heavily fortified
          defensive rings, carefully constructed to take maximum advantage of
          the terrain.",
          "Among the toughest strongpoints of Shuri's defenses was the Maeda
          Escarpment, later known as Hacksaw Ridge, a flat-topped ridge with a
          sheer cliff face running diagonally across the island for several
          thousand yards. The ridge was honeycombed with tunnels and
          interconnected bunkers. It took two weeks for the Americans to clear
          the ridge as they repeatedly scaled and assaulted Japanese position,
          only to be repulsed with heavy casualties, before the position was
          finally taken.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [2, "rain"],
          wind: [1, 5, true],
          hexes:,
          layout:,
          allied_dir: 6.5,
          axis_dir: 3.5,
          victory_hexes: [
            [5, 5, 2], [3, 3, 2], [13, 14, 2], [3, 17, 2], [8, 2, 2], [10, 7, 2], [5, 10, 2],
          ],
          allied_setup: {
            "0" => [
              ["9-22", "0-1"], ["10-22", "2-3"], ["11-22", "4-5"], ["12-22", "6-7"],
              ["13-22", "8-9"], ["14-22", "10-11"], ["15-22", "12-18"], ["14-22", 19],
              ["15-22", 20], ["14-22", 21], ["15-22", 22],
            ],
            "2" => [[22, "*"]],
            "5" => [[22, "*"]],
          },
          axis_setup: {
            "0" => [
              ["0-7", "0-1"], ["0-8", "2-3"], ["0-9", "4-5"], ["0-10", "6-7"], ["0-11", "8-9"],
              ["0-12", "10-11"], ["0-13", "12-18"], ["0-12", 19], ["0-13", 20], ["0-12", 21],
              ["0-13", 22],
            ],
            "5" => [[0, "*"], [6, 3], [8, 3], [5, 6], [11, 9], [10, 13], [6, 14], [12, 16]],
          },
        }
      end

      def hexes
        [
          [
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 5, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 5, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "f", h: 4, b: "c", be: [4] },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "x", h: 5 },
            { t: "o", h: 5, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 5 },
            { t: "r", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 3, b: "c", be: [3, 4] },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "x" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 5 },
            { t: "r", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 5 },
            { t: "r", h: 4 },
            { t: "r", h: 4 },
            { t: "r", h: 3, b: "c", be: [4] },
            { t: "t", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o" },
            { t: "o" },
            { t: "b" },
          ],
          [
            { t: "o", h: 5 },
            { t: "r", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "v", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4, b: "c", be: [3, 4] },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "x" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "b" },
          ],
          [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "r", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4, b: "c", be: [3, 4] },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "r", h: 5 },
            { t: "o", h: 5 },
            { t: "f", h: 4 },
            { t: "r", h: 4 },
            { t: "r", h: 4 },
            { t: "f", h: 4, b: "c", be: [3, 4] },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "v", h: 4 },
            { t: "f", h: 4 },
            { t: "r", h: 4 },
            { t: "v", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4, b: "c", be: [3, 4] },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "r", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "r", h: 3, b: "c", be: [3] },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "o", h: 5 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "v", h: 4 },
            { t: "o", h: 4, b: "c", be: [3, 4] },
            { t: "t", h: 1 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "f", h: 4 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "r", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4, b: "c", be: [3, 4] },
            { t: "t", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 5 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4, b: "c", be: [3, 4] },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4, b: "c", be: [3, 4] },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "r", h: 2 },
          ],
          [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3, b: "c", be: [3, 4, 5] },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
          ],
          [
            { t: "r", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "v", h: 3 },
            { t: "o", h: 3, b: "c", be: [4, 5] },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 5 },
            { t: "r", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "v", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "b", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3] } },
            { t: "r", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "v", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 2 },
            { t: "r", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "t", h: 1 },
            { t: "t", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "r", h: 2 },
            { t: "r", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "t", h: 1 },
            { t: "t", h: 1 },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 2 },
            { t: "r", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "r", h: 1 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "t", h: 1 },
            { t: "t", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
          ],
          [
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "r", h: 2 },
            { t: "r", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
          ],
        ]
      end
    end
  end
end
