# frozen_string_literal: true

module Scenarios
  class Scenario422 < Base
    ID = "422"
    NAME = "The Pinnacle"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 4, 6].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :usa_leader_5_1],
        [2, :usa_leader_4_1],
        [8, :usa_rifle_s],
        [2, :usa_m1918_bar],
        :usa_m2_browning,
        :usa_m1_mortar,
        [2, :usa_ft],
        [2, :usa_sc],
      ] },
      "2": { list: [
        :usa_leader_5_1,
        [2, :usa_rifle_s],
        :usa_m2_4_2inch_mortar,
        :usa_radio_105mm,
        [2, :usa_m3_stuart],
      ] },
      "4": { list: [
        :usa_leader_6_1,
        [2, :usa_rifle_s],
        :usa_m1918_bar,
        :usa_sc,
      ] },
      "5": { list: [
        :usa_leader_5_1,
        [2, :usa_rifle_s],
        :usa_m1918_bar,
        :usa_sc,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_1,
        :jap_leader_4_1,
        [6, :jap_b_division_s],
        [2, :jap_crew_t],
        :jap_type_92_hmg,
        [3, :jap_type_96_lmg],
        [2, :jap_type_97_81mm],
        [2, :jap_sc],
        :jap_type_92_10cm,
        :jap_type_1_47mm,
        :jap_radio_7_5cm,
        [6, :wire],
        [4, :mines8],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Arakachi, Okinawa",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["axis_cave_movement"],
        }
      end

      def description
        [
          "The Pinnacle was the name given to a 30-foot-tall spire atop a
          450-foot-tall ridge of coral approximately 1,000 yards southwest of
          Arakachi, Okinawa. Heavily fortified by the Japanese defenders, this
          outpost to Japan's main defenses at Shuri held up the U.S. 7th
          Infantry Division for two days with accurate and well-concealed
          machine gun, mortar and artillery fire.",
          "Lieutenant Tanigawa had built his defenses around light and heavy
          machine guns sited at the base of the hill. In trenches and pits
          riflemen well-supplied with grenades covered the dead spaces in
          front of the machine guns. The defenses were connected by tunnels
          and trenches, affording underground mobility. On the top of the
          ridge were several mortars, with more on the reverse slope.
          Artillery check points had been established for field pieces to the
          south. Barbed wire and mine fields protected the major approaches.
          Lieutenant Tanigawa could hardly have hoped to stop the Americans,
          but undoubtedly he expected to make the price of victory high.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 3, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [8, 12, 2], [9, 15, 2], [15, 12, 2], [12, 15, 2], [12, 20, 2], [1, 8, 2], [19, 15, 2],
          ],
          allied_setup: {
            "0" => [["18-22", 3], ["19-22", 4], ["*", "0-2"]],
            "2" => [["*", 0]],
            "4" => [["*", 0]],
            "5" => [["*", 0]],
          },
          axis_setup: { "0" => [["5-17", 4], ["0-17", 5], ["*", "6-22"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 1.5 },
            { t: "b" },
            { t: "b" },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1.5 },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, s: { t: "t", d: [4, 6] } },
            { t: "o", h: 3, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 3, s: { t: "t", d: [1, 5] } },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "o", h: 4 },
            { t: "v", h: 3 },
            { t: "o", h: 3, s: { t: "t", d: [1, 5] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 3, s: { t: "t", d: [4, 6] } },
            { t: "v", h: 3 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3, s: { t: "t", d: [2, 5] } },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "o", h: 3, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3, s: { t: "t", d: [2, 5] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "v", h: 3 },
            { t: "o", h: 4, s: { t: "t", d: [1, 5] } },
            { t: "o", h: 4 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "o", h: 3, s: { t: "t", d: [2, 5] } },
            { t: "j", h: 3 },
            { t: "o", h: 3, s: { t: "t", d: [4, 6] } },
            { t: "o", h: 3, s: { t: "t", d: [1, 3] } },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3, s: { t: "t", d: [2, 6] } },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "v", h: 4 },
            { t: "o", h: 5 },
            { t: "j", h: 4 },
            { t: "v", h: 3 },
            { t: "o", h: 3, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 3, s: { t: "t", d: [1, 3] } },
            { t: "v", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [4, 6] } },
          ],
          [
            { t: "j" },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "v", h: 2 },
            { t: "j", h: 3 },
            { t: "o", h: 4 },
            { t: "b", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "b", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3, s: { t: "t", d: [2, 5] } },
            { t: "j", h: 3 },
            { t: "o", h: 4 },
            { t: "b", h: 5 },
            { t: "v", h: 4 },
            { t: "o", h: 4 },
            { t: "j", h: 3 },
            { t: "b", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "j", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "j", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 4 },
            { t: "o", h: 4 },
            { t: "j", h: 4 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "o", h: 3 },
            { t: "v", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
        ]
      end
    end
  end
end
