# frozen_string_literal: true

module Scenarios
  class Scenario330 < Base
    ID = "330"
    NAME = "Pocket Polder"
    ALLIES = ["can"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 10, 28].freeze
    LAYOUT = [32, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :uk_leader_5_1],
        [2, :uk_leader_4_1],
        [9, :uk_line_s],
        [2, :uk_engineer_s],
        [6, :uk_bren_lmg],
        [2, :uk_vickers_mg],
        [2, :uk_2inch_mortar],
        :uk_radio_152mm,
        [5, :uk_m4_sherman],
        [2, :uk_churchill_vii_viii],
        [2, :uk_u__carrier_wasp],
        [3, :uk_kangaroo],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_2,
        [2, :ger_leader_5_1],
        [7, :ger_rifle_s],
        [3, :ger_crew_t],
        [4, :ger_mg_42],
        [2, :ger_kz_8cm_grw_42],
        [2, :ger_panzerschreck],
        [3, :ger_8_8cm_pak_43],
        [2, :ger_jagdpanzer_iv],
        [2, :mines8],
        [6, :wire],
        [3, :foxhole],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Oostburg, Netherlands",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of the Scheldt was a series of military operations to
          open up the Scheldt river between Antwerp and the North Sea for
          shipping, so that Antwerp's port could be used to supply the Allies
          in north-west Europe. The battle took place in the vicinity of the
          Scheldt river in northern Belgium and southwestern Netherlands, a
          lowlying area of difficult terrain (much of it reclaimed and below
          sea level). The operations were carried out by the First Canadian
          Army, with assistance from Polish and British units.",
          "The Canadians had been delayed for more than a month, and the need
          to clear the Scheldt had not yet been addressed, due to Allied
          decisions to spend September focusing on Arnhem (Operation Market
          Garden), Boulogne (Operation Wellhit), Calais (Operation Undergo)
          and the opening weeks of the Siege of Dunkirk. By the time the
          Canadians were sent into the Battle of the Scheldt, the Wehrmacht
          defenders had been reinforced and dug in, with copious ammunition,
          guns, and equipment from previous retreats. The Germans staged an
          effective delaying action during which they flooded land areas in
          the Scheldt estuary and slowed the Allied advance. After five weeks
          of difficult fighting, the Canadian First Army was successful in
          clearing the Scheldt after numerous amphibious assaults, obstacle
          crossings and costly assaults over open ground.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 1, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [5, 2, 2], [4, 10, 2], [16, 13, 2], [17, 21, 2], [20, 7, 2], [23, 3, 2], [13, 4, 2],
            [20, 11, 2], [10, 10, 2],
          ],
          allied_setup: {
            "0" => [
              ["26-31", 0], ["25-31", "1-2"], ["24-31", 3], ["25-31", "4-5"], ["26-31", "6-7"],
              ["27-31", 8], ["28-31", 9], ["29-31", "10-11"], ["30-31", "12-14"],
              ["29-31", "15-16"], ["28-31", 17], ["29-31", "18-19"], ["30-31", 20],
              ["29-31", "21-22"],
            ],
          },
          axis_setup: {
            "0" => [
              ["0-22", "0-1"], ["0-23", "2-4"], ["0-22", "5-6"], ["0-21", "7-8"], ["0-20", "9-12"],
              ["0-19", 13], ["0-20", "14-17"], ["0-21", "18-19"], ["0-23", "20-21"], ["0-24", 22],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", s: { t: "g", d: [2, 4] } },
            { t: "o", s: { t: "g", d: [1, 4] } },
            { t: "o", s: { t: "g", d: [1, 4] } },
            { t: "o", s: { t: "g", d: [1, 4] } },
            { t: "o", s: { t: "g", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", s: { t: "g", d: [2, 4] } },
            { t: "o", s: { t: "g", d: [1, 4] } },
            { t: "o", s: { t: "g", d: [1, 4] } },
            { t: "o", s: { t: "g", d: [1, 4] } },
            { t: "o", s: { t: "g", d: [1, 5] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [4, 6] }, s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", s: { t: "g", d: [2, 5] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "y", s: { t: "s", d: [2, 5] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", s: { t: "g", d: [2, 5] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "y" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o", s: { t: "g", d: [2, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "y" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y", r: { t: "t", d: [3, 6] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", b: "b", be: [2] },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "m" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "y" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "o" },
            { t: "m" },
            { t: "y", r: { t: "t", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "y" },
            { t: "t" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "o" },
            { t: "m" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "y" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "o" },
            { t: "m" },
            { t: "y" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "y" },
            { t: "o" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "o" },
            { t: "m" },
            { t: "y" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "y" },
            { t: "o" },
            { t: "y" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "y", r: { t: "t", d: [3, 5] } },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "y" },
            { t: "f" },
            { t: "f" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "y" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5, 6] } },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] }, b: "b", be: [1, 2] },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] }, b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o" },
            { t: "y" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] }, b: "b", be: [1, 2] },
            { t: "t" },
            { t: "t" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5] }, b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o", s: { t: "g", d: [2, 6] } },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "y" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", b: "b", be: [2] },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "t" },
            { t: "t" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "o", s: { t: "g", d: [4, 6] } },
            { t: "o", s: { t: "g", d: [1, 4] } },
            { t: "o", s: { t: "g", d: [1, 3] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "y", s: { t: "s", d: [1, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "y" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "t" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "b" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "y" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "t" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "t" },
            { t: "o", s: { t: "g", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "y" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "t" },
            { t: "t" },
          ],
        ]
      end
    end
  end
end
