# frozen_string_literal: true

module Scenarios
  class Scenario403 < Base
    ID = "403"
    NAME = "Shadows in the Jungle"
    ALLIES = ["aus"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"

    DATE = [1942, 7, 28].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": {
        list: [
          :uk_leader_4_1,
          :uk_leader_3_1,
          [9, :uk_territorial_s],
          :uk_territorial_t,
          :uk_vickers_mg,
        ],
      },
    }.freeze

    AXIS_UNITS = {
      "0": {
        list: [
          :jap_leader_5_1,
          :jap_leader_4_1,
          [6, :jap_snlf_s],
          [4, :jap_snlf_t],
          :jap_crew_t,
          [2, :jap_type_92_hmg],
          [2, :jap_type_97_81mm],
          :jap_70mm_type_92,
        ],
      },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Kokoda, Papua New Guinea",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The fight over Kokoda began when Japanese forces advancing south
          from Buna made contact with Australian defenders near the village of
          Kokoda.  This marked the opening clash of what would become the
          Kokoda Track Campaign, a brutal and strategically vital struggle for
          control of the overland route to Port Moresby through the ruggen
          Owen Stanley Range of Papua New Guinea.  At the time, Kokoda was held
          by a small force of around 80 men from the 39th Battalion, a mostly
          militia unit of young and largely inexperienced Australian soldiers.",

          "The Japanese assault force, part of the South Seas Detachment, was
          composed of seasoned troops who had landed on the north coast a week
          earlier and had begun a rapid advance toward the mountains.  The
          Australians, dug in around Kokoda, resisted fiercely despite being
          heavily outnumbered.  After hours of fighting in pitch darkness and
          thick jungle, the defenders were eventually forced to withdraw due
          to encirclement and the death of their commanding officer, Lt. Col.
          Owen.  The Japanese briefly occupied the village, but the
          Australians counterattacked and temporarily retook it days later.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [1, 2],
          wind: [0, 5, false],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [3, 6, 1], [4, 3, 1], [6, 15, 1], [7, 4, 1], [8, 3, 1], [8, 9, 1], [10, 5, 1],
          ],
          allied_setup: { "0" => [["0-10", "*"]] },
          axis_setup: { "0" => [["12-14", "*"]] },
          base_terrain: "g",
          night: true,
        }
      end

      def hexes
        [
          [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { d: [3, 5] } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "b" },
            { t: "o", d: 3, st: { sh: "h", s: "f" } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "j" },
            { t: "j" },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 4, 5] } },
            { t: "o", s: { d: [2, 5] }, r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "b" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", d: 3, st: { sh: "h", s: "f" } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o", d: 1, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", s: { d: [2, 5] } },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 3, 4, 5] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 6] } },
            { t: "o", s: { d: [2, 6] } },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "b" },
            { t: "o", d: 1, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o", s: { d: [3, 5] } },
            { t: "b" },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "b" },
            { t: "o", s: { d: [2, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "b" },
            { t: "o", s: { d: [2, 5] } },
            { t: "b" },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "j" },
          ], [
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [2, 5] } },
            { t: "b" },
            { t: "o", d: 2, st: { sh: "h", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { d: [2, 5] } },
            { t: "j" },
          ], [
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "b" },
            { t: "o", s: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { d: [2, 5] } },
          ], [
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "b" },
            { t: "o", s: { d: [2, 6] } },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 6] } },
          ], [
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "o", s: { d: [3, 5] } },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { d: [3, 5] } },
          ], [
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "o", s: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { d: [2, 5] } },
          ], [
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "o", s: { d: [2, 5] } },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "a" } },
            { t: "o" },
            { t: "o", s: { d: [2, 6] } },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", s: { d: [3, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", s: { d: [3, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", s: { d: [3, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
          ], [
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", s: { d: [3, 6] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
          ],
        ]
      end
    end
  end
end
