# frozen_string_literal: true

module Scenarios
  class Scenario034 < Base
    ID = "034"
    NAME = "Last Ride to Kharkov"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 8, 4].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_5_1,
        [2, :ussr_leader_4_1],
        [4, :ussr_rifle_s],
        [4, :ussr_smg_s],
        [3, :ussr_dp_27],
        :ussr_82_pm_41,
        [3, :ussr_t_34_m42_m43],
        [2, :ussr_t_70],
        :ussr_su_122,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :ger_leader_5_1],
        [5, :ger_rifle_s],
        :ger_crew_t,
        :ger_7_5cm_pak_40,
        [2, :ger_mg_42],
        [2, :ger_panzerfaust],
        :ger_sdkfz_250_7,
        :ger_sdkfz_250_8,
        :ger_stug_iii_b_e,
        :ger_stug_iii_f_g,
        [2, :foxhole],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Belgorod, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "During the Belgorod-Kharkov offensive operation the Soviets
          successfully liberated Belgorod and Kharkov, and attempted to
          destroy Nazi German forces of the 4th Panzer Army and Army
          Detachment Kempf. The operation was codenamed Operation General
          Rumyantsev and was conducted by the Voronezh and Steppe Fronts (army
          groups) in the southern sector of the Kursk Bulge. The battle was
          referred to as the Fourth Battle of Kharkov.",
          "The operation began on 3 August 1943, and was intended to build
          upon the successful Soviet defense in the Battle of Kursk. The main
          effort was against the German Army Group South's northern flank, and
          by the 23rd of August, the Soviets had liberated Kharkov from German
          occupation. It was the last time that Kharkov changed hands.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 1, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [6, 11, 2], [1, 17, 2], [9, 18, 2], [13, 7, 2], [2, 19, 2], [4, 14, 2], [9, 14, 2],
          ],
          allied_setup: { "0" => [["*", "0-2"]] },
          axis_setup: { "0" => [["*", "7-22"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, rr: { d: [[3, 6]] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, rr: { d: [[3, 6]] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, rr: { d: [[3, 6]] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", rr: { d: [[3, 5]] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", rr: { d: [[2, 6]] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", rr: { d: [[3, 5]] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
          ],
          [
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
          ],
          [
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
          ],
          [
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
          ],
          [
            { t: "d", d: 2 },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "d", h: 1, d: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] }, r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", rr: { d: [[2, 6]] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", h: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", rr: { d: [[3, 5]] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[2, 6]] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 4, 6] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 3, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] }, rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "d", d: [1, 3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", st: { sh: "c", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 3 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 3 },
            { t: "d", h: 1, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
