# frozen_string_literal: true

module Scenarios
  class Scenario216 < Base
    ID = "216"
    NAME = "Via Appia"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 5, 29].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_5_1,
        [2, :usa_leader_4_1],
        :usa_leader_5_2,
        [9, :usa_rifle_s],
        [4, :usa_m1918_bar],
        [2, :usa_m9_bazooka],
        :usa_radio_155mm,
        [3, :usa_m4a3e2_sherman],
        [3, :usa_m18_hellcat],
        [3, :usa_m3a1_half_track],
        :usa_m20_greyhound,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_5_1,
        :ger_leader_4_1,
        [6, :ger_fallschirmjager_s],
        [3, :ger_mg_42],
        :ger_panzerfaust,
        :ger_panzerschreck,
        :ger_kz_8cm_grw_42,
        [2, :ger_stug_iv],
        [2, :ger_jagdpanzer_iv],
        [2, :ger_crew_t],
        :ger_10_5cm_gebh_40,
        :ger_7_5cm_pak_40,
        [2, :ger_leader_6_2],
        [2, :foxhole],
        [2, :mines10],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Velletri, Italy",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "After inconclusive fighting after the landings at Anzio, both sides
          realized that nothing could be achieved until Spring. In the
          meantime, the Germans prepared a new defensive line, the Caesar C
          line south of Rome.  The Allies planned for an offensive in May,
          Operation Diadem, a push against the Gustav Line farther south
          combined with an attack inland to cut off Route 6 from the Anzio
          beachhead and any retreating German forces.",
          "Despite the overall plan for Diadem requiring the Americans to
          strike inland and cut Route 6, Clark (commander of the forces at
          Anzio) asked Truscott (commander of the American VI Corps) to
          prepare alternatives and to be ready to switch from one to another
          at 48 hours' notice. Of the four scenarios prepared by Truscott,
          Operation Buffalo called for an attack through Cisterna, into the
          gap in the hills and to cut Route 6 at Valmontone. Operation Turtle
          was an attack to the left of the Alban Hills taking Campoleone,
          Albano and on to Rome. On 5 May, Alexander selected Buffalo and
          issued Clark with orders to implement it, but Clark was determined
          that VI Corps should strike directly for Rome.",
          "By the end of 25 May, the 3rd Infantry Division was heading into
          the Velletri gap near Cori, and elements of the 1st Armoured
          Division were within 3 miles of Valmontone in contact with the
          Germans. Although VI Corps had suffered over 3,300 casualties in the
          three days fighting, Operation Buffalo was going to plan, and
          Truscott was confident that a concerted attack by the 1st Armoured
          Division and the 3rd Infantry Division the next day would reach
          Route 6. However, that evening, Truscott received new orders from
          Clark to implement Operation Turtle and turn the main line of attack
          90 degrees to the left. Although the attack towards Valmontone and
          Route 6 would continue, the 1st Armoured Division was to withdraw to
          prepare to exploit the planned breakthrough along the new line of
          attack leaving the 3rd Infantry Division to continue towards
          Valmontone without it. Truscott was shocked; to say the change was
          controversial is an understatement, being described \"as militarily
          stupid as it was insubordinate,\" and possibly added a year to the
          fighting in Italy as the German forces were allowed to escape.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 1, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [10, 4, 2], [4, 7, 2], [13, 5, 2], [4, 14, 2], [17, 16, 2], [15, 12, 2], [6, 11, 2],
          ],
          allied_setup: { "0" => [["*", "19-22"]] },
          axis_setup: { "0" => [["*", "0-16"]] },
        }
      end

      def hexes
        [
          [
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2, h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 2, h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] }, h: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 2.5, h: 1 },
            { t: "d", d: 2, h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "t", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "t", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [2, 5, 6] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2, h: 1 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "d", h: 1, d: 3 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2.5, h: 1 },
            { t: "d", d: 2, h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "d", h: 1, d: 3 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "l", s: "f" } },
            { t: "d", d: 1 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1, h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "d", d: 3, h: 1 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2.5 },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 1 },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1, h: 1 },
          ],
          [
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "o", h: 1 },
          ],
          [
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "f" },
            { t: "f" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "d", d: 2 },
            { t: "f" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "f" },
            { t: "g" },
          ],
        ]
      end
    end
  end
end
