# frozen_string_literal: true

module Scenarios
  class Scenario414 < Base
    ID = "414"
    NAME = "The Pockets"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 2, 11].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_5_1,
        :usa_leader_4_1,
        :usa_m1919_browning,
        :usa_m1917_browning,
        :usa_m1_mortar,
        [2, :usa_rifle_s],
        [3, :usa_philippine_scouts_s],
      ] },
      "4": { list: [
        :usa_rifle_s,
        [2, :usa_m3_stuart],
      ] },
      "5": { list: [
        :usa_leader_4_1,
        [2, :usa_rifle_s],
        :usa_m1919_browning,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :jap_leader_4_1],
        [6, :jap_a_division_s],
        [2, :jap_type_96_lmg],
        :jap_type_97_81mm,
      ] },
      "2": { list: [
        [2, :jap_leader_5_1],
        [7, :jap_a_division_s],
        [2, :jap_type_96_lmg],
        :jap_type_92_hmg,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Bataan, Philippines",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "During the defense of Batan, the American and Philippine troops
          established the last of many defensive lines between Orion and Bagac
          across the Bataan peninsula. The Japanese attacked and managed to
          break through to the rear, but were separated into two pockets, a
          Little Pocket consisting of about a company and a Big Pocket with
          about 1000 men.  General Wainwright, commanding the defense of Bataan,
          committed considerable forces including tanks and artillery  in an
          attempt to eliminate the Pockets. The next day a Japanese salient
          formed (the Upper Pocket) and penetrated within 800 yards of the Big
          Pocket. The day after that, the Little Pocket was surrounded by
          American troops, and eliminated two days later, allowing the
          Americans to concentrate on the Big Pocket next. The Japanese
          attempted a breakout, but only 377 Japanese escaped.",
          "By that point, General Homma recognized he only had three effective
          infantry battalions on Bataan to continue the attack, and ordered a
          halt, ordering his army to retreat to better positions and await
          reinforcements. By now the Japanese command had started to worry
          about the length of the American resistance, as it served as a
          symbol to the Filipinos that the Americans had not deserted them.
          However, by this point the defending army on Bataan's supply
          situation was dire, and they were forced to subsist on a starvation
          diet as their time began to run out.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 6, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [12, 4, 1], [8, 7, 1], [2, 10, 1], [13, 9, 1], [9, 11, 1], [7, 17, 2], [2, 5, 1],
          ],
          allied_setup: {
            "0" => [
              ["0-3", 12], ["7-14", 12], ["0-2", 13], ["8-14", 13], ["0-1", 14], ["9-13", 14],
              [0, 15], ["*", "0-11"],
            ],
            "4" => [[0, "2-16"]],
            "5" => [[14, "2-13"]],
          },
          axis_setup: {
            "0" => [
              ["4-5", 13], ["4-7", 14], ["2-7", 15], [14, 15], ["2-9", 16], ["11-14", 16],
              ["1-14", 17], ["1-14", 18], ["*", "19-22"],
            ],
            "2" => [["*", 0]],
          },
        }
      end

      def hexes
        [
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "p", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 3] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "p", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", r: { t: "p", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "j", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "j", r: { t: "p", d: [1, 3] }, h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", r: { t: "p", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", r: { t: "p", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", r: { t: "p", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "p", d: [3, 6] }, h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", r: { t: "p", d: [2, 6] }, h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "p", d: [3, 5] }, h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "p", d: [3, 5] }, h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "p", d: [2, 6] }, h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "p", d: [2, 6] }, h: 1 },
            { t: "g", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "p", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", r: { t: "p", d: [3, 5] }, h: 1 },
            { t: "g", h: 1 },
          ],
          [
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "p", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", r: { t: "p", d: [2, 5] }, h: 1 },
            { t: "g", h: 1 },
          ],
          [
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", r: { t: "p", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "p", d: [2, 5] }, h: 1 },
          ],
          [
            { t: "p", h: 1 },
            { t: "o", r: { t: "p", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", r: { t: "p", d: [2, 5] }, h: 1 },
          ],
          [
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 3] } },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "g" },
            { t: "g" },
            { t: "g", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "g" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
          ],
          [
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
          ],
          [
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
        ]
      end
    end
  end
end
