# frozen_string_literal: true

module Scenarios
  class Scenario326 < Base
    ID = "326"
    NAME = "Hill 314"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 8, 7].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_6_1,
        :usa_leader_5_2,
        :usa_leader_4_1,
        [7, :usa_rifle_s],
        [3, :usa_crew_t],
        [3, :usa_m1918_bar],
        :usa_m2_mortar,
        [2, :usa_m1919_browning],
        [2, :usa_sc],
        :usa_radio_155mm,
        [3, :usa_57mm_m1],
        [2, :usa_m1a1_bazooka],
        [4, :usa_m3_half_track],
        [2, :mines10],
        [4, :wire],
        [4, :trench],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        [2, :ger_leader_5_1],
        [2, :ger_leader_4_1],
        [7, :ger_ss_s],
        [2, :ger_pionier_s],
        [4, :ger_mg_42],
        [2, :ger_kz_8cm_grw_42],
        :ger_radio_10_5cm,
        [3, :ger_pzkpfw_iv_h_j],
        [3, :ger_panther_a_g],
        :ger_hetzer,
        [3, :ger_stug_iv],
        [2, :ger_sdkfz_251_1],
      ] },
      "3": { list: [
        :ger_leader_5_1,
        [3, :ger_ss_s],
        [2, :ger_mg_42],
        [3, :ger_pzkpfw_iii_n],
        :ger_sdkfz_166,
        :ger_marder_iii_h_m,
        [2, :ger_sdkfz_251_1],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Mortain, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "After Operation Cobra broke out from the beachhead at Normandy, the
          Allies had captured Avranches, and worked to open the gap with the
          capture of Mortain twenty miles east. Shortly after that, the 30th
          Division took over at Mortain with the mission of holding the town
          against possible enemy counterattack. That attack came on August 7th
          with a determined assault by the German XLVII Panzer Corps, which
          had been ordered to capture Mortain and Avranches at all costs.",
          "The 30th took the brunt of the 2nd SS Panzer Division's attack, and
          the American forward units fought furiously, but their 57mm
          anti-tank guns proved inadequate against the heavy German tanks,
          forcing the defenders to counter the tanks at close quarters with
          bazookas or any other weapons they could find. The center of the
          fighting was at Mortain, where east of town where the Germans
          surrounded the defenders on Hill 314. For five days, the surrounded
          Americans beat off assaults by the German 17th SS Panzergrenadier
          Division despite running low on ammunition and supplies, including
          food. Unable to effectively resupply the hill from air, the
          Americans resorted to firing shell cannisters stuffed with supplies
          into friendly lines, alleviating but not solving the supply problems
          on the hill. However, the defenders had clear views of German
          movement from the top and repeatedly called down artillery salvos
          against the German attackers, degrading both assualts on their
          position and preventing the Germans from driving on Avranches.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 5, false],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [4, 1, 1], [3, 14, 1], [7, 12, 1], [15, 12, 2], [3, 18, 1], [3, 7, 1], [7, 18, 1],
            [7, 8, 1], [5, 14, 1],
          ],
          allied_setup: {
            "0" => [
              ["0-5", "0-1"], ["0-6", "2-3"], ["0-7", "4-7"], ["0-8", "8-18"], ["6-7", 19],
            ],
          },
          axis_setup: {
            "0" => [
              ["13-22", 0], ["12-22", "1-2"], ["11-22", 3], ["12-22", "4-5"], ["13-22", "6-9"],
              ["14-22", "10-11"], ["15-22", "12-13"], ["16-22", "14-16"], ["15-22", "17-19"],
              ["16-22", "20-21"], ["17-22", 22],
            ],
            "3" => [
              [22, "0-21"], ["*", 22],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1, b: "b", be: [1] },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1, b: "b", be: [1] },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [3, 6] } },
            { t: "g", h: 1 },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 1, b: "b", be: [2] },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 2, b: "b", be: [2] },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [3, 6] } },
            { t: "g", h: 1 },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [2] },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 3 },
            { t: "g", h: 2, b: "b", be: [2, 3] },
            { t: "g", h: 2, b: "b", be: [3] },
            { t: "g", h: 1, b: "b", be: [2, 3] },
            { t: "o", h: 1 },
            { t: "o", h: 2, b: "b", be: [2, 3] },
            { t: "o", h: 2, b: "b", be: [2, 3] },
            { t: "o", h: 1, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o" },
            { t: "o", b: "b", be: [2, 3] },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 1, b: "b", be: [1, 2] },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "t", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
          ],
          [
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 5] } },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "g", h: 2 },
            { t: "o", h: 2, b: "b", be: [1, 2] },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
          ],
          [
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 4, 5] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 3] } },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2, b: "b", be: [2, 3] },
            { t: "o", h: 2, b: "b", be: [2] },
            { t: "g", h: 2, b: "b", be: [1, 2, 3] },
            { t: "g", h: 2, b: "b", be: [2, 3] },
            { t: "g", h: 1, b: "b", be: [2] },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, b: "b", be: [3] },
            { t: "g", h: 2, b: "b", be: [1] },
            { t: "g", h: 2 },
            { t: "g", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, b: "b", be: [3] },
            { t: "g", h: 2, b: "b", be: [1] },
            { t: "g", h: 2 },
            { t: "g", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 6] } },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, b: "b", be: [2, 3] },
            { t: "o", h: 2, b: "b", be: [2, 3] },
            { t: "o", h: 2 },
            { t: "o", h: 2, b: "b", be: [2, 3] },
            { t: "o", h: 1, b: "b", be: [2, 3] },
            { t: "o", h: 1, r: { t: "t", d: [3, 5] } },
            { t: "g", h: 1 },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] }, s: { t: "s", d: [2, 6] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 3, 5] } },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "g", h: 1 },
            { t: "g" },
            { t: "g" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", h: 2, r: { t: "t", d: [2, 6] } },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "g", h: 2, b: "b", be: [3] },
            { t: "o", h: 2, b: "b", be: [1] },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2, b: "b", be: [1, 2] },
            { t: "g", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", b: "b", be: [1, 2] },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "t", d: [3, 5] } },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "g", h: 2, b: "b", be: [3] },
            { t: "o", h: 2, b: "b", be: [1] },
            { t: "o", h: 2 },
            { t: "g", h: 2, b: "b", be: [1, 2] },
            { t: "g", h: 2 },
            { t: "g", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "g", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 6] } },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3, r: { t: "t", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 2, 5] } },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 3, 5] } },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 2, r: { t: "t", d: [2, 4, 6] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "t", d: [1, 3] } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "g", h: 1, b: "b", be: [2, 3] },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 1, b: "b", be: [1, 2] },
            { t: "g", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", h: 1, r: { t: "t", d: [3, 4, 6] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "g", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "g", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "g", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [3, 5] } },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, b: "b", be: [3] },
            { t: "d", h: 1, b: "b", be: [1, 2], d: 4 },
            { t: "d", h: 1, d: 4 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "t", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "g", h: 1, b: "b", be: [3] },
            { t: "g", h: 1, b: "b", be: [2] },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, b: "b", be: [2, 3] },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "g", h: 1, b: "b", be: [1] },
            { t: "g", h: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 1 },
            { t: "f", h: 1 },
            { t: "g", h: 1, b: "b", be: [3] },
            { t: "o", h: 1, b: "b", be: [1, 2, 3] },
          ],
          [
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 6] } },
            { t: "o", h: 1 },
            { t: "g", h: 1, b: "b", be: [1, 2] },
            { t: "g", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1] },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "g", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "g", h: 1, b: "b", be: [1, 2] },
            { t: "g", h: 1 },
            { t: "g", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
          ],
        ]
      end
    end
  end
end
