# frozen_string_literal: true

module Scenarios
  class Scenario027 < Base
    ID = "027"
    NAME = "Victory's End"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 3, 11].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_5_1,
        [2, :ussr_leader_4_1],
        [6, :ussr_rifle_s],
        [4, :ussr_smg_s],
        [2, :ussr_pm_m1910],
        :ussr_dshk,
        [2, :ussr_su_76m],
        [2, :ussr_su_85],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_5_1,
        [2, :ger_leader_4_1],
        [8, :ger_ss_s],
        [3, :ger_mg_42],
        :ger_ft,
        [2, :ger_sc],
        :ger_radio_10_5cm,
        [2, :ger_panther_d],
        [4, :ger_pzkpfw_iv_h_j],
        :ger_marder_iii,
        :ger_stuh_42,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Kharkov, Ukraine",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "After the German 6th Army was encircled in the Battle of
          Stalingrad, the Red Army undertook a series of wider attacks against
          the rest of Army Group South. These culminated when the Red Army
          launched Operation Star and Operation Gallop, which between January
          and early February broke German defenses and led to the Soviet
          recapture of Kharkov, Belgorod, Kursk as well as Voroshilovgrad and
          Izium. These victories caused participating Soviet units to
          over-extend themselves. Months of continuous operations had taken a
          heavy toll on the Soviet forces and some divisions were reduced to
          barely one to two thousand combat-effective soldiers. On 19
          February, Field Marshal Erich von Manstein launched his Kharkov
          counterstrike, using the fresh II SS Panzer Corps and two panzer
          armies.",
          "The Wehrmacht flanked, encircled, and defeated the Red Army's
          armored spearheads south of Kharkov. This enabled Manstein to renew
          his offensive against the city of Kharkov proper. Despite orders to
          encircle Kharkov from the north, the SS Panzer Corps instead decided
          to directly engage Kharkov. This led to four days of house-to-house
          fighting before Kharkov was recaptured by the SS Division
          Leibstandarte. The German forces recaptured Belgorod two days later,
          creating a salient, which in July would lead to the Battle of Kursk.
          The German offensive cost the Red Army an estimated 90,000
          casualties. The house-to-house fighting in Kharkov was also
          particularly bloody for the German SS Panzer Corps, which had
          suffered approximately 4,300 men killed and wounded by the time
          operations ended in mid-March.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 6, true],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [18, 6, 1], [13, 18, 1], [17, 20, 1], [11, 5, 1], [16, 10, 1], [4, 8, 2], [7, 18, 2],
            [18, 14, 1], [8, 1, 1],
          ],
          allied_setup: {
            "0" => [
              ["8-22", "0-1"], ["9-22", "2-3"], ["10-22", "4-5"], ["11-22", "6-7"],
              ["12-22", "8-10"], ["11-22", "11-13"], ["12-22", 14], ["11-22", "15-16"],
              ["10-22", "17-18"], ["9-22", "19-20"], ["8-22", "21-22"],
            ],
          },
          axis_setup: {
            "0" => [
              ["0-1", "0-1"], ["0-2", "2-3"], ["0-3", "4-5"], ["0-4", "6-7"], ["0-5", "8-9"],
              ["0-6", "10-11"], ["0-7", "12-13"], ["0-8", "14-15"], ["0-9", 16],
              ["0-8", "17-18"], ["0-7", "19-20"], ["0-6", "21-22"],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 6 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", rr: { d: [[2, 5]] }, r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "d", d: 6 },
          ],
          [
            { t: "d", d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 6 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", rr: { d: [[6, 3]] }, r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "d", d: 6 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 6 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2 },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2 },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o" },
          ],
          [
            { t: "o", d: 4, st: { sh: "s", s: "u" } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[6, 3], [1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 5]] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] }, r: { t: "t", d: [2, 5] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 3], [6, 3]] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
          ],
          [
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] }, r: { t: "t", d: [3, 6] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 3 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "d", d: 3 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "d", d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
