# frozen_string_literal: true

module Scenarios
  class Scenario036 < Base
    ID = "036"
    NAME = "On the Edge"
    ALLIES = ["ussr"].freeze
    AXIS = ["slv"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1941, 7, 22].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_4_1,
        [3, :ussr_rifle_s],
        [2, :ussr_pm_m1910],
      ] },
      "5": { list: [
        :ussr_leader_5_1,
        [3, :ussr_rifle_s],
        [2, :ussr_smg_s],
        [2, :ussr_dp_27],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :axm_leader_4_1],
        [6, :axm_regular_s],
        [3, :axm_zb_vz__30],
        [2, :axm_lt_vz__35],
        [2, :axm_lt_vz__38],
        :axm_oa_vz__30,
        :axm_radio_10_5cm,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Lypovets, Ukraine",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["axis_fragile_vehicles"],
        }
      end

      def description
        [
          "The Slovak Republic was a puppet state established by Germany after
          it annexed Czechoslovakia. It possessed a small army of its own,
          largely made up of parts inherited from the old Czechoslovak Army
          and the took part in the German invasion of Poland. When the Slovak
          government was informed about the invasion of Russia, as the regime
          sought to demonstrate that its loyalty was greater than that of
          Hungary it offered to participate, and the Slovak Army was called up
          for the invasion.",
          "The Battle of Lypovec was an armed clash fought between the Slovak
          Mobile Brigade (Slovenská rýchla brigáda) and troops of the Red Army
          during Operation Barbarossa. It was one of the first battles of
          Slovakia with the Red Army, where it faced units tasked with
          delaying their advance, not holding. The Mobile Brigade managed to
          occupy Lypovets but when it ran into the Soviets, the Slovak tanks
          ran out of fuel, and catastrophe was only avoided by artillery
          support, which managed to decimate the Soviets enough to allow the
          Slovak soldiers to retreat.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 4, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [7, 5, 1], [10, 13, 1], [11, 6, 1], [7, 15, 1], [8, 9, 1],
          ],
          allied_setup: {
            "0" => [
              ["12-14", 0], ["10-14", "1-2"], ["9-14", "3-4"], ["7-14", "5-7"], ["8-14", "8-9"],
              ["9-14", "10-12"], ["8-14", "13-14"], ["7-14", 15], ["8-14", "16-17"],
              ["13-14", "18-20"], ["12-14", 21], ["13-14", 22],
            ],
            "5" => [[14, "*"]],
          },
          axis_setup: { "0" => [["0-2", "*"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "w" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] }, s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w", s: { t: "s", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 4 },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 4] }, r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 3, 5] } },
            { t: "d", d: 4 },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 4, 6] } },
            { t: "o", s: { t: "s", d: [2, 5] }, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4, 6] }, s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [1, 3, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [4, 6] }, r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", s: { t: "s", d: [2, 3, 6] } },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "w", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
