# frozen_string_literal: true

module Scenarios
  class Scenario310 < Base
    ID = "310"
    NAME = "Hell's Highway"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"

    DATE = [1944, 9, 18].freeze
    LAYOUT = [15, 36, "x"].freeze

    ALLIED_UNITS = {
      "0": {
        list: [
          :uk_leader_6_1,
          :uk_leader_5_2,
          [3, :uk_guard_s],
          [3, :uk_guard_t],
          [2, :uk_bren_lmg],
          :uk_ml_3inch_mortar,
          :uk_radio_152mm,
          [2, :uk_cromwell],
          [3, :uk_m4_sherman],
          :uk_sherman_firefly,
          [2, :uk_universal_carrier],
          :uk_m8_greyhound,
        ],
      },
    }.freeze

    AXIS_UNITS = {
      "0": {
        list: [
          :ger_leader_5_1,
          :ger_leader_4_1,
          [4, :ger_fallschirmjager_s],
          [2, :ger_fallschirmjager_t],
          [2, :ger_crew_t],
          [2, :ger_mg_42],
          [2, :ger_7_5cm_pak_40],
        ],
      },
      "3": {
        list: [
          :ger_leader_4_1,
          [3, :ger_rifle_s],
          :ger_rifle_t,
          :ger_mg_42,
        ],
      },
      "6": {
        list: [
          :ger_leader_5_1,
          :ger_ss_s,
          :ger_ss_t,
          :ger_crew_t,
          :ger_mg_42,
          :ger_7_5cm_pak_40,
          :ger_stug_iv,
        ],
      },
    }.freeze

    class << self
      def generate
        {
          turns: 10,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Highway 69, Netherlands",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "Operation Market Garden was an Allied military operation fought in
          the September of 1944. Its objective was to cut through the
          Netherlands and punch into German territory with a bridgehead over
          the Lower Rhine River, bypassing the Siegfried Line and creating
          route for allied forces into northern Germany. This was to be
          achieved by two sub-operations: seizing nine bridges with combined
          American and British airborne forces (\"Market\") followed by
          British land forces swiftly following over the bridges
          (\"Garden\")",
          "The planned route for allied forces followed Highway 69, later
          nicknamed \"Hell's Highway,\" consisting of two narrow lanes, partly
          raised above a surrounding flat terrain of polder or floodplain. The
          ground on either side of the highway was in places too soft to
          support tactical vehicle movement and there were numerous dikes and
          drainage ditches. Dikes tended to be topped by trees or large
          bushes, and roads and paths were lined with trees, making flanking
          attacks impossible and allowing numerous positions available for
          ambushes.",
        ]
      end

      def map_data
        {
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [10, 2, 2], [6, 5, 2], [10, 9, 2], [3, 15, 2], [7, 16, 2], [11, 21, 2],
            [9, 22, 2], [4, 25, 2], [5, 32, 1],
          ],
          allied_setup: { "0" => [["*", "31-35"]] },
          axis_setup: {
            "0" => [["*", "20-29"]],
            "3" => [["*", "10-19"]],
            "6" => [["*", "0-9"]],
          },
          base_terrain: "g",
        }
      end

      def hexes
        [
          [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "d", d: 3 },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "f" },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "d", d: 3 },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "f" },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "d", d: 3 },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "f" },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "d", d: 3 },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "f" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "d", d: 3 },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "f" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "f" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "o", r: { d: [1, 4], t: "p" } },
            { t: "o", r: { d: [1, 3, 4], t: "p" } },
            { t: "o", r: { d: [1, 4], t: "p" } },
            { t: "o", r: { d: [1, 4], t: "p" } },
            { t: "o", r: { d: [1, 4], t: "p" } },
            { t: "o", r: { d: [1, 4, 5], t: "p" } },
            { t: "o", r: { d: [1, 4], t: "p" } },
            { t: "o", r: { d: [1, 4], t: "p" } },
            { t: "o", r: { d: [3, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 5], t: "g" } },
            { t: "f" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { d: [2, 5], t: "p" } },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "f" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { d: [2, 5], t: "p" } },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { d: [2, 5], t: "p" } },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 6], t: "g" } },
            { t: "o", r: { d: [2, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 4, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [2, 6], t: "p" } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "d", d: 1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "b" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "b" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "b" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "b" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "b" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { d: [3, 4], t: "p" } },
            { t: "o", r: { d: [1, 4], t: "p" } },
            { t: "o", r: { d: [3, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 5], t: "g" } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ], [
            { t: "o" },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "b" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "b" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "b" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "b" },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", d: 2, st: { sh: "l", s: "f" } },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 6], t: "g" } },
            { t: "o", r: { d: [2, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 6], t: "t", h: -1 } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ], [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [4, 6] } },
            { t: "o", h: -1, s: { d: [1, 4] } },
            { t: "w", h: -1, s: { d: [1, 4] } },
            { t: "w", h: -1 },
            { t: "w", h: -1 },
          ], [
            { t: "o", h: -1, s: { d: [1, 4] } },
            { t: "w", h: -1, s: { d: [1, 4] } },
            { t: "w", h: -1 },
            { t: "w", h: -1, s: { d: [1, 4] } },
            { t: "o", h: -1, s: { d: [1, 4] } },
            { t: "o", h: -1, s: { d: [1, 4] } },
            { t: "o", h: -1, s: { d: [1, 4] } },
            { t: "o", h: -1, s: { d: [1, 4] } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 }, s: { d: [1, 4] } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 }, s: { d: [1, 4] } },
            { t: "o", h: -1, s: { d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o" },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o" },
            { t: "f" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o" },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o" },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o" },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "d", d: 3 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o" },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "d", d: 3 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "o" },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", st: { sh: "c" } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 6], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 6], t: "g" } },
            { t: "o" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: -1, s: { d: [3, 5], t: "g" } },
            { t: "o", r: { d: [3, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [3, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [3, 5], t: "g" } },
            { t: "o" },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "d", d: 2 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "f" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "d", d: 2 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ], [
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "g", h: -1 },
            { t: "o" },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", r: { d: [2, 5], t: "t", h: -1 } },
            { t: "o", h: -1, s: { d: [2, 5], t: "g" } },
            { t: "d", d: 2 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
            { t: "t", h: -1 },
          ],
        ]
      end
    end
  end
end
