# frozen_string_literal: true

module Scenarios
  class Scenario524 < Base
    ID = "524"
    NAME = "Tanne Ost"
    ALLIES = ["fin"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 9, 15].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [3, :fin_leader_4_1],
        [5, :fin_regular_s],
        :fin_ls_26,
        :fin_81mm_tampella,
        :fin_crew_t,
        :fin_75mm_gun,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :ger_leader_5_1],
        [4, :ger_rifle_s],
        [2, :ger_mg_42],
        :ger_sdkfz_234_3,
      ] },
      "1": { list: [
        :ger_leader_4_1,
        [4, :ger_rifle_s],
        [2, :ger_mg_42],
      ] },
      "2": { list: [
        :ger_leader_4_1,
        [3, :ger_rifle_s],
        [2, :ger_mg_42],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Suursaari, Finland",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Lapland War was a war in the last year of WW II between Finland
          and Nazi Germany primarily in Finland's northernmost region,
          Lapland. Though the Finns and the Germans had been fighting together
          against the Soviet Union since 1941 during the Continuation War,
          peace negotiations between the Finnish government and the Allies had
          been conducted intermittently during 1943 and 1944, but no agreement had
          been reached. The Moscow Armistice, signed on 19 September 1944,
          demanded that Finland break diplomatic ties with Germany and expel
          or disarm any German soldiers remaining in Finland.",
          "The Wehrmacht had anticipated this turn of events and planned an
          organised withdrawal to Nazi-occupied Norway. Despite a failed
          offensive landing operation by Germany in the Gulf of Finland, the
          evacuation proceeded peacefully at first. The Finns escalated the
          situation into warfare on 28 September after Soviet pressure to
          adhere to the terms of the armistice. The Finnish Army was required
          by the Soviet Union to push Wehrmacht troops out of Finnish
          territory. After a series of minor battles, the war came to an
          effective end in November 1944, when all of the Wehrmacht troops had
          reached Norway or the border area and took fortified positions.",
          "Operation Tanne Ost (Fir East) Was a German operation at the
          beginning of the Lapland war to capture the island Suursaari in the
          Gulf of Finland before it could fall into Soviet hands. The landing
          occurred in three waves before the Finns cut off further landings;
          the invasion was not successful, and most of the invaders were
          captured.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 2, true],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [6, 3, 1], [9, 17, 1], [11, 14, 1], [8, 16, 1], [6, 8, 1],
          ],
          allied_setup: {
            "0" => [
              [6, 2], ["5-6", 3], ["4-7", 4], ["2-8", 5], ["2-9", 6], ["1-9", 7], ["2-10", 8],
              ["1-10", 9], ["2-10", "10-11"], ["2-11", 12], ["2-10", 13], ["3-10", 14],
              ["4-8", 15], ["5-8", 16], ["4-8", 17], ["4-9", 18], ["3-9", 19], ["4-9", "20-21"],
              ["5-9", 22],
            ],
          },
          axis_setup: {
            "0" => [
              [12, "10-11"], [13, 12], [12, "13-14"], [11, 15], ["11-12", 16], [10, 17], [11, 18],
            ],
            "1" => [[6, 1], [7, 2], ["7-8", 3], [9, "4-5"]],
            "2" => [[10, 19], [12, 19], ["11-13", 20], [12, "21-22"]],
          },
        }
      end

      def hexes
        [
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "o" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "b" },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "b" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "b" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "b" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "w", r: { t: "t", d: [1, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "b" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "b" },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "w", r: { t: "t", d: [2, 4] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "w" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "b" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "b" },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
        ]
      end
    end
  end
end
