# frozen_string_literal: true

module Scenarios
  class Scenario214 < Base
    ID = "214"
    NAME = "Ponte Grande"
    ALLIES = ["uk"].freeze
    AXIS = ["ita"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 7, 10].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :uk_leader_6_1],
        [5, :uk_airborne_s],
        [2, :uk_bren_lmg],
        :uk_vickers_mg,
        :uk_2inch_mortar,
      ] },
      "3": { list: [
        :uk_leader_5_1,
        [2, :uk_airborne_s],
        :uk_bren_lmg,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :ita_leader_4_1],
        [7, :ita_blackshirt_s],
        :ita_brixia_m35,
        [2, :ita_breda_30],
        [2, :ita_breda_m37],
      ] },
      "2": { list: [
        :ita_leader_3_1,
        [3, :ita_blackshirt_s],
        :ita_breda_30,
        :ita_81_14_m35,
      ] },
      "3": { list: [
        :ita_leader_4_1,
        [3, :ita_blackshirt_s],
        :ita_breda_m37,
      ] },
    }.freeze

    INIT_AXIS_UNITS = [
      { data: :pillbox, x: 8, y: 6, facing: 6 },
      { data: :pillbox, x: 12, y: 6, facing: 6 },
      { data: :pillbox, x: 5, y: 5, facing: 5 },
    ].freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Syracuse, Sicily",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          init_axis_units:,
        }
      end

      def description
        [
          "Operation Ladbroke was a glider landing operation performed by
          British airborne troops near Syracuse, Sicily during Operation
          Husky. The objective was to land a large invasion force near
          Syracuse and secure the Ponte Grande Bridge before taking control of
          the city itself with its strategically vital docks as a prelude to
          the full-scale invasion of Sicily.",
          "From the start, everything went wrong. Sixty-five gliders were
          released too early and crashed into the see, drowning 252 men. Many
          others landed in the wrong place, 40km away, or were shot down or
          failed to release and returned to the staging airfields in Tunesia.
          Only one glider with a single platoon of infantry landed near the
          bridge. Another glider landed about 200 yards from the bridge but
          exploded on landing, killing everyone on board. Nonetheless, despite
          the horrendous losses and confusion, the mission was largely
          achieved; the bridge was captured, demolition charges there were
          dismantled, and reinforcements trickled in, and the scattered
          landings elsewhere worked (mostly) to the British advantage as the
          defenders were confused by cut telephone wires and a captured radio
          station, and many (but not all) of the defending coast batteries
          were neutralized. And despite the bridge eventually being recaptured
          by the Italians, due to the demolition charges being removed, it
          never was destroyed.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 5, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [7, 6, 1], [6, 8, 1], [6, 11, 1], [5, 13, 1], [5, 18, 1],
          ],
          allied_setup: { "0" => [["*", "4-22"]], "3" => [["*", 22]] },
          axis_setup: { "0" => [["*", "0-2"]], "2" => [["*", 0]], "3" => [["*", 0]] },
        }
      end

      def hexes
        [
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
          ],
          [
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", b: "f", be: [1] },
          ],
          [
            { t: "d", d: 3 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
          ],
          [
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
          ],
          [
            { t: "d", d: 3 },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "d", d: 3 },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
        ]
      end
    end
  end
end
