# frozen_string_literal: true

module Scenarios
  class Scenario329 < Base
    ID = "329"
    NAME = "Almost the End"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 3, 6].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_6_1,
        [2, :usa_leader_5_1],
        [6, :usa_veteran_s],
        [2, :usa_m1918_bar],
        :usa_m1919_browning,
        :usa_m2_mortar,
        :usa_radio_155mm,
        [3, :usa_m4a176_sherman],
        [2, :usa_m26_pershing],
        :usa_m20_greyhound,
        :usa_m8_scott,
        [3, :usa_m4a3e2_sherman],
        [3, :usa_m3a1_half_track],
        :usa_engineer_s,
        :usa_sc,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :ger_leader_5_1],
        [5, :ger_rifle_s],
        [3, :ger_mg_42],
        :ger_kz_8cm_grw_42,
        :ger_panzerschreck,
        :ger_nashorn,
        [3, :ger_pzkpfw_iv_h_j],
        [3, :ger_stug_iv],
        [2, :mines8],
        [4, :wire],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Cologne, Germany",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Allies approached Cologne from three directions, with the 3rd
          Armored Division striking from the northwest, the 104th Infantry
          Division coming from the west, and the 9th Armored and 9th Infantry
          Divisions clearing the south of the city. On the 5th of March, the
          3rd Armored Division launched a final advance on Cologne and the
          next day moved into the heart of the city.",
          "As the Americans moved towards the Rhine, the Wehrmacht demolished
          the Hohenzollern Bridge, the last link between the east and west of
          the city. Although the Allies had failed to capture any of the
          bridges near Cologne, farther south the 9th Armored Division of the
          U.S. First Army advanced unexpectedly quickly and were surprised to
          find the Ludendorff Bridge still standing, captured in during the
          Battle of Remagen. Regardless, by the 7th of March, all of Cologne
          west of the Rhine had been captured by the Allies, and the right
          east bank would remain under German control until mid-April.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 4, false],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [12, 6, 2], [12, 11, 2], [6, 18, 2], [16, 18, 2], [18, 12, 2], [11, 17, 2], [8, 12, 2],
            [14, 2, 2], [5, 3, 2],
          ],
          allied_setup: {
            "0" => [
              ["6-22", 0], ["5-22", 1], ["6-22", "2-3"], ["7-22", "4-5"], ["8-22", "6-7"],
              ["9-22", "8-10"], ["8-22", "11-12"], ["7-22", "13-14"], ["6-22", "15-16"],
              ["5-22", "17-18"], ["4-22", "19-20"], ["3-22", "21-22"],
            ],
          },
          axis_setup: {
            "0" => [
              ["0-4", 0], ["0-3", 1], ["0-4", "2-3"], ["0-5", 4], ["0-4", "5-7"], ["0-5", 8],
              ["0-4", 9], ["0-5", "10-11"], ["0-6", 12], ["0-5", "13-14"], ["0-4", "15-16"],
              ["0-3", "17-18"], ["0-2", "19-20"], ["0-1", "21-22"],
            ],
          },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 5 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "x" },
            { t: "o" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 5 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "x" },
            { t: "o" },
          ],
          [
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "x" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 4 },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 5 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "x" },
            { t: "o" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 5 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 1 },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "b" },
            { t: "o", st: { sh: "t", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "x" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 4 },
            { t: "x" },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 4 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 5 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 5 },
            { t: "x" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] }, rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "t", d: [1, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4], [1, 3]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] }, r: { t: "t", d: [3, 6] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "b" },
            { t: "b" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "b" },
            { t: "o", st: { sh: "x", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "b" },
            { t: "b" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 6]] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "x" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] }, r: { t: "t", d: [3, 6] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4], [4, 6]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 3]] } },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "x" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "x" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o" },
            { t: "d", d: 2 },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "x" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "x" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "x" },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m", s: "u" }, d: 1 },
            { t: "x" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "b" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "u" }, d: 2 },
          ],
          [
            { t: "b" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
          ],
          [
            { t: "b" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "x" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
