# frozen_string_literal: true

module Scenarios
  class Scenario614 < Base
    ID = "614"
    NAME = "Garrison Hill"
    ALLIES = ["uk"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 4, 6].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_5_1,
        :uk_leader_4_1,
        [4, :uk_line_s],
        [4, :uk_indian_s],
        :uk_crew_t,
        [2, :uk_vickers_mg],
        :uk_qf_25pdr_short,
        [3, :foxhole],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_1,
        [2, :jap_leader_4_1],
        [10, :jap_b_division_s],
        [4, :jap_type_99_lmg],
        [2, :jap_sc],
        :jap_radio_7_5cm,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Kohima, India",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Kohima was the high point of the Japanese U-Go
          offensive into British India. It took place in three stages around
          the town of Kohima, now the capital of the state of Nagaland in
          Northeast India. The Japanese attempted to capture Kohima Ridge, a
          feature which dominated the road the British used to supply the
          British and Indian troops defending the beseiged city of Imphal.",
          "Initially the British and Indians defended the city, before
          counter-attacking and driving the Japanese from the positions they
          had captured, forcing the Japanese to abandon the ridge itself,
          though they Japanese still managed to block the Kohima-Imphal road.
          Finally, the British and Indian troops pursued the Japanese troops
          that were forced to retreat once their supply situation reached a
          breaking point, reopening the road and meeting forces from
          Imphal at Milestone 109, ending the Siege of Imphal.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 4, false],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [11, 4, 1], [6, 4, 1], [7, 8, 1], [7, 12, 1], [7, 16, 1], [4, 18, 1], [7, 19, 1],
          ],
          allied_setup: { "0" => [["0-11", "*"]] },
          axis_setup: { "0" => [["13-14", "*"]] },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "b", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "f", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 4, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 4, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 4, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 4, 6] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "b", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 4, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
          ],
          [
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2 },
            { t: "f", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o" },
            { t: "b", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "b", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "b" },
            { t: "b" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 4, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "b" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [3, 4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "b", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 4 },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 4 },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 2, 4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
        ]
      end
    end
  end
end
