# frozen_string_literal: true

module Scenarios
  class Scenario607 < Base
    ID = "607"
    NAME = "Iron Fist"
    ALLIES = ["chi"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"

    DATE = [1937, 8, 19].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :chi_leader_5_1,
        [3, :chi_leader_4_1],
        [14, :chi_elite_s],
        [6, :chi_elite_t],
        :chi_crew_t,
        [4, :chi_type_24_maxim],
        [2, :chi_type_20_mortar],
        :chi_75mm_gun,
        :chi_vickers_6_ton,
        :sniper4,
      ] },
      "2": { list: [
        :chi_leader_6_1,
        [3, :chi_elite_s],
        :chi_elite_t,
        :chi_czeck_lmg,
      ] },
      "4": { list: [
        :chi_leader_5_1,
        [5, :chi_elite_s],
        :chi_vickers_6_ton,
      ] },
      "6": { list: [
        :chi_leader_4_1,
        [2, :chi_elite_s],
        :chi_elite_t,
        :chi_czeck_lmg,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :jap_leader_6_1],
        [2, :jap_leader_5_1],
        [8, :jap_snlf_s],
        [4, :jap_snlf_t],
        [2, :jap_elite_crew_t],
        [4, :jap_type_92_hmg],
        [2, :jap_70mm_type_92],
        :jap_radio_15cm,
        :jap_chiyoda_ac,
        [6, :wire],
        [4, :pillbox],
        :sniper4,
      ] },
      "3": { list: [
        :jap_leader_4_1,
        [3, :jap_snlf_s],
        :jap_type_97_ac,
      ] },
      "5": { list: [
        :jap_leader_5_1,
        [2, :jap_snlf_s],
        :jap_snlf_t,
        :jap_type_96_lmg,
        :jap_chiyoda_ac,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 1,
          first_action: 1,
          date:,
          location: "Shanghai, China",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "During the opening days of the Battle of Shanghai, the Chinese
          sensed an opportunity.  The Japanese forces were concentrated in the
          center of Shanghai, surrounded by much more numerous Chinese troops.
          Chiang Kai-shek decided to commit his best unit, the 88th Division,
          to attempt to capture the Japanese headquarters near Zhabei as part
          of a larger offensive to drive the Japanese from Shanghai.  Trained
          by German advisers, the division had not entirely completed its
          training or been completely equipped before being rushed to Shanghai
          to face the Japanese, but nonetheless on August 13th, they attacked.
          The ensuing battle was brutal, and due to poor artillery
          coordination, the division made limited progress in the first two
          days of the battle.  On the 16th, they commenced a second attack
          using German-trained assault tactics: operation Iron Fist.  While
          the attack was successful at first, the Japanese countered by
          deploying several tanks and armored cars, and eventually halted the
          attack.  This led the Chinese to deploy their own tanks on the
          19th.",
          "While the Chinese were able to push the Japanese almost all the way
          back to the Huangpu river, ultimately they failed to break through,
          and several months later the Japanese would win the battle
          completely.  The Japanese would not be driven from Shanghai until they
          were finally and completely defeated by the Allies eight years later.",
          "Japanese artillery represents support elements of the third fleet
          stationed in the Yangtze and Huangpu Rivers.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [0, 6, true],
          hexes:,
          layout:,
          allied_dir: 1.5,
          axis_dir: 4.5,
          victory_hexes: [
            [2, 12, 1], [2, 20, 1], [4, 16, 2], [7, 6, 1], [7, 18, 2], [9, 13, 2],
            [11, 18, 2], [16, 6, 1], [16, 18, 2], [19, 10, 2], [20, 14, 2],
          ],
          allied_setup: {
            "0": [
              ["0-2", "*"], ["*", "0-8"],
            ],
            "2": [[0, "*"], ["*", 0]],
            "4": [[0, "*"], ["*", 0]],
            "6": [[0, "*"], ["*", 0]],
          },
          axis_setup: {
            "0": [["4-22", "10-22"]],
            "3": [[22, "11-19"]],
            "5": [[22, "11-19"]],
          },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4, 6], t: "t" } },
          ], [
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 4, st: { sh: "l", s: "f" }  },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 4, st: { sh: "l", s: "f" }  },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 4, st: { sh: "l", s: "f" }  },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 4, st: { sh: "l", s: "f" }  },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", d: 1, st: { sh: "s", s: "f" } },
            { t: "o", d: 4, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "o" },
          ], [
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 4, st: { sh: "l", s: "f" }  },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 4, st: { sh: "l", s: "f" }  },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 4, st: { sh: "l", s: "f" }  },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 1, st: { sh: "l", s: "f" }  },
            { t: "o", d: 4, st: { sh: "l", s: "f" }  },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "d", d: 2 },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [3, 4, 6], t: "t" } },
            { t: "f", r: { d: [1, 5], t: "p" } },
            { t: "f" },
            { t: "f", r: { d: [3, 6], t: "p" } },
            { t: "o" },
          ], [
            { t: "o", r: { d: [2, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", d: 6, st: { sh: "m", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "f" },
            { t: "f", r: { d: [2, 4], t: "p" } },
            { t: "o", r: { d: [1, 3, 6], t: "p" } },
            { t: "w" },
            { t: "b" },
          ], [
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", d: 2, st: { sh: "m", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 6, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { d: [3, 5], t: "p" } },
            { t: "w" },
            { t: "b" },
          ], [
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "x", s: "f" } },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "p" } },
            { t: "b" },
            { t: "o", r: { d: [3, 6], t: "t" } },
          ], [
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [2, 4, 6], t: "t", c: "l" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 3, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4], t: "t" } },
            { t: "o", r: { d: [1, 3, 6], t: "t" } },
          ], [
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [3, 5], t: "t", c: "r" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "d", d: 2 },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", d: 1, st: { sh: "s", s: "f" } },
            { t: "o", d: 1, st: { sh: "m", s: "f" } },
            { t: "o", d: 4, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
          ], [
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 6], t: "t", c: "l" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "d", d: 2 },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "m", s: "f" } },
            { t: "w" },
            { t: "o", d: 3, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
          ], [
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [3, 4, 5], t: "t", c: "r" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", d: 3, st: { sh: "m", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
          ], [
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", d: 4, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [2, 6], t: "t", c: "l" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "d", d: 2 },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "m", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 2, st: { sh: "m", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 6, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
          ], [
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3, 5], t: "t", c: "r" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "d", d: 2 },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
          ], [
            { t: "o", d: 1, st: { sh: "s", s: "f" } },
            { t: "o", d: 4, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 4, 5, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 3, 5], t: "t" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
          ], [
            { t: "d", d: 1 },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "bc1" } },
            { t: "o", d: 1, st: { sh: "bs2" } },
            { t: "o", d: 1, st: { sh: "bc3" } },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "bs3" } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", d: 2, st: { sh: "bs1" } },
            { t: "o", d: 2, st: { sh: "bc1" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 3, st: { sh: "l", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 1, st: { sh: "l", s: "f" } },
          ], [
            { t: "o", s: { d: [1, 4] } },
            { t: "o", r: { d: [3, 6], t: "t" }, s: { d: [1, 5] } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 4, st: { sh: "bc3" } },
            { t: "o", d: 4, st: { sh: "bs2" } },
            { t: "o", d: 4, st: { sh: "bc1" } },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "bs1" } },
            { t: "o", d: 4, st: { sh: "bs1" } },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 5, st: { sh: "bc2" } },
            { t: "o", d: 2, st: { sh: "bm" } },
            { t: "o", d: 2, st: { sh: "bc2" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "m", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 4, 5, 6], t: "t" } },
            { t: "o", r: { d: [1, 3, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
          ], [
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "o", s: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "m", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "t" } },
            { t: "o" },
            { t: "o", d: 4, st: { sh: "bs3" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", d: 5, st: { sh: "bc1" } },
            { t: "o", d: 5, st: { sh: "bs1" } },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "d", d: 2 },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", d: 1, st: { sh: "s", s: "f" } },
          ], [
            { t: "o", d: 1, st: { sh: "s", s: "f" } },
            { t: "o", d: 4, st: { sh: "s", s: "f" } },
            { t: "o", s: { d: [2, 6] } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", r: { d: [2, 4, 5, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "o", b: "w", be: [3, 4] },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "m", s: "f" } },
          ], [
            { t: "d", d: 1 },
            { t: "o", s: { d: [3, 5] } },
            { t: "d", d: 2 },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", b: "w", be: [1, 2, 3] },
            { t: "o", d: 1, st: { sh: "bc1" }, b: "w", be: [2, 3] },
            { t: "o", d: 1, st: { sh: "bc2" }, b: "w", be: [2, 3] },
            { t: "o", b: "w", be: [2, 3] },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "bc1" }, b: "w", be: [2, 3] },
            { t: "o", d: 1, st: { sh: "bs2" }, b: "w", be: [2, 3] },
            { t: "o", d: 1, st: { sh: "bc2" }, b: "w", be: [2, 3] },
            { t: "o", b: "w", be: [2, 3] },
            { t: "o", b: "w", be: [2, 3] },
            { t: "o", d: 1, st: { sh: "bc1" }, b: "w", be: [2, 3] },
            { t: "o", d: 1, st: { sh: "bc2" }, b: "w", be: [2, 3] },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 4, st: { sh: "t" } },
            { t: "o", d: 4, st: { sh: "t" } },
            { t: "o", d: 4, st: { sh: "t" }, b: "w", be: [3, 4] },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
          ], [
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", d: 2, st: { sh: "s", s: "f" } },
            { t: "o", s: { d: [2, 5] } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 1, st: { sh: "t" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "bs1" } },
            { t: "o", d: 1, st: { sh: "bm" } },
            { t: "o", d: 4, st: { sh: "bs1" } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "bs1" } },
            { t: "o", d: 1, st: { sh: "bm" } },
            { t: "o", d: 1, st: { sh: "bm" } },
            { t: "o", d: 4, st: { sh: "bs1" } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "bs1" } },
            { t: "o", d: 1, st: { sh: "bm" } },
            { t: "o", d: 4, st: { sh: "bs1" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 4, st: { sh: "t" } },
            { t: "o", d: 4, st: { sh: "t" } },
            { t: "o", d: 4, st: { sh: "t" }, b: "w", be: [3, 4] },
            { t: "o", r: { d: [2, 5], t: "t" } },
          ], [
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", d: 5, st: { sh: "s", s: "f" } },
            { t: "o", s: { d: [2, 5] }, r: { d: [3, 6], t: "t" } },
            { t: "d", d: 2 },
            { t: "o", d: 1, st: { sh: "t" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 4, st: { sh: "bc2" } },
            { t: "o", d: 4, st: { sh: "bc1" } },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 4, st: { sh: "bc2" } },
            { t: "o", d: 4, st: { sh: "bs2" } },
            { t: "o", d: 4, st: { sh: "bc1" } },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 4, st: { sh: "bc2" } },
            { t: "o", d: 4, st: { sh: "bc1" } },
            { t: "o" },
            { t: "o", r: { d: [2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4], t: "t" } },
          ], [
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3, 5], t: "t" } },
            { t: "o", s: { d: [2, 6] } },
            { t: "d", d: 2 },
            { t: "o", d: 1, st: { sh: "t" } },
            { t: "o", r: { d: [2, 6], t: "t" } },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 4, st: { sh: "t" } },
            { t: "o", d: 4, st: { sh: "t" } },
            { t: "o", d: 4, st: { sh: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ], [
            { t: "o", d: 1, st: { sh: "bc2" } },
            { t: "o" },
            { t: "o", r: { d: [2, 4], t: "t" }, s: { d: [3, 5] } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ], [
            { t: "o", d: 1, st: { sh: "bm" } },
            { t: "o", d: 4, st: { sh: "bs1" } },
            { t: "d", d: 1 },
            { t: "w", s: { d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
        ]
      end
    end
  end
end
