# frozen_string_literal: true

module Scenarios
  class Scenario518 < Base
    ID = "518"
    NAME = "The Knife's Edge"
    ALLIES = ["nz"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1941, 5, 20].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_5_1,
        :uk_leader_4_1,
        [5, :uk_line_s],
        [2, :uk_vickers_mg],
        [2, :uk_ml_3inch_mortar],
        :uk_matilda_ii_cs,
        :uk_crew_t,
        :uk_qf_25_pounder,
        [3, :foxhole],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_2,
        :ger_leader_5_2,
        :ger_leader_5_1,
        [8, :ger_fallschirmjager_s],
        [4, :ger_mg_34],
        [2, :ger_5cm_legrw_36],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Maleme, Crete",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Maleme was one of three main battles that occurred in
          the Battle of Crete against the Fallschirmjäger. The German plan was
          to conquer Crete with German Paratroopers landing in three main
          areas, Heraklion, Maleme and Rethymno. The operation relied on
          German airborne troops, both paratroopers and in military gliders.
          Due to miscommunication, and despite being in a superior position,
          New Zealand troops abandoned a strategic hill, leaving it to the
          Germans, and then lost the airfield. Counterattacks by the New
          Zealand troops were unable to recapture the airfield or prevent the
          Germans from landing reinforcements, and the whole island was
          subsequently lost to the Germans.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [4, 3, true],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [18, 8, 1], [13, 4, 1], [11, 7, 1], [15, 6, 1], [8, 6, 1], [4, 12, 1], [14, 14, 1],
          ],
          allied_setup: {
            "0" => [["3-22", 11], ["4-18", 12], ["13-16", 13], ["14-15", 14], ["*", "0-10"]],
          },
          axis_setup: {
            "0" => [
              ["0-1", 13], ["0-3", "14-15"], ["0-4", 16], ["0-12", 17], ["0-15", "18-19"],
              ["0-16", 20], ["0-17", 21], ["0-19", 22],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w", s: { t: "s", d: [3, 6] } },
            { t: "w" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "b", s: { t: "s", d: [3, 5] } },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 3, 4, 6] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "b" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", d: 3 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "d", d: 2 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] }, s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 1, d: 2 },
            { t: "o", r: { t: "t", d: [2, 6] }, h: 1 },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "t", d: [3, 5] }, h: 1 },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
          ],
          [
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "d", d: 3 },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o" },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [2, 3, 4, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] }, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
          ],
          [
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
          ],
          [
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 1 },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 1 },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 1 },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
        ]
      end
    end
  end
end
