# frozen_string_literal: true

module Scenarios
  class Scenario999 < Base
    ID = "999"
    NAME = "Desert Sands"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze

    class << self
      def generate
        {
          turns: 6,
          first_setup: 1,
          first_move: 2,
          date: [1941, 11, 21],
          location: "Bir el Gubi, Libya",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "Counterattack by the Italian Ariete armored division.  Part of Operation Crusader
          and the attempt to relieve the siege of Tobruk.",
        ]
      end

      def map_data
        {
          hexes:,
          layout: [15, 21, "x"],
          allied_edge: "r",
          axis_edge: "l",
          victory_hexes: [],
          allied_setup: { "0" => [] },
          axis_setup: { "0" => [] },
        }
      end

      def hexes
        [
          [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
            { t: "s" },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
            { t: "s" },
            { t: "s" },
            { t: "s" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "s" },
            { t: "o", r: { d: [3, 6] } },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "o", r: { d: [3, 5, 6] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "o" },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 2, 5] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "o" },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "s", r: { d: [3, 4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s", r: { d: [2, 5] } },
            { t: "s" },
            { t: "s" },
            { t: "s" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "b" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [2, 5] } },
            { t: "s" },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s", r: { d: [4, 6] } },
            { t: "s", r: { d: [1, 4] } },
            { t: "s", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "s", r: { d: [1, 3] } },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "s", r: { d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s", r: { d: [2, 5] } },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s", r: { d: [2, 5] } },
          ],
        ]
      end

      def allied_units
        {
          s: { list: [
            :uk_leader_5_2,
            :uk_leader_4_1,
            [8, :uk_line_s],
            [2, :uk_elite_crew_t],
            [2, :uk_vickers_mg],
            [2, :uk_boys_at_rifle],
            [2, :uk_qf_6pdr_mk_ii],
            [2, :uk_universal_carrier],
            [2, :uk_valentine_i_vii],
            [2, :uk_matilda_ii_cs],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
        }
      end

      def axis_units
        {
          s: { list: [
            :ger_leader_6_2,
            :ger_leader_5_1,
            [6, :ger_rifle_s],
            [2, :ger_mg_34],
            [2, :ger_sdkfz_250_1],
            :ger_sdkfz_221,
            [5, :ger_pzkpfw_iii_j],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
        }
      end
    end
  end
end
