# frozen_string_literal: true

module Scenarios
  class Scenario416 < Base
    ID = "416"
    NAME = "Red Beach"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 2, 1].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :usa_leader_5_1],
        :usa_leader_4_1,
        [2, :usa_engineer_s],
        :usa_ft,
        [2, :usa_sc],
        [4, :usa_rifle_s],
        :usa_radio_8inch,
        [2, :usa_m1918_bar],
        :usa_m1919_browning,
        [2, :usa_lvta_2],
      ] },
      "2": { list: [
        :usa_leader_4_1,
        [4, :usa_rifle_s],
        :usa_m2_mortar,
        :usa_m1919_browning,
        :usa_ft,
      ] },
      "6": { list: [
        :usa_leader_4_1,
        [2, :usa_rifle_s],
        :usa_m1918_bar,
        [2, :usa_m4_sherman],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_6_1,
        :jap_leader_5_1,
        :jap_leader_4_1,
        [8, :jap_b_division_s],
        [2, :jap_type_89_gren_l],
        [2, :jap_type_96_lmg],
        :jap_crew_t,
        :jap_70mm_type_92,
        [2, :jap_type_92_hmg],
        :sniper4,
      ] },
      "4": { list: [
        :jap_leader_5_1,
        :jap_leader_4_1,
        [5, :jap_b_division_s],
        [2, :jap_type_96_lmg],
        [2, :jap_sc],
        [2, :jap_type_94],
      ] },
    }.freeze

    INIT_ALLIED_UNITS = [
      { data: :bunker, x: 4, y: 8, facing: 1 },
      { data: :bunker, x: 5, y: 16, facing: 1 },
      { data: :bunker, x: 21, y: 19, facing: 5 },
      { data: :bunker, x: 13, y: 20, facing: 6 },
    ].freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Kwajalein, Marshall Islands",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          init_allied_units:,
        }
      end

      def description
        [
          "The Battle of Kwajalein was fought on Kwajalein Atoll in the
          Marshall Islands. Employing learned lessons from the Battle of
          Tarawa, the United States launched a successful twin assault on the
          main islands of Kwajalein on the south end of the atoll as well as
          Roi-Namur to the north. The Japanese defenders put up stiff
          resistance, but were outnumbered and inadequately prepared. They had
          not realized until the Battle of Tarawa that American amphibious
          vehicles could cross coral reefs and land on the lagoon side of an
          atoll and had built the strongest defenses facing the ocean.  In
          addtion, the bombardment was devastating — the U.S. Navy had changed
          its bombardment tactics based on the experience of Tarawa and used
          armor-piercing shells as well as firing into the island at closer
          ranges.",
          "For the US, the battle represented both the next step in its
          island-hopping march to Japan and a significant morale victory as it
          was the first time the Americans had penetrated the \"outer ring\"
          of the Japanese Pacific sphere. For the Japanese, the battle
          represented the failure of beach-line defenses. From that point
          forward the Japanese defenses were prepared in depth, and the
          Battles of Peleliu, Guam, and the Marianas proved far more costly to
          the attackers.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [4, 3, true],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [4, 8, 2], [5, 16, 2], [8, 3, 2], [19, 6, 2], [14, 7, 2], [12, 13, 2], [18, 17, 2],
            [12, 19, 2], [20, 16, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-7", 0], ["0-6", "1-2"], ["0-4", "3-4"], ["0-3", "5-6"], ["0-2", "7-9"],
              ["0-3", "10-13"], ["0-4", 14], ["0-3", "15-16"], ["2-3", 17], [4, 18],
            ],
            "2" => [
              ["0-6", 0], ["0-5", "1-2"], ["0-4", "3-4"], ["0-3", "5-6"],
              ["0-2", "7-13"], ["0-3", 14], ["0-2", 15], ["0-3", 16], ["2-3", 17], [4, 18],
            ],
            "6" => [
              ["0-7", 0], ["0-6", "1-2"], ["0-5", "3-4"], ["0-4", "5-6"], ["0-3", "7-13"],
              ["0-4", 14], ["0-3", 15], ["0-4", 16], ["2-4", 17], ["4-5", 18],
            ],
          },
          axis_setup: {
            "0" => [
              ["9-22", 0], ["8-22", "1-2"], ["7-22", 3], ["6-22", 4], ["5-22", "5-6"],
              ["4-22", "7-9"], ["5-22", "10-13"], ["6-22", 14], ["5-22", "15-17"],
              ["6-22", "18-19"], ["7-22", "20-21"], ["8-22", 22],
            ],
            "4" => [[22, "*"]],
          },
          base_terrain: "d",
        }
      end

      def hexes
        [
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "x" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [1, 4] } },
            { t: "o", r: { t: "p", d: [1, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "c" },
            { t: "c" },
            { t: "o" },
            { t: "c" },
            { t: "o", r: { t: "p", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", s: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [2, 4] } },
            { t: "o", r: { t: "p", d: [1, 4] } },
            { t: "o", r: { t: "p", d: [1, 4] } },
            { t: "o", r: { t: "p", d: [1, 4] } },
            { t: "o", r: { t: "p", d: [1, 5] } },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "p" },
            { t: "p" },
            { t: "p" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", s: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "c" },
            { t: "p" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 3 },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "c" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "c" },
            { t: "p" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 3 },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "c" },
            { t: "p" },
            { t: "p" },
            { t: "c" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", s: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "c" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "s" },
            { t: "x" },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "c" },
            { t: "p" },
            { t: "c" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "x" },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "c" },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "t", d: [4, 6] } },
            { t: "c" },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o" },
            { t: "o", s: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "c" },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "c" },
            { t: "x" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
        ]
      end
    end
  end
end
