# frozen_string_literal: true

module Scenarios
  class Scenario042 < Base
    ID = "042"
    NAME = "Steel Tide"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 7, 12].freeze
    LAYOUT = [32, 36, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :ussr_leader_6_1],
        [2, :ussr_leader_5_1],
        [2, :ussr_leader_4_1],
        [10, :ussr_guards_rifle_s],
        [4, :ussr_guards_smg_s],
        [7, :ussr_dp_27],
        :ussr_dshk,
        [2, :ussr_sg_43],
        [2, :ussr_82_pm_41],
        :ussr_radio_152mm,
        [8, :ussr_t_34_m42_m43],
        [4, :ussr_t_34_85],
        [3, :ussr_su_85],
        [3, :ussr_su_152],
        [3, :ussr_su_122],
        [6, :ussr_m9_half_track],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_5_1,
        [2, :ger_leader_4_1],
        [9, :ger_ss_s],
        [3, :ger_elite_crew_t],
        [6, :ger_mg_42],
        [2, :ger_kz_8cm_grw_42],
        [2, :ger_panzerfaust],
        :ger_radio_15cm,
        [2, :ger_7_5cm_pak_40],
        :ger_8_8cm_pak_43,
        [7, :ger_pzkpfw_iv_g],
        [3, :ger_stug_iii_f_g],
        :ger_marder_iii_h_m,
        [2, :ger_jagdpanzer_iv],
        [8, :trench],
        [4, :ger_sdkfz_251_1],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Prokhorovka, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "In spring of 1943, the German leadership began preparing for
          Operation Citadel, with the objective of enveloping and destroying
          the Soviet forces in the Kursk salient by attacking and breaking
          through the base of the salient from north and south simultaneously.
          The German offensive was delayed several times and the Soviet high
          command, Stavka, had learned of the German intentions and so used
          the delay to prepare and dig in along the routes of the planned
          German offensive. The Soviet leadership also massed several armies
          as a reserved deep behind their defenses and planned to launch
          counteroffensives once the German attack had dissipated. It would be
          one of the largest tank battles in history",
          "After the Wehrmacht launched its offensive, the German forces
          bogged down within four days on the northern side of the salient. On
          the southern side, the German 4th Panzer Army attacked the Soviet
          defenses and made slow but steady progress through the Soviet
          defensive lines.",
          "After a week of fighting, the Soviets launched their
          counteroffensives: one in the north and another it the south. On the
          southern side of the salient near Prokhorovka, the 5th Guards Tank
          Army engaged the II SS-Panzer Corps of the 4th Panzer Army,
          resulting in a large clash of armoured fighting vehicles. The 5th
          Guards Tank Army suffered significant losses but succeeded in
          preventing the Wehrmacht from capturing Prokhorovka and breaking
          through. The Red Army went on a general offensive and had now seized
          the strategic initiative on the Eastern Front, holding it for the
          rest of the war.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 4, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [24, 8, 2], [2, 29, 2], [27, 16, 2], [10, 21, 2], [10, 11, 2], [18, 11, 2], [24, 28, 2],
            [18, 21, 2], [7, 9, 2], [29, 25, 2], [16, 31, 2],
          ],
          allied_setup: {
            "0" => [
              ["20-31", 3], ["21-31", "4-5"], ["24-31", "6-7"], ["26-31", "8-9"], ["27-31", 10],
              ["26-31", "11-13"], ["27-31", "14-15"], ["28-31", 16], ["27-31", 17],
              ["28-31", "18-19"], ["29-31", "20-21"], ["30-31", "22-23"], [31, "24-25"],
              ["*", "0-2"],
            ],
          },
          axis_setup: {
            "0" => [
              ["0-1", 6], ["0-3", 7], ["0-4", 8], ["0-7", 9], ["23-24", 9], ["0-8", 10],
              ["23-25", 10], ["0-12", 11], ["16-17", 11], ["22-24", 11], ["0-24", "12-13"],
              ["0-25", "14-15"], ["0-26", 16], ["0-25", 17], ["0-26", "18-19"], ["0-27", "20-21"],
              ["0-28", "22-23"], ["0-29", "24-25"], ["0-30", "26-27"], ["*", "28-35"],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "w", s: { t: "s", d: [1, 4] } },
            { t: "w" },
            { t: "f" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 4, 6] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] }, r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 4, 5] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [2, 6] }, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "w", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "b" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "w", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 3, st: { sh: "l", s: "f" }, d: 2 },
            { t: "g", h: 3 },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", h: 3, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", h: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] }, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 1, s: { t: "s", d: [4, 6] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 3] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 2, s: { t: "s", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 5] } },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 2, s: { t: "s", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
        ]
      end
    end
  end
end
