# frozen_string_literal: true

module Scenarios
  class Scenario314 < Base
    ID = "314"
    NAME = "Push, Counter, Pull"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 6, 12].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_6_2,
        :usa_leader_5_2,
        [2, :usa_leader_5_1],
        [12, :usa_paratroop_s],
        [3, :usa_m1918_bar],
        :usa_m2_mortar,
        :usa_m1a1_bazooka,
      ] },
      "2": { list: [
        :usa_leader_5_1,
        [4, :usa_paratroop_s],
        :usa_m1918_bar,
      ] },
      "11": { list: [
        :usa_leader_5_1,
        :usa_leader_4_1,
        [4, :usa_rifle_s],
        :usa_m1918_bar,
        :usa_m1a1_bazooka,
        [2, :usa_m3_half_track],
        [4, :usa_m4_sherman],
        :usa_radio_155mm,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        [2, :ger_leader_5_1],
        [6, :ger_fallschirmjager_s],
        [2, :ger_mg_42],
        :ger_5cm_legrw_36,
        [2, :ger_elite_crew_t],
        :ger_7_5cm_gebg_36,
        :ger_7_5cm_pak_40,
      ] },
      "6": { list: [
        :ger_leader_5_1,
        :ger_leader_4_1,
        [5, :ger_ss_s],
        [2, :ger_mg_42],
      ] },
      "7": { list: [
        [2, :ger_leader_4_1],
        [5, :ger_ss_s],
        [2, :ger_mg_42],
        [2, :ger_sdkfz_251_1],
        :ger_radio_15cm,
      ] },
      "8": { list: [
        :ger_leader_4_1,
        [3, :ger_ss_s],
        :ger_mg_42,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 15,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Carentan, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Carentan was battle between airborne forces of the
          United States and the Germandy during the Battle of Normandy. The
          objective of the attacking American forces was consolidation of the
          U.S. beachheads and establishment of a continuous defensive line
          against expected German counterattacks. The defending German force
          attempted to hold the town long enough to allow reinforcements en
          route from the south to arrive, prevent or delay the linking of the
          American lines, and keep the U.S. First Army from launching an
          attack that would cut off the Cotentin Peninsula.",
          "Carentan was defended by two battalions of the
          Fallschirmjäger-Regiment 6 (6th Parachute Regiment) of the 2nd
          Fallschirmjäger-Division. The 17th SS Panzergrenadier Division,
          ordered to reinforce Carentan, was delayed by transport shortages
          and attacks by Allied aircraft. The attacking 101st Airborne
          Division, landed by parachute as part of the American airborne
          landings in Normandy, was ordered to seize control of Carentan.",
          "In the ensuing battle, the 101st attacked across the causeway into
          Carentan where forced the German forces to withdraw. The
          panzergrenadiers counter-attacked the next day. Initially
          successful, its attack was thrown back by Combat Command A of the
          U.S. 2nd Armored Division.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 5, true],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [20, 17, 2], [5, 9, 2], [9, 7, 2], [15, 11, 2], [18, 6, 1], [2, 3, 1], [9, 14, 2],
            [11, 15, 2], [5, 16, 2], [9, 19, 2], [14, 15, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-4", 3], ["14-22", 3], ["0-4", 4], ["15-22", 4], ["0-3", 5], ["15-22", 5],
              ["16-22", 6], ["*", "0-2"],
            ],
            "2" => [["*", 0]],
            "11" => [["*", 0]],
          },
          axis_setup: {
            "0" => [["5-13", 5], ["5-14", 6], ["0-14", 7], ["*", "8-22"]],
            "6" => [["*", 22]],
            "7" => [["*", 22]],
            "8" => [["*", 22]],
          },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "m" },
            { t: "m" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "m" },
            { t: "m" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w", s: { t: "s", d: [2, 4, 6] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [3, 6] }, r: { t: "d", d: [2, 5] } },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "m" },
            { t: "m" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "w", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ],
          [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [2, 6] }, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "g" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2] },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "c", s: "u" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] }, s: { t: "s", d: [3, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "b", be: [3] },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "b", be: [2, 3] },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "b", be: [2] },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "g" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "g" },
            { t: "g" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1] },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "g" },
            { t: "g" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
          ],
          [
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2] },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "g", h: 1, b: "b", be: [1, 2, 3] },
            { t: "f", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "c", s: "u" }, d: 3 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "g", h: 1, b: "b", be: [1, 2, 3] },
            { t: "o", h: 1, b: "b", be: [1, 3] },
            { t: "g", b: "b", be: [1, 3] },
            { t: "o", b: "b", be: [1] },
            { t: "g" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, b: "b", be: [3] },
            { t: "g", b: "b", be: [1, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [1, 2] },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "c", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", h: 1 },
            { t: "g", h: 1, b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g", b: "b", be: [3] },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [1, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [2] },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
