# frozen_string_literal: true

module Scenarios
  class Scenario007 < Base
    ID = "007"
    NAME = "Clash of Steel"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "a"

    class << self
      def generate
        {
          turns: 6,
          first_setup: 1,
          first_move: 2,
          date: [1943, 7, 5],
          location: "Orel, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The battle of Kursk began with the launch of Operation Citadel by
          the German army, which had the goal of encircling Soviet forces in
          the Kursk salient via pincer attacks from the north and south.  On
          the north side, the initial German attack was spearheaded by assault
          guns and heavy (Tiger) tanks. While most of the front was heavy
          fortified and mined, intelligence obtained from prisoner
          interrogation identified a weakness at the boundary of the 15th and
          81st Rifle Divisions caused by the German preliminary artillery
          bombardment; accordingly, the Tigers tanks of the spearhead were
          redeployed to strike towards this area.",
          "The Red Army recognized the threat and countered with a large force
          of T-34s.  In the resulting three-hour battle,  The Soviet armoured
          units lost 42 tanks while the Germans lost two Tigers and a further
          five more immobilized with track damage.  While the Red Army
          counter-attack was defeated and the first defensive belt breached,
          the fighting had delayed the Germans long enough for the rest of
          29th Rifle Corps of the 13th Army — initially deployed behind the
          first belt — to move forward and seal the breach",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [1, 3, true],
          hexes:,
          layout: [15, 23, "x"],
          allied_edge: "t",
          axis_edge: "b",
          victory_hexes: [
            [2, 1, 2], [4, 2, 2], [5, 7, 1], [11, 10, 1], [7, 12, 1], [7, 18, 1], [6, 20, 1],
          ],
          allied_setup: { "0" => [["*", "7-22"]] },
          axis_setup: { "0" => [["*", "0-3"]] },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "l" } },
            { t: "o", r: { d: [3, 6] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f" },
            { t: "o", d: 2, st: { sh: "l" } },
            { t: "o", r: { d: [2, 4, 5] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "f" },
            { t: "o", d: 2, st: { sh: "l" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "l" } },
            { t: "f" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2, 6] },
            { t: "g" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 6] },
            { t: "g" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 5, 6] },
            { t: "g", b: "f", be: [5, 6] },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 4] } },
          ], [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "g" },
            { t: "g" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 6] } },
            { t: "o", d: 2, st: { sh: "c" } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "g" },
            { t: "g" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2, 3] },
            { t: "g", b: "f", be: [2, 3] },
            { t: "o", r: { d: [3, 4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", d: 1, st: { sh: "x", s: "f" } },
            { t: "o" },
            { t: "g" },
            { t: "g", b: "f", be: [3, 4, 5] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g", b: "f", be: [4, 5] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2, 6] },
            { t: "g" },
            { t: "o", r: { d: [3, 5] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "f", be: [4, 5] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 5, 6] },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "g", b: "f", be: [5] },
            { t: "g", b: "f", be: [5, 6] },
            { t: "g", b: "f", be: [4, 5, 6] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "l" } },
            { t: "o", r: { d: [2, 5, 6] } },
            { t: "o", d: 2, st: { sh: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o", r: { d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end

      def allied_units
        {
          "0": { list: [
            :ussr_leader_6_1,
            :ussr_leader_4_1,
            [3, :ussr_rifle_s],
            [2, :ussr_smg_s],
            [2, :ussr_crew_t],
            :ussr_dp_27,
            :ussr_120_pm_38,
            [2, :ussr_57mm_zis_2],
            [4, :ussr_t_34_m42_m43],
            [2, :ussr_su_122],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
        }
      end

      def axis_units
        {
          "0": { list: [
            :ger_leader_6_2,
            :ger_leader_4_1,
            [5, :ger_rifle_s],
            [2, :ger_mg_42],
            :ger_radio_15cm,
            :ger_sdkfz_222,
            [2, :ger_sdkfz_251_1],
            [2, :ger_stuh_42],
            [5, :ger_tiger_i],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
        }
      end
    end
  end
end
