# frozen_string_literal: true

module Scenarios
  class Scenario522 < Base
    ID = "522"
    NAME = "Kollaa Kestää"
    ALLIES = ["ussr"].freeze
    AXIS = ["fin"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1940, 3, 2].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :ussr_leader_4_1],
        [3, :ussr_rifle_s],
        [2, :ussr_smg_s],
        :ussr_dp_27,
        :ussr_82_bm_37,
        :ussr_pm_m1910,
      ] },
      "3": { list: [
        :ussr_leader_4_1,
        :ussr_rifle_s,
        :ussr_smg_s,
        :ussr_dp_27,
        :ussr_ba_20,
        :ussr_kv_1_m39,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :fin_leader_5_1,
        :fin_leader_4_1,
        [5, :fin_regular_s],
        :fin_ls_26,
        :fin_maxim_m_32_33,
        :fin_81mm_tampella,
        :fin_14mm_pst_kiv_37,
        [2, :trench],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Loimola, Finland",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "After a string of defeats at the beginning of the Winter War, the
          Finns entrenched themselves west of the Kollaa River. The Soviet
          attack in this sector was largely unexpected, and threatened to
          allow the Soviets to outflank the Finnish line of defense north of
          Lake Ladoga, bypassing the Mannerheim Line. Therefore, large
          portions of the Finnish Fourth Corps were deverted to this position.
          Despite still having far fewer troops than the Soviets, the Finnish
          forces repelled the Red Army attack due to the Soviets lack of
          ability to proceed cross-country without skis and being forced to
          proceed along roads, of which there were few in the Kollaa area.",
          "The attacks shifted back and forth as the Finns counterattacked and
          the Soviets committed more forces to the attack and failed to break
          the Finnish lines. One hill, called \"Killer Hill\" by the Finns, saw
          the Soviets advance an entire regiment against a force of 32
          fortified Finns who held and inflicted massive casualties on the
          Soviets in the process.  A famous quote from the Battle is Major
          General Hägglund's question, \"Will Kollaa hold? (Kestääkö Kollaa?)\",
          to which Lieutenant Aarne Juutilainen replied, \"Kollaa will hold
          (Kollaa kestää), unless the orders are to run away.\" The simple
          question and reply became part of the Finnish lexicon as an expression
          of resolve in the face of difficulty.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [1, "snow"],
          wind: [2, 5, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [6, 7, 2], [3, 8, 2], [6, 13, 2], [8, 10, 2], [10, 7, 2],
          ],
          allied_setup: {
            "0" => [
              ["12-14", "0-11"], ["13-14", 12], ["12-14", "13-15"], ["13-14", 16], ["12-14", 17],
              ["13-14", "18-19"],
            ],
            "3" => [[14, "0-19"]],
          },
          axis_setup: {
            "0" => [
              ["0-6", "0-1"], ["0-7", "2-5"], ["0-10", "6-8"], ["0-8", 9], ["0-9", 10],
              ["0-8", "11-13"], ["0-9", "14-15"], ["0-10", "16-17"], ["0-11", "18-19"],
              ["0-12", 20], ["*", "21-22"],
            ],
          },
          base_terrain: "s",
        }
      end

      def hexes
        [
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "w" },
            { t: "o" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "w" },
            { t: "o" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "f" },
            { t: "w" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "w", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] }, s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "w", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "w", s: { t: "s", d: [1, 2] } },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "w" },
            { t: "f" },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
          ],
          [
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "w", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
        ]
      end
    end
  end
end
