# frozen_string_literal: true

module Scenarios
  class Scenario417 < Base
    ID = "417"
    NAME = "Alligator Creek"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 8, 21].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_6_1,
        :usa_leader_5_1,
        :usa_leader_4_1,
        [7, :usa_marine_rifle_s],
        :usa_m1919_browning,
        :usa_m1917_browning,
        [2, :usa_m1918_bar],
        [4, :wire],
        [3, :trench],
      ] },
      "3": { list: [
        :usa_leader_5_1,
        [3, :usa_marine_rifle_s],
        [2, :usa_m1918_bar],
        :usa_radio_75mm,
        :usa_m3_stuart,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_1,
        :jap_leader_4_1,
        [12, :jap_a_division_s],
        [3, :jap_type_96_lmg],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Ilu River, Guadalcanal",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["axis_bonzai"],
        }
      end

      def description
        [
          "The Battle of the Tenaru (also referred to as the Battle of the Ilu
          River or Alligator Creek) was a battle between the Imperial Japanese
          Army and U.S. Marines on the island of Guadalcanal.  In the battle,
          the Marines repulsed a full assault by a Japanese regiment under the
          command of Japanese Colonel Kiyonao Ichiki. The Marines were
          defending the Lunga perimeter after capturing Henderson Field in
          amphibious landings two weeks before. Ichigi's regiment was sent to
          Guadalcanal in reponse to the landings in order to recapture the
          airfield and drive the Americans off the island.",
          "Underestimating the strength of Allied forces on Guadalcanal, which
          at the time numbered about 11,000, Ichiki's 900-man unit conducted a
          nighttime frontal assault on Marine positions at Alligator Creek on
          the east side of the Lunga perimeter. A Coastwatcher scout warned
          the Americans of the impending attack minutes before Ichiki's
          assault and the Japanese were defeated with heavy losses. The
          Marines counterattacked Ichiki's surviving troops the next day,
          killing many more. About 800 of the original 917 of the Ichiki
          formation died, and (depending on the account) Ichiki was either
          killed in the battle or committed seppuku immediately thereafter.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 1, false],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [4, 5, 1], [4, 16, 1], [12, 20, 1], [6, 9, 1], [8, 12, 1], [4, 8, 1], [7, 14, 1],
          ],
          allied_setup: {
            "0" => [
              ["0-5", "0-7"], ["0-6", "8-9"], ["0-7", "10-11"], ["0-8", "12-13"], ["0-10", "14-15"],
              ["0-12", "16-17"], ["0-13", "18-19"], ["*", "20-22"],
            ],
            "3" => [[0, "*"]],
          },
          axis_setup: {
            "0" => [
              ["7-14", "0-3"], ["8-14", 4], ["7-14", 5], ["8-14", "6-9"], ["9-14", "10-11"],
              ["10-14", 12], ["11-14", 13], ["12-14", 14], ["13-14", 15], [14, "16-17"],
            ],
          },
          base_terrain: "",
          night: true,
        }
      end

      def hexes
        [
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "j" },
            { t: "o", r: { t: "p", d: [4, 6] } },
            { t: "j", r: { t: "p", d: [1, 4] } },
            { t: "j", r: { t: "p", d: [1, 4] } },
            { t: "o", r: { t: "p", d: [1, 5] } },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "p", d: [1, 3] } },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [2, 6] } },
            { t: "o" },
            { t: "y" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "p", d: [3, 5] } },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [2, 6] } },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [3, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
          ],
          [
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
          ],
          [
            { t: "p" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "p", d: [2, 4] } },
            { t: "o", r: { t: "p", d: [1, 5] } },
            { t: "o" },
            { t: "y" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "p" },
          ],
          [
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [2, 5, 6] } },
            { t: "j" },
            { t: "y" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "p", d: [3, 5] } },
            { t: "j", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "p", d: [2, 6] } },
            { t: "j", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "p", d: [3, 6] } },
            { t: "p" },
            { t: "j", r: { t: "p", d: [2, 4] } },
            { t: "j", r: { t: "p", d: [1, 5] } },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [4, 6] } },
            { t: "o", r: { t: "p", d: [1, 4] } },
            { t: "o", r: { t: "p", d: [1, 4] } },
            { t: "o", r: { t: "p", d: [1, 3] } },
            { t: "p" },
            { t: "p" },
            { t: "j" },
            { t: "j", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o", r: { t: "p", d: [3, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "j" },
            { t: "j", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o", r: { t: "p", d: [3, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "y" },
          ],
          [
            { t: "o", r: { t: "p", d: [1, 4] } },
            { t: "o", r: { t: "p", d: [1, 3] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "y" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [2, 6] } },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "p", d: [3, 6] } },
            { t: "o" },
            { t: "j" },
          ],
        ]
      end
    end
  end
end
