# frozen_string_literal: true

module Scenarios
  class Scenario019 < Base
    ID = "019"
    NAME = "Out of the Woods"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 5, 1].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_6_1,
        [2, :ussr_leader_4_1],
        [3, :ussr_rifle_s],
        [2, :ussr_sg_43],
        [2, :ussr_t_34_85_m44],
        [2, :ussr_smg_s],
        :ussr_radio_152mm,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_5_1,
        :ger_leader_4_1,
        [8, :ger_rifle_s],
        [2, :ger_mg_42],
        [2, :ger_pzkpfw_iv_h_j],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Halbe, Germany",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "During the Battle of Halbe, the German Ninth Army was encircled in
          a large pocket in the Spree Forest south-east of Berlin, and
          attempted to break out westwards through the the pine forests and
          the village of Halbe to link up with the German Twelfth Army, with
          the intention of heading west and surrendering to the Western
          Allies.  To do this, the Ninth Army had to fight its way through
          three lines of Soviet troops, while at the same time other units of
          the Soviets attacked the German rearguard from the northeast.",
          "After heavy fighting, about 30,000 German soldiers — just over one
          third of those originally in the pocket — reached the comparative
          safety of the Twelfth Army's front lines. The rest were either
          killed or captured by Soviet forces and the Ninth Army ceased to
          exist as a fighting force.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 4, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [3, 15, 1], [3, 18, 1], [7, 18, 1], [3, 10, 1], [4, 13, 1], [8, 1, 2], [11, 13, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-1", 8], ["0-1", 9], ["0-3", 10], ["0-3", 11], ["0-4", 12], ["0-4", 13],
              ["0-5", 14], ["0-5", 15], ["0-6", 16], ["0-6", 17], ["0-7", 18], ["0-7", 19],
              ["0-8", 20], ["0-8", 21], ["0-8", 22],
            ],
          },
          axis_setup: {
            "0" => [
              ["2-14", 7], ["3-14", 8], ["4-14", 9], ["5-14", 10], ["5-14", 11], ["6-14", 12],
              ["6-14", 13], ["7-14", 14], ["7-14", 15], ["8-14", 16], ["8-14", 17], ["9-14", 18],
              ["9-14", 19], ["10-14", 20], ["10-14", 21], ["10-14", 22], ["*", "0-6"],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "f", r: { t: "t", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", st: { sh: "l", s: "f" }, d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "f", r: { t: "t", d: [1, 3] } },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 3, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "f", r: { t: "t", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] }, s: { t: "s", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", st: { sh: "s", s: "f" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3, s: { t: "s", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "f" }, d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "f" }, d: 3 },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "f" }, d: 5 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o", st: { sh: "s", s: "f" }, d: 6 },
            { t: "w", s: { t: "s", d: [3, 5] } },
            { t: "w" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
        ]
      end
    end
  end
end
