# frozen_string_literal: true

module Scenarios
  class Scenario410 < Base
    ID = "410"
    NAME = "Steel Bonzai"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"

    DATE = [1944, 6, 16].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": {
        list: [
          :usa_leader_5_1,
          [6, :usa_marine_rifle_s],
          :usa_crew_t,
          :usa_m2_browning,
          [2, :usa_m1a1_bazooka],
          :usa_37mm_m3,
          [3, :usa_m4_sherman],
          :usa_m8_scott,
        ],
      },
    }.freeze

    AXIS_UNITS = {
      "0": {
        list: [
          :jap_leader_4_1,
          [5, :jap_b_division_s],
          :jap_type_99_lmg,
          [4, :jap_type_97_chi_ha],
          [4, :jap_type_95_ha_go],
        ],
      },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Saipan, Mariana Islands",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "Following the U.S. landings on Saipan, the Japanese launched an
          immediate counteroffensive in an attempt to throw the American
          beachhead back into the sea.  On the second night, they attempted a
          coordinated tank-infantry attack using the bulk of his armored
          force.  The assault targeted the lines held by the 6th and 8th Marine
          Regiments of the 2nd Marine Division.",

          "However, the Americans had prepared for such a response. Armed with
          bazookas, anti-tank guns, and artillery, the Marines met the attack
          head-on. In a chaotic and violent night battle, virtually all of the
          Japanese tanks were destroyed, many in fiery explosions under direct
          hits. The supporting infantry suffered severe casualties as they
          were mowed down by automatic weapons and artillery fire. By dawn on
          June 17, the counterattack had completely failed, with over 700
          Japanese soldiers killed and the armored force effectively wiped
          out.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [0, 1, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [12, 2, 2], [3, 5, 1], [12, 7, 1], [10, 9, 1], [2, 15, 1], [4, 19, 1], [11, 20, 1],
          ],
          allied_setup: { "0" => [["*", "9-22"]] },
          axis_setup: { "0" => [["*", "0-4"]] },
          base_terrain: "g",
          night: true,
        }
      end

      def hexes
        [
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { d: [3, 5] } },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 5] } },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [2, 4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { d: [2, 6] } },
            { t: "o" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", d: 3, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { d: [3, 6] } },
            { t: "p" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { d: [2, 4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 3, 5] } },
            { t: "p" },
            { t: "j" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { d: [3, 5] } },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { d: [2, 6] } },
            { t: "j" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", d: 1, st: { sh: "h", s: "f" } },
            { t: "p" },
            { t: "o", r: { d: [3, 5] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [2, 6] } },
            { t: "j" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { d: [3, 5] } },
            { t: "j" },
            { t: "j" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "j" },
          ], [
            { t: "w" },
            { t: "o", r: { d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { d: [2, 5] } },
            { t: "j" },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { d: [2, 6] } },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [2, 5, 6] } },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { d: [3, 6] } },
            { t: "j", h: 1 },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "j", h: 1 },
          ], [
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
          ], [
            { t: "w" },
            { t: "o", r: { d: [3, 5] } },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
          ], [
            { t: "w" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
          ], [
            { t: "w" },
            { t: "w" },
            { t: "o", r: { d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
          ], [
            { t: "w" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", d: 3, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { d: [2, 6] } },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", d: 3, st: { sh: "h", s: "f" } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
          ], [
            { t: "w" },
            { t: "o", r: { d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j", h: 1 },
          ],
        ]
      end
    end
  end
end
