# frozen_string_literal: true

module Scenarios
  class Scenario412 < Base
    ID = "412"
    NAME = "Langoan Field"
    ALLIES = ["dut"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 1, 11].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [1, :alm_leader_3_1],
        [3, :alm_conscript_s],
        [1, :alm_12_7mm_hmg],
        [1, :alm_overvalwagen],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [1, :jap_leader_5_2],
        [2, :jap_leader_5_1],
        [6, :jap_snlf_s],
        [2, :jap_type_99_lmg],
        [2, :jap_type_89_gren_l],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Langoan, Manado, Dutch East Indies",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "Langoan Airfield was a strategic airbase located on the Manado
          Peninsula of Celebes Island.  Built prewar by the Dutch, it was a
          key objective in Japan’s Eastern Offensive to capture the Dutch East
          Indies.",
          "The airfield was one of the main sites of the Battle of Manado, and
          was the first combat parachute drop ever performed by the Japanese.
          The 1st Yokosuka Special Naval Landing Force (SNLF) dropped 334
          paratroopers from the Philippines to seize the airfield, which was
          defended by Dutch forces under Captain W. C. van den Berg and 1st
          Lieutenant J. G. Wielinga. Despite heavy casualties, the Japanese
          captured the airfield.",
          "Many of the Dutch prisoners were subsequently executed by the
          Japanese, and the airfield was used by Japanese aircraft until the
          end of the Pacific War.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 6, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [6, 20, 1], [3, 19, 1], [6, 11, 1], [5, 15, 1], [4, 16, 1],
          ],
          allied_setup: { "0" => [["*", "10-22"]] },
          axis_setup: { "0" => [["*", "0-4"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "m", s: { t: "s", d: [3, 6] } },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "m", s: { t: "s", d: [3, 6] } },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "m", s: { t: "s", d: [4, 6] } },
            { t: "m", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "m", s: { t: "s", d: [1, 4] } },
            { t: "m", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "j" },
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "y" },
            { t: "d", d: 3 },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
          ],
          [
            { t: "t" },
            { t: "p" },
            { t: "o" },
            { t: "y" },
            { t: "d", d: 3 },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
          ],
          [
            { t: "t" },
            { t: "t" },
            { t: "y" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
          ],
          [
            { t: "t" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "d", d: 3 },
            { t: "o" },
          ],
          [
            { t: "t" },
            { t: "y" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "o" },
            { t: "p" },
            { t: "t" },
            { t: "d", d: 3 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "p" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "a", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
          ],
        ]
      end
    end
  end
end
