# frozen_string_literal: true

module Scenarios
  class Scenario608 < Base
    ID = "608"
    NAME = "Marco Polo Bridge"
    ALLIES = ["chi"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1937, 7, 8].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :chi_leader_4_1],
        [8, :chi_conscript_s],
        [2, :chi_type_24_maxim],
        [1, :chi_type_triple_ten],
      ] },
      "2": { list: [
        [1, :chi_leader_4_1],
        [3, :chi_conscript_s],
        [1, :chi_czeck_lmg],
      ] },
      "4": { list: [
        [3, :chi_conscript_s],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [1, :jap_leader_5_1],
        [2, :jap_leader_4_1],
        [8, :jap_b_division_s],
        [2, :jap_type_89_gren_l],
        [3, :jap_type_96_lmg],
      ] },
      "3": { list: [
        [1, :jap_leader_5_1],
        [4, :jap_a_division_s],
        [1, :jap_crew_t],
        [1, :jap_70mm_type_92],
        [1, :jap_type_92_hmg],
      ] },
    }.freeze

    INIT_ALLIED_UNITS = [
      { data: :pillbox, x: 5, y: 6, facing: 4 },
      { data: :pillbox, x: 5, y: 3, facing: 4 },
      { data: :pillbox, x: 5, y: 8, facing: 4 },
      { data: :pillbox, x: 5, y: 11, facing: 4 },
    ].freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Fengtai, Beijing, China",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          init_allied_units:,
        }
      end

      def description
        [
          "Tensions between the Empire of Japan and the Republic of China had
          been high since the Japanese invasion of Manchuria in 1931 and the
          subsequent creation of the puppet state of Manchukuo, and as the
          Japanese extended their control further into northern China after
          the invasion, tensions got higher still.",
          "By the terms of the Boxer Protocol, China had granted nations with
          legations in Beijing the right to station guards at twelve specific
          points along railways connecting Beijing with Tianjin. These forces
          were also allowed to conduct maneuvers without informing the
          authorities of other nations in China.  By July 1937, Japan had
          expanded its forces in China to an estimated 7,000 to 15,000 men,
          mostly along the railways. This number of men was several times the
          size of the detachments deployed by the European powers, and greatly
          in excess of the limits set by the Boxer Protocol.",
          "On the night of 7 July, the Japanese units stationed at Fengtai
          crossed the border to conduct military exercises.  Japanese and
          Chinese forces outside the town Wangping exchanged fire that night.
          The exact cause of this incident remains unknown, but when a
          Japanese soldier failed to return to his post, the Japanese sent a
          message to the Chinese demanding permission to enter Wanping to
          search for the missing soldier; the Chinese refused. It turned out
          that the Japanese soldier had merely lost his way and was quickly
          found, but the Japanese demands changed to a damand that the Chinese
          give up the soldiers who had fired the initial shots.",
          "Reinforcements soon arrived, fighting broke out, and although a
          rough cease-fire soon took hold in Beijing, fighting ultimately resumed
          and the Second Sino-Japanese War had begun.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 5, true],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [5, 8, 1], [5, 6, 1], [3, 16, 1], [11, 14, 1], [19, 8, 2], [7, 16, 1], [13, 16, 1],
          ],
          allied_setup: {
            "0" => [
              ["0-11", 0], ["0-11", 1], ["0-11", 2], ["0-11", 3], ["0-11", 4], ["0-11", 5],
              ["0-11", 6], ["0-11", 7], ["0-11", 8], ["0-11", 9], ["0-11", 10], ["0-11", 11],
              ["0-16", 12], ["0-16", 13], ["0-16", 14], ["0-16", 15], ["0-16", 16], ["0-16", 17],
              ["0-16", 18], ["0-16", 19], ["0-16", 20], ["0-16", 21], ["0-16", 22],
            ],
            "2" => [
              ["0-3", 0], ["0-3", 1], ["0-3", 2], ["0-3", 3], ["0-3", 4], ["0-3", 5], ["0-3", 6],
              ["0-3", 7], ["0-3", 8], ["0-3", 9], ["0-3", 10], ["0-3", 11], ["0-3", 12],
              ["0-3", 13], ["0-3", 14], ["0-3", 15], ["0-6", 16], ["0-6", 17], ["0-6", 18],
              ["0-6", 19], ["0-6", 20], ["0-6", 21], ["0-6", 22],
            ],
            "4" => [["0-3", "*"]],
          },
          axis_setup: {
            "0" => [
              ["13-22", 0], ["13-22", 1], ["13-22", 2], ["13-22", 3], ["13-22", 4], ["13-22", 5],
              ["13-22", 6], ["13-22", 7], ["13-22", 8], ["13-22", 9], ["13-22", 10], ["18-22", 11],
              ["18-22", 12], ["18-22", 13], ["18-22", 14], ["18-22", 15], ["18-22", 16],
              ["18-22", 17], ["18-22", 18], ["18-22", 19], ["18-22", 20], ["18-22", 21],
              ["18-22", 22],
            ],
            "3" => [[22, "*"]],
          },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", d: 1, st: { sh: "s2", s: "f" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ],
          [
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "w", rr: { d: [[1, 4]] } },
            { t: "w", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] }, r: { t: "t", d: [3, 5] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] }, r: { t: "t", d: [2, 5] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4], [1, 5]] } },
            { t: "o", rr: { d: [[1, 4]] } },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", rr: { d: [[2, 5]] }, r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "s2", s: "f" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 5 },
            { t: "f" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", b: "w", be: [1, 2, 3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [2, 3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [2, 3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [2, 3], r: { t: "t", d: [4, 6], c: "l" } },
            { t: "o", b: "w", be: [2], r: { t: "t", d: [1, 3, 4], c: "r" } },
            { t: "o", b: "w", be: [3], r: { t: "t", d: [1, 4] } },
            { t: "o", b: "w", be: [2, 3], r: { t: "t", d: [1, 6], c: "l" } },
            { t: "o", b: "w", be: [2, 3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [2, 3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [2, 3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [1] },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", b: "w", be: [3], r: { t: "t", d: [2, 6] } },
            { t: "o", b: "w", be: [1], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "bc4", s: "f" }, d: 1 },
            { t: "o", st: { sh: "bc2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [1] },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 5 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", b: "w", be: [1, 2], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bc2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "bc4", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 4] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", b: "w", be: [3], r: { t: "t", d: [2, 6] } },
            { t: "o", b: "w", be: [1], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [1] },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ],
          [
            { t: "w", r: { t: "t", d: [1, 4] } },
            { t: "w", r: { t: "t", d: [1, 4] } },
            { t: "w", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "w", be: [2] },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "w", be: [2] },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", b: "w", be: [3] },
            { t: "o", b: "w", be: [1], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "f", b: "w", be: [1] },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", b: "w", be: [1, 2], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "f", b: "w", be: [1, 2] },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", b: "w", be: [3] },
            { t: "o", b: "w", be: [1], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", b: "w", be: [3], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "f", b: "w", be: [1] },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 2 },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", b: "w", be: [1, 2], st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "f", b: "w", be: [1, 2] },
            { t: "o" },
            { t: "f" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "m2", s: "u" }, d: 2 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "f", b: "w", be: [3] },
            { t: "f", b: "w", be: [2, 3] },
            { t: "f", b: "w", be: [2, 3] },
            { t: "f", b: "w", be: [2, 3] },
            { t: "f", b: "w", be: [2, 3] },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "f", b: "w", be: [2, 3] },
            { t: "f", b: "w", be: [2, 3] },
            { t: "f", b: "w", be: [2, 3] },
            { t: "f", b: "w", be: [2, 3] },
            { t: "f", b: "w", be: [2] },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 5 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
          ],
        ]
      end
    end
  end
end
