# frozen_string_literal: true

module Scenarios
  class Scenario418 < Base
    ID = "418"
    NAME = "Battle of the Ridges"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 12, 5].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_5_1,
        [2, :usa_leader_4_1],
        [6, :usa_rifle_s],
        [3, :usa_m1918_bar],
        [2, :usa_lvta_2],
        [4, :usa_lvta_4],
        :usa_ft,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :jap_leader_5_1],
        [6, :jap_a_division_s],
        [2, :jap_type_99_lmg],
        :jap_type_97_81mm,
        :jap_type_92_hmg,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Balugo, Philippines",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "When they started to advance towards Ormoc on the west coast of
          Lyte Island in the Philippines, they tried out a novel tactic: they
          sent out amtanks from the 776th Amphibian Tank Battalion to sea and
          leapfrogged the Japanese troops, positioning themself west of of
          Bolugo.  Moving within 200 yards of shore, they fired into the hills
          in front of the advancing American infantry. The tactic proved
          effective, greatly disorganizing the defenders, except where the
          ground troops encountered enemy pockets on reverse slopes inland
          where they were shielded from the offshore tank fire.",
          "The Americans pushed north with two regiments which encountered
          heavy enemy fire coming from Hill 918, from which the entire coast
          to Ormoc City could be observed. Two days after the start of the
          advance, the American forces had taken Hills 918, 380 and 606, plus
          the surrounding ridges. And by five days later, the lead battalion
          of the Americans was less than 10 miles south of Ormoc City.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [4, 3, true],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [3, 8, 2], [3, 4, 2], [5, 14, 2], [6, 10, 2], [6, 5, 2],
          ],
          allied_setup: { "0" => [["11-14", 18], ["10-14", 19], ["*", "20-22"]] },
          axis_setup: {
            "0" => [["0-11", "13-14"], ["0-10", "15-16"], ["0-4", 17], ["8-9", 17], ["*", "0-12"]],
          },
        }
      end

      def hexes
        [
          [
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p" },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 3] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 2 },
          ],
          [
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p" },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "y", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] }, r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p" },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] }, r: { t: "d", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "p" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "p" },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 3 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "p" },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 3] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1, s: { t: "s", d: [4, 6] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p", h: 1 },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] }, r: { t: "d", d: [2, 5] } },
            { t: "p", h: 1 },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "p" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] }, r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y", s: { t: "s", d: [3, 6] } },
            { t: "p" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 3 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "p", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
          ],
        ]
      end
    end
  end
end
