# frozen_string_literal: true

module Scenarios
  class Scenario204 < Base
    ID = "204"
    NAME = "The Slogging Grounds"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"

    DATE = [1944, 1, 24].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": {
        list: [
          :usa_leader_5_1,
          [2, :usa_leader_4_1],
          [12, :usa_rifle_s],
          [4, :usa_m1918_bar],
          :usa_m1_mortar,
          :usa_radio_155mm,
          [2, :usa_t12_gmc],
          [4, :usa_m4_sherman],
        ],
      },
    }.freeze

    AXIS_UNITS = {
      "0": {
        list: [
          :ger_leader_5_1,
          :ger_leader_4_1,
          [6, :ger_rifle_s],
          [4, :ger_crew_t],
          [3, :ger_mg_42],
          [2, :ger_7_5cm_leig_18],
          [2, :ger_7_5cm_pak_40],
          [4, :bunker],
        ],
      },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Cassino, Italy",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Monte Cassino, also known as the Battle for Rome, was
          a series of four military assaults by the Allies against German
          forces in Italy during the Italian Campaign of World War II. The
          objective was to break through the Winter Line and facilitate an
          advance towards Rome.",

          "At the end of January, 1944, the U.S. II Corps, with 34th Infantry
          Division spearheading the attack and French colonial troops on its
          right flank, launched an assault across the flooded Rapido valley
          north of Cassino and into the mountains behind with the intention of
          then wheeling to the left and attacking Monte Cassino from high
          ground.  While the task of crossing the river would be easier in
          that the Rapido upstream of Cassino was fordable, the flooding made
          movement on the approaches each side very difficult. In particular,
          armour could only move on paths laid with steel matting and it took
          eight days of bloody fighting across the waterlogged ground for 34th
          Division to push back the German 44th Infantry Division to establish
          a foothold in the mountains.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [0, 1, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [2, 8, 2], [3, 6, 2], [5, 12, 2], [5, 20, 2], [10, 12, 2], [11, 16, 2], [14, 9, 2],
          ],
          allied_setup: { "0" => [["16-22", "*"]] },
          axis_setup: { "0" => [["0-6", "*"]] },
          base_terrain: "m",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "y" },
            { t: "o" },
          ], [
            { t: "o", h: 1, r: { d: [1, 4], t: "d" } },
            { t: "o", h: 1, r: { d: [1, 6], t: "d" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "d", d: 3 },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "y", r: { d: [3, 6], t: "d" } },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [3, 5], t: "d" } },
            { t: "o", d: 2.5, st: { sh: "l2", s: "f" } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o", d: 3, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o", d: 3, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o", r: { d: [3, 4, 6], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o", d: 3, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "o", d: 3, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
          ], [
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 4], t: "d" } },
            { t: "y", r: { d: [1, 4], t: "d" } },
            { t: "m", r: { d: [1, 4], t: "d" } },
            { t: "m", r: { d: [1, 4], t: "d" } },
            { t: "o", r: { d: [1, 3, 6], t: "d" } },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
          ], [
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m", r: { d: [3, 6], t: "d" } },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m", r: { d: [3, 6], t: "d" } },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "m", r: { d: [3, 6], t: "d" } },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "y", r: { d: [3, 6], t: "d" } },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "t" },
            { t: "t" },
            { t: "o", r: { d: [3, 6], t: "d" } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "y" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
