# frozen_string_literal: true

module Scenarios
  class Scenario315 < Base
    ID = "315"
    NAME = "Drop Zone O"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 6, 6].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :usa_leader_6_1],
        [2, :usa_leader_5_1],
        [8, :usa_paratroop_s],
        [2, :usa_m1918_bar],
      ] },
      "2": { list: [
        :usa_leader_6_1,
        :usa_leader_5_1,
        [4, :usa_paratroop_s],
        :usa_m1918_bar,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_4_1,
        [5, :ger_volksgrenadier_s],
        [2, :ger_mg_42],
      ] },
      "5": { list: [
        :ger_leader_4_1,
        [5, :ger_volksgrenadier_s],
        [2, :ger_mg_42],
        :ger_hetzer,
        :ger_marder_iii,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Chef-du-Pont, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["allied_random_drop_0", "allied_random_drop_2"],
        }
      end

      def description
        [
          "Early on the morning of D-Day, American paratroopers landed in
          Normandy in two waves, followed by gliders. The first wave consisted
          of the 101st airborne and was scattered all over, sometimes miles
          from their landing zones, due to various difficulties caused by
          weather and other factors. The second wave consisted of the 82nd
          airborne who were less scattered as conditions improved, though only
          the 505th Parachute Infantry Regiment managed to (mostly) accurately
          land in its intended drop zone.",
          "Timely assembly allowed the 505th to accomplish two of its missions
          on schedule; with the help of a Frenchman who led them into the
          town, they captured Sainte-Mère-Église by against almost no
          resistance, and established a blocking position on the northern
          approaches to the town, as well as fending off the first
          counter-attacks. However, they failed to capture the bridges over
          the Merderet at la Fière and Chef-du-Pont despite the assistance of
          several hundred troops from the 507th and 508th PIRs.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 3, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [11, 11, 2], [18, 1, 2], [18, 5, 2], [6, 20, 2], [14, 11, 2], [9, 14, 2], [4, 3, 2],
            [4, 17, 2], [3, 5, 2],
          ],
          allied_setup: { "0" => [["1-21", "1-21"]], "2" => [["1-21", "1-21"]] },
          axis_setup: { "0" => [["*", "*"]], "5" => [[0, "*"]] },
          base_terrain: "",
          night: true,
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [1] },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "m", s: { t: "s", d: [3, 6] } },
            { t: "m" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "m", s: { t: "s", d: [3, 6] } },
            { t: "m" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "m" },
            { t: "m", s: { t: "s", d: [3, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "g" },
            { t: "m" },
            { t: "m", s: { t: "s", d: [2, 4] } },
            { t: "m", s: { t: "s", d: [1, 5] } },
            { t: "m" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "b", be: [3] },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "b", be: [2, 3] },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "b", be: [2, 3] },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "b", be: [2] },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] }, b: "b", be: [1] },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "g" },
            { t: "m" },
            { t: "m" },
            { t: "m", s: { t: "s", d: [2, 5] } },
            { t: "m" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2] },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "g" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "m", r: { t: "t", d: [1, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "g" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "o" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
            { t: "o" },
            { t: "m" },
            { t: "m", s: { t: "s", d: [2, 5] } },
            { t: "g" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
            { t: "o" },
            { t: "m" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "g" },
            { t: "o", b: "b", be: [3] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "g" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] }, s: { t: "s", d: [3, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", b: "b", be: [3] },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "g" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g", b: "b", be: [3] },
            { t: "o", s: { t: "s", d: [3, 5] }, b: "b", be: [1] },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [3] },
            { t: "o" },
            { t: "g" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [1] },
            { t: "m", s: { t: "s", d: [3, 6] } },
            { t: "m" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [1] },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "m", s: { t: "s", d: [3, 6] } },
            { t: "m" },
            { t: "m" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] }, h: 1 },
            { t: "f", h: 1, r: { t: "t", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "m", s: { t: "s", d: [3, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "g" },
          ],
          [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", r: { t: "t", d: [2, 5] }, h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "m", s: { t: "s", d: [2, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "b", be: [3] },
            { t: "o", b: "b", be: [2, 3] },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", r: { t: "t", d: [2, 6] }, h: 2 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "m", s: { t: "s", d: [2, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "o", h: 2, st: { sh: "l", s: "f" }, d: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "m", s: { t: "s", d: [2, 6] } },
            { t: "m" },
            { t: "m" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
          ],
        ]
      end
    end
  end
end
