# frozen_string_literal: true

module Scenarios
  class Scenario043 < Base
    ID = "043"
    NAME = "Out of the Frying Pan"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1941, 8, 5].freeze
    LAYOUT = [32, 11, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [5, :ussr_rifle_s],
        [2, :ussr_smg_s],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_4_1,
        [3, :ger_rifle_s],
        [2, :ger_mg_34],
      ] },
      "2": { list: [
        [2, :ger_leader_5_1],
        [6, :ger_rifle_s],
        [4, :ger_mg_34],
        [2, :ger_pzkpfw_i],
        [2, :ger_sdkfz_221],
        [2, :ger_sdkfz_250_1],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Yartsevo, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["allied_escape"],
        }
      end

      def description
        [
          "During the first Battle of Smolensk during Operation Barbarossa,
          the Axis managed to encircle and destroy the Soviet 16th, 19th, and
          20th armies, but due to stiffening Soviet resistance,
          counterattacks, and difficult terrain in places, the encirclement
          was not complete until several weeks after the inital attacks.  Even
          after the final gap was closed, with determined effort, some Soviet
          troops of the 20th Army managed to break out of the pocket a few
          days later.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 5, false],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [9, 6, 1], [17, 8, 2], [23, 5, 2],
          ],
          escape_hexes: [
            [31, 3, 1], [31, 4, 1], [31, 5, 1], [31, 6, 1],
          ],
          allied_setup: {
            "0" => [
              ["5-6", 3], ["6-7", "4-5"], [8, 6],
            ],
          },
          axis_setup: {
            "0" => [
              ["25-31", "*"],
            ],
            "2" => [
              ["0-2", "0-4"],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4, 5] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 4] } },
            { t: "o", s: { t: "s", d: [1, 6] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [2, 6] }, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
          ],
          [
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
          ],
        ]
      end
    end
  end
end
