# frozen_string_literal: true

module Scenarios
  class Scenario317 < Base
    ID = "317"
    NAME = "The Guns of Pointe du Hoc"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 6, 6].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :usa_leader_6_2],
        [8, :usa_ranger_s],
        [2, :usa_m1918_bar],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [4, :ger_volksgrenadier_s],
        [4, :ger_mg_42],
      ] },
    }.freeze

    INIT_AXIS_UNITS = [
      { data: :bunker, x: 9, y: 6, facing: 3 },
      { data: :bunker, x: 12, y: 10, facing: 3 },
      { data: :bunker, x: 15, y: 17, facing: 3 },
      { data: :bunker, x: 14, y: 14, facing: 3 },
      { data: :bunker, x: 7, y: 17, facing: 2 },
      { data: :bunker, x: 9, y: 10, facing: 2 },
      { data: :bunker, x: 20, y: 16, facing: 3 },
      { data: :bunker, x: 0, y: 17, facing: 2 },
      { data: :ger_crew_t, x: 0, y: 17, facing: 1 },
      { data: :ger_crew_t, x: 20, y: 16, facing: 1 },
      { data: :ger_crew_t, x: 14, y: 14, facing: 1 },
      { data: :ger_crew_t, x: 12, y: 10, facing: 1 },
      { data: :ger_crew_t, x: 9, y: 10, facing: 1 },
      { data: :ger_crew_t, x: 9, y: 6, facing: 1 },
      { data: :ger_gpf_155mm_k418, x: 9, y: 10, facing: 2 },
      { data: :ger_gpf_155mm_k418, x: 0, y: 17, facing: 2 },
      { data: :ger_gpf_155mm_k418, x: 9, y: 6, facing: 3 },
      { data: :ger_gpf_155mm_k418, x: 12, y: 10, facing: 3 },
      { data: :ger_gpf_155mm_k418, x: 14, y: 14, facing: 3 },
      { data: :ger_gpf_155mm_k418, x: 20, y: 16, facing: 3 },
    ].freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Pointe du Hoc, Normandy, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          init_axis_units:,
        }
      end

      def description
        [
          "Pointe du Hoc was a prominent clifftop location west of the center
          of Omaha Beach that was fortified by the Germans before D-Day. The
          battery housed six captured French WWI vintage 155mm guns, and
          additional infantry were stationed at the battery to defend it from
          attack.",
          "By the time the Rangers made it to the beach, about half of the
          force had not arrived for various reasons, including a significant
          number of casualties from German fire before they reached shore. The
          Rangers sustained an additional 15 casualties after landing before
          successfully scaling the cliffs. Additionally, because the attack
          had been delayed by about 40 minutes, the larger Ranger force of
          eight companies meant as reinforcements had been redirected to Omaha
          Beach instead. Upon reaching the fortifications, the Rangers
          discovered that their main objective, the artillery battery, had
          been removed. The Rangers regrouped at the top of the cliffs, and a
          small patrol went off in search of the guns which were found nearby
          nearby (including one being repaired), and destroyed their firing
          mechanisms with thermite grenades.",
          "In this hypothetical scenario, the guns are still emplaced and
          functioning, posing a significant danger to the attacking Rangers.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [4, 6, true],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [0, 17, 2], [7, 17, 2], [9, 10, 2], [9, 6, 2], [12, 10, 2], [14, 14, 2], [15, 17, 2],
            [20, 16, 2], [9, 13, 2],
          ],
          allied_setup: {
            "0" => [
              ["*", "0-2"], ["0-7", "3-6"], ["0-6", "7-8"], ["0-4", "9-10"], ["0-2", "11-12"],
              ["0-1", "13-14"], ["9-22", 3], ["10-22", 4], ["9-22", 5], ["10-22", "6-7"],
              ["12-22", 8], ["13-22", 9], ["15-22", 10], ["16-22", 11], ["19-22", 12],
              ["21-22", 13],
            ],
          },
          axis_setup: {
            "0" => [
              [8, 3], ["8-9", 4], [8, 5], ["8-9", 6], ["7-9", 7], ["7-11", 8], ["5-12", 9],
              ["5-14", 10], ["3-15", 11], ["3-18", 12], ["2-20", 13], ["2-22", 14], ["*", "15-22"],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "s", b: "c", be: [1] },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2, 3, 4] },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2, 6] },
            { t: "o", h: 1, b: "c", be: [3, 4, 5] },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 4] },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2] },
            { t: "o", h: 1, b: "c", be: [3, 4] },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "b", h: 1, b: "c", be: [1, 2] },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1, b: "c", be: [3, 4], s: { t: "t", d: [2, 5] } },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "b", h: 1, b: "c", be: [1, 2] },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, b: "c", be: [3], s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1, b: "c", be: [2, 3, 4] },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2, 3] },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, s: { t: "t", d: [2, 4, 5] } },
            { t: "o", h: 1, b: "c", be: [3], s: { t: "t", d: [1, 5] } },
            { t: "o", h: 1, b: "c", be: [2, 3, 4] },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2] },
            { t: "o", h: 1, s: { t: "t", d: [4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3, 5] } },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [2, 6] }, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, b: "c", be: [2, 3, 4] },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2, 3] },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "b", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 5] } },
            { t: "o", h: 1, b: "c", be: [3] },
            { t: "o", h: 1, b: "c", be: [2, 3, 4] },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "y" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2] },
            { t: "o", h: 1, s: { t: "t", d: [4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] }, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 4, 5] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, b: "c", be: [3], s: { t: "t", d: [1, 5] } },
            { t: "o", h: 1, b: "c", be: [2, 3] },
            { t: "o", h: 1, b: "c", be: [2, 3, 4] },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
          ],
          [
            { t: "y" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2] },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [2, 6] }, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 5] } },
            { t: "o", h: 1, b: "c", be: [2, 3] },
            { t: "o", h: 1, b: "c", be: [2, 3, 4] },
            { t: "s" },
            { t: "s" },
          ],
          [
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1, b: "c", be: [1, 2] },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, b: "c", be: [2, 3] },
          ],
          [
            { t: "o", h: 1, b: "c", be: [2, 3] },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
        ]
      end
    end
  end
end
