# frozen_string_literal: true

module Scenarios
  class Scenario320 < Base
    ID = "320"
    NAME = "The Bloody Woods"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 11, 2].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_5_1,
        [3, :usa_leader_4_1],
        [10, :usa_rifle_s],
        :usa_m2_browning,
        [4, :usa_m1918_bar],
        :usa_m4105_sherman,
        :usa_m1_mortar,
        [3, :usa_m3a1_half_track],
        :usa_radio_105mm,
        :usa_m10a1,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_4_1,
        :ger_leader_3_1,
        [6, :ger_rifle_s],
        [2, :ger_mg_42],
        [2, :ger_kz_8cm_grw_42],
        [2, :ger_panzerschreck],
        [2, :ger_crew_t],
        :ger_7_5cm_leig_18,
        :ger_7_5cm_pak_40,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 10,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Hürtgen Forest, Germany",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Hürtgen Forest was a series of battles between
          American and German forces on the Western Front, just east of the
          Belgian-German border. Lasting 88 days, it was the longest battle on
          German ground during World War II and the second longest battle the
          U.S. Army has ever fought (after the Battle of Bataan).",
          "The initial goal was to pin down German forces in the area to keep
          them from reinforcing the front lines farther north in Aachen, where
          the U.S. was fighting against the Siegfried Line network of
          pillboxes, tank traps, and mindfields among fortified industrial
          towns and villages. Instead, the Allies progress was slow, with
          heavy casualties, as the defenders took full advantage of the
          terrain and fortifications of the Westwall (Siegfried Line). The
          forest cost the U.S. First Army tens of thousands of casualties, and
          though the German losses were significant as well, it was ultimately
          an Allied defeat. The battle ended with a German counterattack — the
          Battle of the Bulge.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [1, "rain"],
          wind: [3, 3, true],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [19, 6, 2], [19, 18, 2], [14, 17, 2], [8, 4, 2], [12, 11, 2], [8, 8, 2], [15, 8, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-4", 0], ["0-3", 1], ["0-4", 2], ["0-3", "3-4"], ["0-2", 5], ["0-3", "6-7"],
              ["0-4", "8-12"], ["0-3", "13-22"],
            ],
          },
          axis_setup: {
            "0" => [
              ["6-22", 0], ["5-22", 1], ["6-22", 2], ["5-22", "3-4"], ["4-22", 5], ["5-22", "6-7"],
              ["6-22", "8-9"], ["7-22", "10-11"], ["9-22", "12-13"], ["10-22", "14-20"],
              ["9-22", "21-22"],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [2, 6] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f", r: { t: "d", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", r: { t: "d", d: [3, 5] } },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] }, r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 3, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "f", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
          ],
          [
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 5] } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
          ],
          [
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] }, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [2, 4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 6] } },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [3, 5, 6] }, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] }, r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 3] } },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
        ]
      end
    end
  end
end
