# frozen_string_literal: true

module Scenarios
  class Scenario035 < Base
    ID = "035"
    NAME = "Karelian Bulwark"
    ALLIES = ["ussr"].freeze
    AXIS = ["fin"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 6, 13].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_5_1,
        [3, :ussr_leader_4_1],
        [8, :ussr_rifle_s],
        [3, :ussr_smg_s],
        :ussr_radio_152mm,
        [3, :ussr_dp_27],
        :ussr_sg_43,
        [2, :ussr_ft],
        [2, :ussr_sc],
        [2, :ussr_t_34_85],
        [2, :ussr_is_2],
        :ussr_su_152,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :fin_leader_6_1,
        :fin_leader_5_1,
        [7, :fin_regular_s],
        [4, :fin_elite_crew_t],
        [4, :fin_mg_08_15],
        [2, :fin_75mm_gun],
        [2, :fin_57mm_zis_2],
        [2, :fin_81mm_tampella],
        [2, :fin_panzerfaust],
        [2, :fin_panzerschreck],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Siiranmäki, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Vyborg–Petrozavodsk offensive or Karelian offensive was a
          strategic operation by the Soviets against Finland on the Karelian
          Isthmus and East Karelia fronts of the Continuation War. The Soviet
          forces captured East Karelia and Vyborg/Viipuri, but after that the
          fighting reached a stalemate.",
          "The Finnish Army started dug in and in a well-fortified position,
          but the Soviet air attacks surprised the defending forces and the
          initial defensive line of trenches and fortifications were quickly
          overrun and destroyed in the breakthrough sector. The second line of
          defense was the VT-line, where the Soviets attempted to break
          through at a perceived weak point at Siiranmäki. It was not.
          Siiranmäki was also the first place where Finnish troops had
          Panzerfausts and Panzerschrecks imported from Germany. Though
          Finnish troops managed to contain the Soviet breakthrough at
          Siiranmäki, the VT-line had already been breached at Kuuterselkä.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 4, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [2, 7, 2], [6, 6, 2], [10, 6, 2], [14, 6, 2], [17, 7, 2], [21, 8, 2], [7, 3, 2],
          ],
          allied_setup: { "0" => [["0-5", 8], ["18-22", 8], ["19-22", 9], ["*", "0-7"]] },
          axis_setup: { "0" => [["*", "17-22"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 5] }, h: 1 },
            { t: "o", r: { t: "p", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "f", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "p", d: [4, 6] }, h: 1 },
            { t: "f", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "f", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 5] }, h: 1 },
            { t: "o", r: { t: "p", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "f", r: { t: "p", d: [1, 5] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 3, 6] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 5] }, h: 1 },
            { t: "o", r: { t: "p", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 2, 4] }, h: 1 },
            { t: "f", r: { t: "p", d: [1, 5] }, h: 1 },
            { t: "o", r: { t: "p", d: [3, 6] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 3, 5] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", r: { t: "p", d: [2, 5] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [3, 5] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 3, 6] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 3, 5] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 6] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 5] }, h: 1 },
            { t: "o", r: { t: "p", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "f", r: { t: "p", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "p", d: [1, 5] }, h: 1 },
            { t: "o", r: { t: "p", d: [4, 6] }, h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 5] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 5] } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 3, 6] }, h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "p", d: [2, 3, 6] }, h: 1 },
          ],
          [
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1, s: { t: "t", d: [2, 4] } },
            { t: "o", s: { t: "t", d: [1, 4] }, h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 5] } },
            { t: "o", r: { t: "p", d: [3, 6] }, h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
        ]
      end
    end
  end
end
