# frozen_string_literal: true

module Scenarios
  class Scenario421 < Base
    ID = "421"
    NAME = "Amal River"
    ALLIES = ["dut"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 1, 11].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :alm_leader_4_1,
        [4, :alm_conscript_s],
        [2, :alm_crew_t],
        :alm_12_7mm_hmg,
        [2, :alm_75mm_gun],
        [2, :pillbox],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :jap_leader_5_1],
        [6, :jap_snlf_s],
        :jap_kohei_ka_s,
        [2, :jap_type_96_lmg],
        [2, :jap_type_89_gren_l],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Tarakan, Dutch East Indies",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Tarakan took place a day after the Empire of Japan
          declared war on the Kingdom of the Netherlands. Although Tarakan was
          only a small marshy island off northeastern Borneo in the Dutch East
          Indies, its 700 oil wells, refineries, and airfield made it a
          crucial objective for Japan. For the capture of Tarakan, the
          Japanese planned for a two pronged landing from the eastern side of
          the Island. One prong of the advance, the Right Wing Unit, would
          land at the shores near the Amal River and destroy any Dutch troops
          there. Without waiting for the landing to be completed, the unit
          would then move westwards through the jungle and launch a sudden
          attack to seize the Pamoesian oilfields.",
          "The Right Wing Unit, having mistaken the fires at the Gunung
          Cangkol oil field for that of the Lingkas oil field to the south,
          landed several kilometers north of their intended landing point, the
          mouth of the Amal River. Reaching the Amal river just before dawn,
          the unit attacked and outflanked the Dutch pillboxes located there.
          About 30 remaining Dutch troops withdrew to a new support point near
          the Pamoesian River. As fires from the oil fields rendered many
          support points useless, this had become the main point of defense on
          the eastern front, and became a rallying base for retreating troops,
          enabling the Dutch to restore the front line.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 1, false],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [7, 16, 1], [9, 9, 1], [11, 18, 1], [9, 22, 1], [4, 19, 1],
          ],
          allied_setup: {
            "0" => [
              ["0-11", "0-1"], ["0-12", 2], ["0-11", 3], ["0-12", "4-6"], ["0-11", 7], ["0-12", 8],
              ["0-11", "9-10"], ["0-10", 11], ["0-11", 12], ["0-10", 13], ["0-11", "14-18"],
              ["0-10", 19], ["0-11", 20], ["0-10", 21], ["0-11", 22],
            ],
          },
          axis_setup: {
            "0" => [["13-14", "0-1"], [14, 2], ["13-14", 3], [14, "4-10"], ["13-14", 11], [14, 12]],
          },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "s" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "s" },
            { t: "y" },
          ],
          [
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [3, 6] }, s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "s" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [2, 3] } },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "s", s: { t: "s", d: [2, 4] } },
            { t: "y", s: { t: "s", d: [1, 4] } },
          ],
          [
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "s" },
            { t: "s" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "s" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "s" },
            { t: "s" },
            { t: "y" },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [1, 5] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "s" },
            { t: "s" },
            { t: "y" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "s" },
            { t: "y", s: { t: "s", d: [4, 6] } },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] }, r: { t: "d", d: [2, 6] } },
            { t: "s", s: { t: "s", d: [1, 3] } },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "j", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 3 },
            { t: "s", s: { t: "s", d: [4, 6] } },
            { t: "y", s: { t: "s", d: [1, 5] } },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "j", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "j" },
            { t: "o", s: { t: "s", d: [5, 6] } },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [2, 6] }, s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1, s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o", s: { t: "s", d: [2, 3] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 3 },
            { t: "s" },
            { t: "s" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "o", h: 1, s: { t: "s", d: [4, 6] } },
            { t: "o", h: 1, s: { t: "s", d: [1, 3] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "y" },
          ],
        ]
      end
    end
  end
end
