# frozen_string_literal: true

module Scenarios
  class Scenario328 < Base
    ID = "328"
    NAME = "Hillman Fortress"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 6, 6].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_6_2,
        [2, :uk_leader_5_2],
        :uk_leader_4_1,
        [10, :uk_line_s],
        [4, :uk_bren_lmg],
        [2, :uk_vickers_mg],
        [2, :uk_ml_3inch_mortar],
        [2, :uk_sc],
        :uk_radio_152mm,
        [4, :uk_sherman_firefly],
        [2, :uk_m5_half_track],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :ger_leader_4_1],
        [8, :ger_volksgrenadier_s],
        [6, :ger_mg_42],
        [2, :ger_12cm_grw_42],
        :ger_crew_t,
        :ger_8_8cm_pak_43,
      ] },
    }.freeze

    INIT_AXIS_UNITS = [
      { data: :bunker, x: 18, y: 12, facing: 3 },
      { data: :bunker, x: 17, y: 8, facing: 3 },
      { data: :bunker, x: 13, y: 8, facing: 3 },
      { data: :bunker, x: 16, y: 11, facing: 2 },
      { data: :bunker, x: 6, y: 8, facing: 2 },
      { data: :bunker, x: 9, y: 8, facing: 2 },
      { data: :bunker, x: 14, y: 15, facing: 5 },
      { data: :bunker, x: 15, y: 14, facing: 4 },
      { data: :bunker, x: 6, y: 17, facing: 6 },
      { data: :bunker, x: 4, y: 12, facing: 1 },
      { data: :bunker, x: 10, y: 11, facing: 2 },
      { data: :bunker, x: 13, y: 11, facing: 2 },
      { data: :mines12, x: 19, y: 7, facing: 2 },
      { data: :mines12, x: 18, y: 9, facing: 2 },
      { data: :mines12, x: 19, y: 8, facing: 2 },
      { data: :wire, x: 18, y: 8, facing: 2 },
      { data: :wire, x: 17, y: 7, facing: 2 },
      { data: :wire, x: 16, y: 7, facing: 2 },
      { data: :wire, x: 13, y: 7, facing: 2 },
      { data: :wire, x: 12, y: 7, facing: 2 },
      { data: :wire, x: 9, y: 7, facing: 2 },
      { data: :wire, x: 8, y: 7, facing: 2 },
      { data: :wire, x: 6, y: 7, facing: 2 },
      { data: :wire, x: 5, y: 7, facing: 2 },
      { data: :wire, x: 5, y: 8, facing: 2 },
    ].freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Colleville-sur-Orne, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          init_axis_units:,
        }
      end

      def description
        [
          "The Hillman Fortress (Widerstandsnest 17) was a German bunker
          complex and command post built during the Second World War and
          located near Colleville-Montgomery in Normandy, France. The bunker
          complex, designated as Hill 61 and codenamed Hillman by the British
          was assaulted by the 1st Battalion, Suffolk Regiment on D-Day. The
          Suffolks had landed on Sword Beach that morning and began heading
          inland to clear their objectives.",
          "The well-designed and defended bunkers proved difficult to take and
          the Suffolks brought Shermans from 13/18 Hussars and a second
          assault overran the site. To silence the bunkers Sherman Fireflies
          fired on the armoured cupolas but the rounds bounced off. The
          well-defended bunkers were proving an incredibly difficult task for
          the infantry, but the combined armour and infantry succeeded in
          taking most of the complex by that night. The last remaining bunker
          surrendered the next morning, by which point the Suffolks had lost
          two officers and five men killed and 24 wounded.",
          "Historians suggest that the strong resistance of Hillman
          contributed to preventing the 3rd Infantry Division taking Caen as
          planned by the evening of D-Day.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 3, false],
          hexes:,
          layout:,
          allied_dir: 6,
          axis_dir: 3,
          victory_hexes: [
            [6, 8, 2], [9, 8, 2], [13, 8, 2], [4, 12, 2], [6, 17, 2], [14, 14, 2], [17, 8, 2],
            [18, 12, 2], [7, 11, 2], [12, 14, 2], [9, 14, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-4", 6], ["0-3", "7-8"], ["0-2", "9-10"], ["0-1", "11-12"], [0, 13], ["*", "0-5"],
            ],
          },
          axis_setup: {
            "0" => [
              ["6-17", 8], ["5-17", 9], ["5-18", 10], ["4-18", "11-12"], ["4-17", 13], ["5-17", 14],
              ["5-15", 15], ["6-14", 16], ["6-13", 17],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 2, 4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3, 5] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 6] } },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", h: 1, s: { t: "t", d: [1, 3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [4, 6] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [1, 3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] }, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] }, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] }, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", h: 1, s: { t: "t", d: [1, 2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 2, 5] } },
            { t: "o", h: 1, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3, 4, 6] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [3, 4, 6] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1, s: { t: "t", d: [2, 4, 6] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, s: { t: "t", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
