# frozen_string_literal: true

module Scenarios
  class Scenario104 < Base
    ID = "104"
    NAME = "Ayo Gorkhali"
    ALLIES = ["ind"].freeze
    AXIS = ["ger"].freeze
    STATUS = "a"

    class << self
      def generate
        {
          turns: 6,
          first_setup: 1,
          first_move: 2,
          date: [1942, 7, 1],
          location: "Deir el Shein, Egypt",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "First battle of El Alamein.  The Commonwealth forces are on their
          heels, and though the Germans are also exhausted and short on
          supplies, Rommel attempts to press his advantage.  Hoping to prevent
          the Germans from routing his forces and reaching his home base in
          Cairo, Auchinleck constructs several \"boxes\" to dig in and stop
          the advance.  On the morning of July 1st, 1942, as part of a
          flanking maneuver around Deir el Abyad, the 21st Panzer Division
          runs into the hastily deployed 18th Indian Infantry brigade who now
          occupied Deir el Shein.",
          "Historically, the Indians didn't have time to create a proper
          fortified box and were overrun after a day of desperate fighting,
          but bought time for Auchinleck to organize a defense to the west at
          Ruweisat Ridge.  The British 1st Armoured Division was sent to
          intervene at Deir el Shein but ran into the 15th Panzer Division
          instead to the south and ultimately was unable to relieve the
          Indians.  This version of the part of the action posits what might
          have happened had the relief forces arrived in time.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [2, 4, true],
          hexes:,
          layout: [15, 21, "x"],
          allied_edge: "r",
          axis_edge: "l",
          victory_hexes: [
            [2, 16, 2], [6, 9, 1], [6, 15, 1], [10, 10, 1], [11, 13, 1], [13, 18, 1], [13, 2, 1],
          ],
          allied_setup: {
            "0": 0.upto(20).map do |y|
              (((y - 12).abs / 2) + 3).abs.upto(14).map { |x| [x, y] }
            end.flatten(1),
            "3": 10.upto(14).map { |x| [x, 20] }.concat(15.upto(20).map { |y| [14, y] }),
          },
          axis_setup: {
            "0": 0.upto(20).map do |y|
              0.upto((((y - 12).abs / 2) + 1)).map { |x| [x, y] }
            end.flatten(1),
          },
          base_terrain: "d",
        }
      end

      def hexes
        [
          [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "r" },
            { t: "r" },
            { t: "s", r: { d: [3, 6] } },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "r" },
            { t: "r" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "r" },
            { t: "r" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "r" },
            { t: "r" },
            { t: "s", r: { d: [3, 6] } },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "r" },
            { t: "r" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "s" },
            { t: "o" },
            { t: "r" },
            { t: "r" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "r" },
            { t: "r" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "r" },
            { t: "r" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "s" },
            { t: "o", r: { d: [3, 6] } },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "o", r: { d: [3, 5, 6] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "s" },
            { t: "s", r: { d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 2, 5] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "s", r: { d: [3, 4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s", r: { d: [2, 5] } },
            { t: "s" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "b" },
            { t: "r" },
            { t: "r" },
            { t: "o", r: { d: [2, 5] } },
            { t: "s" },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s", r: { d: [4, 6] } },
            { t: "s", r: { d: [1, 4] } },
            { t: "s", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "s", r: { d: [1, 3] } },
            { t: "r" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "r" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s", r: { d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "r" },
            { t: "r" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "r" },
            { t: "r" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s", r: { d: [2, 5] } },
            { t: "s" },
          ], [
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s", r: { d: [2, 5] } },
          ],
        ]
      end

      def allied_units
        {
          "0": { list: [
            :uk_leader_5_1,
            :uk_leader_4_1,
            [5, :uk_gurkha_s],
            [4, :uk_crew_t],
            [2, :uk_vickers_mg],
            [2, :uk_qf_25_pounder],
            [2, :uk_qf_6pdr_mk_ii],
            [2, :uk_matilda_ii],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
          "3": { list: [
            :uk_leader_5_2,
            [4, :uk_line_s],
            [2, :uk_universal_carrier],
            [5, :uk_crusader_iii],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
        }
      end

      def axis_units
        {
          "0": { list: [
            :ger_leader_6_2,
            :ger_leader_5_1,
            [6, :ger_rifle_s],
            [2, :ger_mg_34],
            [2, :ger_sdkfz_250_1],
            :ger_sdkfz_221,
            [6, :ger_pzkpfw_iii_l],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
        }
      end
    end
  end
end
