# frozen_string_literal: true

module Scenarios
  class Scenario316 < Base
    ID = "316"
    NAME = "A Bridge Too Far"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 9, 18].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_6_1,
        [2, :uk_leader_5_1],
        [7, :uk_airborne_s],
        [4, :uk_bren_lmg],
        [2, :uk_piat],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_4_1,
        [3, :ger_rifle_s],
        :ger_mg_42,
      ] },
      "1": { list: [
        [2, :ger_leader_5_1],
        [4, :ger_ss_s],
        [2, :ger_mg_42],
        [2, :ger_pzkpfw_ii_luchs],
        :ger_stug_iv,
        [4, :ger_sdkfz_251_1],
      ] },
      "4": { list: [
        :ger_leader_5_1,
        :ger_leader_4_1,
        [4, :ger_ss_s],
        [2, :ger_mg_42],
        [2, :ger_stug_iii_f_g],
        :ger_marder_iii,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Arnhem, Netherlands",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "During Operation Market Garden, Lt. Col. John Frost, commander of
          the 2nd Parachute Battalion of the 1st Parachute Brigade led a group
          of about 750 lightly armed men into Arnhem along the Rhine River.
          Encountering little opposition, they had been unable to secure their
          objects along the way (the bridges had either been blown up or
          moved) until they reached the main road bridge in Arnhem, where they
          captured the northern end, but were unable to secure the southern
          end from the German defenders.  They were able to consolidate their
          position and quickly repulsed other German units when they arrived
          to secure the bridge.",
          "The next day, the troops of the 9th SS Panzer Division quickly
          surrounded them, cutting them off from the rest of the division. The
          9th SS Reconnaissance Battalion headed back toward Arnhem from the
          south of the river, having concluded that it was not needed at
          Nijmegen. Aware of the British troops at the bridge, they attempted
          to rush it, and were repulsed with many losses in a two-hour battle.
          Twelve of the 22 armored vehicles in the attack were destroyed or
          knocked out and over 70 men killed including its commanding officer.
          German attacks on the British at the Arnhem bridge continued for the
          rest of the day but the British held on.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 3, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [8, 9, 1], [10, 5, 1], [8, 6, 1], [12, 13, 1], [4, 8, 1], [4, 5, 1], [7, 12, 2],
          ],
          allied_setup: {
            "0" => [
              ["3-14", 8], ["6-14", 9], ["9-14", "10-11"], ["11-14", "12-13"], ["12-14", "14-15"],
              [14, "16-17"], ["*", "0-7"],
            ],
          },
          axis_setup: {
            "0" => [
              ["0-1", 10], ["0-4", 11], ["0-7", "12-13"], ["0-9", "14-15"], ["3-10", 16],
              ["7-10", 17], ["8-12", 18], ["9-12", 19], ["11-13", 20], ["11-14", 21], ["12-14", 22],
            ],
            "1" => [["0-1", 18], ["0-5", 19], ["0-6", 20], ["0-7", 21], ["0-8", 22]],
            "4" => [["*", 0]],
          },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "b" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "f" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
          ],
          [
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "b" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1.5 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1.5 },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "b" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "m", s: "u" }, d: 3 },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 3, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
          ],
          [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
