# frozen_string_literal: true

module Scenarios
  class Scenario506 < Base
    ID = "506"
    NAME = "A Ridge Too Far"
    ALLIES = ["gre"].freeze
    AXIS = ["ita"].freeze
    STATUS = "p"

    DATE = [1940, 11, 2].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": {
        list: [
          :alm_leader_5_1,
          :alm_leader_4_1,
          [9, :alm_regular_s],
          :alm_regular_t,
          :alm_vickers_mg,
          :alm_81mm_mortar,
          :alm_75mm_gun,
          [2, :pillbox],
        ],
      },
    }.freeze

    AXIS_UNITS = {
      "0": {
        list: [
          :ita_leader_4_1,
          :ita_leader_3_1,
          [7, :ita_fucilieri_s],
          [2, :ita_breda_m37],
          [4, :ita_l3_35],
          [2, :ita_m13_40],
        ],
      },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Elaia, Greece",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["axis_fragile_vehicles"],
        }
      end

      def description
        [
          "The Battle of Elaia-Kalamas was fought
          during the opening phase of the Greco-Italian War. As Italian forces
          advanced from Albania through the rugged region of Epirus, the
          Greeks bought time to finish mobilizing to full strength by falling back to the
          Elaia-Kalamas ridge, a defensive line protecting the route to
          Ioannina and central Greece.  Despite being outnumbered and
          under-equipped, the Greek 8th Infantry Division held firm.",

          "Defending from fortified positions along the ridge line, Greek
          troops used the mountainous terrain and local familiarity to repel a
          series of determined Italian attacks. The Italians suffered heavy
          losses and failed to gain ground, forcing a halt to their offensive.
          The battle marked one of the first successful Allied defensive
          actions of World War II, boosting Greek morale and setting the stage
          for a counteroffensive that pushed deep into Italian-occupied
          Albania.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [2, 3],
          wind: [0, 3, false],
          hexes:,
          layout:,
          allied_dir: 1.5,
          axis_dir: 4.5,
          victory_hexes: [
            [9, 5, 1], [2, 11, 2], [12, 12, 1], [10, 13, 1], [12, 15, 1], [8, 17, 1], [1, 20, 1],
          ],
          allied_setup: { "0" => [
            ["*", "18-22"], ["3-14", 17], ["6-14", 16], ["8-14", 15], ["9-14", "13-14"],
            ["10-14", "11-12"], ["11-14", "9-10"], ["12-14", 8],
          ] },
          axis_setup: { "0" => [
            ["7-8", 0], ["6-8", 1], ["7-8", 2], ["6-8", 3], ["7-9", 4],
            [0, "10-13"], [1, "11-13"], [2, "11-14"],
          ] },
          base_terrain: "m",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { d: [3, 6] } },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [3, 5] } },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 4 },
            { t: "b", h: 5 },
            { t: "b", h: 5 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { d: [3, 6] } },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 6] } },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 4 },
            { t: "b", h: 5 },
            { t: "b", h: 5 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { d: [3, 6] } },
            { t: "o", h: 4 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [3, 5] } },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 4 },
            { t: "b", h: 5 },
            { t: "b", h: 5 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { d: [3, 6] } },
            { t: "o", h: 4 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 4 },
            { t: "b", h: 5 },
            { t: "b", h: 5 },
          ], [
            { t: "o", h: 4, r: { d: [1, 4] } },
            { t: "o", h: 4, r: { d: [1, 3] } },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 4 },
            { t: "b", h: 4 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 2, 5] } },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
          ], [
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ], [
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { d: [2, 6] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o", d: 3, st: { sh: "l2", s: "f" } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1, r: { d: [3, 5, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { d: [3, 6] } },
            { t: "o", h: 2, r: { d: [2, 4] } },
            { t: "o", h: 2, r: { d: [1, 4] } },
            { t: "f", h: 2 },
            { t: "f", h: 3 },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 3, d: 1, st: { sh: "l2", s: "f" } },
            { t: "o", h: 3, d: 1, st: { sh: "l2", s: "f" } },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
          ], [
            { t: "b", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 3, r: { d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 2 },
          ], [
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 3, r: { d: [4, 6] } },
            { t: "o", h: 3, r: { d: [1, 4] } },
            { t: "o", h: 3, r: { d: [1, 3] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ], [
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 3, r: { d: [4, 6] } },
            { t: "o", h: 3, r: { d: [1, 4] } },
            { t: "o", h: 3, r: { d: [1, 3] } },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 3, d: 3, st: { sh: "l2", s: "f" } },
            { t: "o", h: 3, r: { d: [4, 6] } },
            { t: "o", h: 3, r: { d: [1, 3] } },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f", h: 1 },
          ], [
            { t: "o", h: 3 },
            { t: "o", h: 3, d: 3, st: { sh: "l2", s: "f" } },
            { t: "o", h: 2, r: { d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", s: { d: [4, 6] } },
            { t: "o", s: { d: [1, 5] } },
            { t: "o" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [3, 5] } },
            { t: "o", h: 2, d: 2, st: { sh: "l2", s: "f" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", s: { d: [3, 5] } },
            { t: "o" },
            { t: "o", s: { d: [2, 4] } },
            { t: "o", s: { d: [1, 4] } },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [2, 6] } },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
