# frozen_string_literal: true

module Scenarios
  class Scenario208 < Base
    ID = "208"
    NAME = "Ayo Gorkhali"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 2, 17].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [1, :uk_leader_6_1],
        [2, :uk_leader_5_1],
        [9, :uk_gurkha_s],
        [2, :uk_lewis_gun],
        [1, :uk_2inch_mortar],
        [1, :uk_radio_114mm],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [1, :ger_leader_5_1],
        [5, :ger_fallschirmjager_s],
        [2, :ger_mg_42],
        [1, :ger_8cm_grw_34],
        [1, :ger_elite_crew_t],
        [1, :ger_7_5cm_gebg_36],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Monte Cassino, Italy",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "On Februry 15th, 1944 American bombers performed a massive raid on
          the abbey of Monte Cassino after ground attacks had failed to
          capture it or the surrounding hills. The raid was a debacle on many
          levels — based on faulty assumptions that the abbey was being used
          as an artillery observation point (it wasn't) and expanded by the
          U.S. Army Air Force who wanted to showcase U.S. Army air power to
          support ground operations, the bombing raid was spectacularly
          destructive but achieved very little (what little it did achieve was
          due to inaccurate bombing that managed not to inflict friendly fire
          and hit nearby German units purely by accident).  It completely
          destroyed the abbey, killing numerous civilians taking shelter
          there.",
          "Worst of all, after the bombing, German paratroopers then occupied
          the ruins and turned it into a fortress...  And the observation post
          it hadn't been before.", "On the night of the 17th, a second assault
          took on the German defenses on the high ground by the Rajputana and
          Gurkha Rifles took place including a sweep across the slopes and
          ravines by the latter in a direct assault on the monastery. This
          attack was across appalling terrain, but it was hoped that the
          Gurkhas, expert in mountain terrain, would succeed. They did not.
          The fighting was brutal, but despite the unquestionably courageous
          efforts of the attackers, no progress was made and casualties were
          heavy.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 3, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [4, 17, 2], [5, 20, 2], [9, 13, 2], [5, 11, 2], [4, 14, 2], [6, 14, 2], [4, 5, 1],
          ],
          allied_setup: { "0" => [["*", "0-7"]] },
          axis_setup: { "0" => [["*", "9-22"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 5] } },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [5, 6] } },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 4, d: 3 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 5, st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", h: 5, st: { sh: "s2", s: "u" }, d: 2 },
            { t: "o", h: 4, r: { t: "d", d: [2, 5] } },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 4 },
            { t: "o", h: 3 },
            { t: "d", h: 4, d: 3 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 5, st: { sh: "m2", s: "u" }, d: 3 },
            { t: "o", h: 5, st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o", h: 5, st: { sh: "s2", s: "u" }, d: 5 },
            { t: "o", h: 4, r: { t: "d", d: [2, 6] } },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 4 },
            { t: "b", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 5, st: { sh: "m2", s: "u" }, d: 3 },
            { t: "d", h: 5, d: 3 },
            { t: "o", h: 5, st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o", h: 4, r: { t: "d", d: [3, 5] } },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "b", h: 4 },
            { t: "b", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 5, st: { sh: "s2", s: "u" }, d: 2 },
            { t: "o", h: 5, st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o", h: 5 },
            { t: "o", h: 5, st: { sh: "s2", s: "u" }, d: 3, b: "c", be: [4, 5] },
            { t: "o", h: 4, r: { t: "d", d: [2, 6] }, b: "c", be: [4, 5] },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [2, 6] }, b: "c", be: [3, 4, 5] },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1 },
          ],
          [
            { t: "b", h: 4 },
            { t: "b", h: 3 },
            { t: "o", h: 4, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 5, st: { sh: "m2", s: "u" }, d: 2 },
            { t: "o", h: 5, st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o", h: 5, st: { sh: "m2", s: "u" }, d: 3, b: "c", be: [4, 5] },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] }, b: "c", be: [4, 5] },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 5] }, b: "c", be: [4] },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "b", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "d", h: 5, d: 2 },
            { t: "o", h: 5, st: { sh: "s2", s: "u" }, d: 5 },
            { t: "o", h: 5, st: { sh: "s2", s: "u" }, d: 6, b: "c", be: [4, 5] },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] }, b: "c", be: [4, 5] },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [2, 6] }, b: "c", be: [3, 4, 5] },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
          ],
          [
            { t: "d", h: 4, d: 2 },
            { t: "o", h: 4, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 4 },
            { t: "o", h: 5, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 5, r: { t: "d", d: [1, 2] } },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
          ],
          [
            { t: "o", h: 3 },
            { t: "d", h: 4, d: 2 },
            { t: "o", h: 4, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 3] } },
            { t: "d", h: 4, d: 1 },
            { t: "o", h: 4, r: { t: "d", d: [3, 5] } },
            { t: "d", h: 4, d: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 4 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
          ],
          [
            { t: "b", h: 3 },
            { t: "b", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 4 },
            { t: "b", h: 4 },
            { t: "o", h: 4, r: { t: "d", d: [2, 5] } },
            { t: "d", h: 4, d: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "b", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 4, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 3] } },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 3, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 4, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 3, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
        ]
      end
    end
  end
end
