# frozen_string_literal: true

module Scenarios
  class Scenario207 < Base
    ID = "207"
    NAME = "Guns in the Groves"
    ALLIES = ["usa"].freeze
    AXIS = ["ita"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 7, 12].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [1, :usa_leader_5_1],
        [1, :usa_leader_4_1],
        [6, :usa_rifle_s],
        [2, :usa_m1918_bar],
        [1, :usa_radio_105mm],
        [2, :usa_m3_half_track],
      ] },
      "2": { list: [
        [1, :usa_leader_4_1],
        [2, :usa_rifle_s],
        [1, :usa_m1918_bar],
        [3, :usa_m4_sherman],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [1, :ita_leader_5_1],
        [1, :ita_leader_3_1],
        [4, :ita_bersaglieri_s],
        [1, :ita_breda_30],
        [1, :ita_brixia_m35],
        [3, :ita_semovente_da_90_53],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Canicatti, Sicily",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "After the Allied landings of Sicily, the Allies rushed to capture
          ports and airfields to build up their forces, and then establish a
          line between Licata in the west and Catania on the east before
          reducing the rest of the island. The Axis plans had been to
          counter-attack the allied landings on the eastern coast of Sicily,
          but it soon became clear that the Axis forces were in danger of
          being cut off by allied forces moving north along that coast.",
          "Therefore Italian units took up rearguard positions to cover the
          withdrawal of the axis forces, particularly Kampfgruppe Schmalz and
          the Hermann Göring Division. The American advance toward Canicattì
          was temporarily held up by Semovente da 90/53 tank destroyers from
          the 161st Self-propelled Artillery Battalion, 526th Bersaglieri
          Battalion and 177th Bersaglieri Regiment from Gruppo Tattico Venturi
          as Kampfgruppe Schmalz retreated toward Catania.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 6, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [11, 21, 1], [8, 10, 2], [20, 8, 2], [7, 5, 2], [11, 5, 2], [2, 13, 2], [5, 7, 2],
          ],
          allied_setup: { "0" => [["*", "20-22"]], "2" => [] },
          axis_setup: { "0" => [["*", "0-18"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "g", b: "f", be: [1] },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "g" },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3, b: "f", be: [3] },
            { t: "g", b: "f", be: [1] },
            { t: "g" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 5] } },
            { t: "w" },
            { t: "o", b: "f", be: [3] },
            { t: "g", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "o", b: "f", be: [3] },
            { t: "o" },
            { t: "g", b: "f", be: [2, 3] },
            { t: "g", b: "f", be: [2, 3] },
            { t: "g", b: "f", be: [2, 3] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "d", d: 6.5 },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 4, b: "f", be: [3] },
            { t: "d", d: 4, b: "f", be: [2, 3] },
            { t: "o", r: { t: "d", d: [4, 6] }, b: "f", be: [2, 3] },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "d", d: 6 },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 2 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 4 },
            { t: "d", d: 4 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "g", b: "f", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [3] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "o" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "g", b: "f", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 6] }, b: "f", be: [3] },
            { t: "g", b: "f", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", d: 6, b: "f", be: [3] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
          ],
        ]
      end
    end
  end
end
