# frozen_string_literal: true

module Scenarios
  class Scenario209 < Base
    ID = "209"
    NAME = "Avalanche by a Thread"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 9, 9].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [1, :uk_leader_5_1],
        [1, :uk_leader_4_1],
        [4, :uk_line_s],
        [2, :uk_bren_lmg],
        [1, :uk_crew_t],
        [1, :uk_qf_6pdr_mk_iv],
      ] },
      "3": { list: [
        [1, :uk_leader_5_1],
        [1, :uk_leader_4_1],
        [4, :uk_guard_s],
        [2, :uk_bren_lmg],
        [2, :uk_piat],
        [2, :uk_universal_carrier],
        [1, :uk_radio_183mm],
      ] },
      "5": { list: [
        [2, :uk_leader_4_1],
        [4, :uk_line_s],
        [1, :uk_bren_lmg],
        [1, :uk_2inch_mortar],
        [1, :uk_universal_carrier],
        [1, :uk_u__carrier_6pdr],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [1, :ger_leader_6_1],
        [1, :ger_leader_5_1],
        [2, :ger_leader_4_1],
        [8, :ger_rifle_s],
        [3, :ger_mg_42],
        [1, :ger_5cm_legrw_36],
        [1, :ger_radio_10_5cm],
        [4, :ger_sdkfz_251_1],
      ] },
      "2": { list: [
        [1, :ger_leader_5_1],
        [2, :ger_rifle_s],
        [1, :ger_mg_42],
        [4, :ger_pzkpfw_iv_f2],
        [2, :ger_stug_iii_f_g],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Battipaglia, Italy",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "When the Allies landed at Salerno, it was decided not to bombard
          the beaches before the landing in an attempt to surprise the
          defenders. The defenders were not surprised. Troops were also landed
          at Calabria and Taranto in an attempt to draw off Axis defenders and
          cut them off. The Germans did not take the bait. Despite all that,
          and despite the fact that the Italian surrender did not cause the
          Germans to withdraw, the initial landings went well, the beaches
          were secured, and the Allied forces started to push inland.",
          "However, the beachhead was dangerously exposed and thinly held.
          Worse, the British and American beachheads were separated by the Sele
          river.  Recognizing an opportunity to destroy the invasion before it
          could expand, German commanders launched a series of powerful
          counterattacks spearheaded by the veteran 16th Panzer Division.
          Driving across the Sele Plain, the Germans sought to split the
          Allied line and force the invaders back into the sea. American and
          British troops, supported by hastily assembled reserves and naval
          gunfire (represented by the British radio) fought desperately to
          hold the fragile perimeter.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 1, false],
          hexes:,
          layout:,
          allied_dir: 3.5,
          axis_dir: 6.5,
          victory_hexes: [
            [4, 16, 1], [13, 19, 1], [20, 17, 1], [11, 11, 1], [9, 2, 1], [18, 6, 1], [19, 4, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-5", 0], ["0-5", 1], ["0-9", 2], ["0-12", 3], ["0-14", 4], ["0-14", 5],
              ["0-19", 6], ["0-19", 7], ["*", "8-22"],
            ],
            "3" => [
              [0, 13], [0, 14], [0, 15], [0, 16], [0, 17], [0, 18], [0, 19], [0, 20], [0, 21],
              ["*", 22],
            ],
            "5" => [
              [0, 13], [0, 14], [0, 15], [0, 16], [0, 17], [0, 18], [0, 19], [0, 20], [0, 21],
              ["*", 22],
            ],
          },
          axis_setup: {
            "0" => [
              ["7-22", 0], ["10-22", 1], ["14-22", 2], ["15-22", 3], ["16-22", 4], ["20-22", 5],
              ["21-22", 6],
            ],
            "2" => [
              ["7-22", 0], [22, 1], [22, 2], [22, 3], [22, 4], [22, 5], [22, 6],
            ],
          },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] }, s: { t: "s", d: [3, 6] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o" },
            { t: "g", b: "f", be: [2] },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "d", d: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o" },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [1] },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "d", d: 1 },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", b: "b", be: [1] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "g", b: "f", be: [3] },
            { t: "g", b: "f", be: [2, 3] },
            { t: "g" },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", b: "b", be: [1] },
            { t: "o", b: "b", be: [3] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2 },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 3 },
            { t: "o", b: "b", be: [1] },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [4, 6] }, b: "b", be: [3] },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 1 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1] },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", b: "b", be: [3] },
            { t: "o", r: { t: "t", d: [3, 6] }, b: "b", be: [1] },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [1] },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [1] },
            { t: "o", r: { t: "t", d: [2, 5] }, b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o" },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "g" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "g", b: "f", be: [1] },
            { t: "g" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] }, b: "f", be: [3] },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "f", be: [2, 3] },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] }, b: "f", be: [2] },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "g", b: "f", be: [1, 2] },
            { t: "g" },
            { t: "g", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o" },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2] },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
