# frozen_string_literal: true

module Scenarios
  class Scenario423 < Base
    ID = "423"
    NAME = "No. 3 Airstrip"
    ALLIES = ["aus"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 8, 31].freeze
    LAYOUT = [23, 11, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [4, :wire],
        [4, :mines8],
      ] },
      "1": { list: [
        [2, :uk_leader_4_1],
        [5, :uk_garrison_s],
        [2, :uk_vickers_mg],
        :uk_ml_3inch_mortar,
        [2, :uk_sc],
        :uk_radio_88mm,
      ] },
      "4": { list: [
        :uk_leader_6_1,
        [3, :uk_line_s],
        [2, :uk_bren_lmg],
        :uk_sc,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :jap_type_95_ha_go],
      ] },
      "1": { list: [
        :jap_leader_5_1,
        [2, :jap_leader_4_1],
        [9, :jap_snlf_s],
        [3, :jap_type_96_lmg],
        [2, :jap_type_97_81mm],
        :jap_radio_7_5cm,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 1,
          date:,
          location: "Gili Gili, Papua New Guinea",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["axis_fragile_vehicles"],
        }
      end

      def description
        [
          "In August of 1942, Japanese naval infantry landed at Milne Bay,
          intending to attack Allied airfields that had been established on
          the eastern tip of New Guinea. The Japanese landed farther east than
          intended, but pushed inland and began their advance towards the
          airfields. After several small engagements, the Japanese reached No. 3
          airstrip, where their initial attack was repulsed.",
          "A second attack came at 3AM on the 31st of August. Three waves of
          Japanese troops launched themselves across the open ground of the
          airstrip towards the defenders.  Coming under very heavy
          machine-gun, artillery and mortar fire, Japanese losses were high.
          The Japanese tried moving around the end of the airstrip, but they
          were met with heavy fire and around dawn, the Japanese withdrew.",
          "Ultimately, the attack on the airfield was the high point of the
          operation; due to poor intelligence work, the Japanese had
          miscalculated the size of the garrison; heavily outnumbered,
          suffering from a lack of supplies, and harrassed by Allied air
          superiority, the Japanese withdrew, giving the Allies one of their
          first clear victories of the war in the Pacific.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [5, "rain"],
          wind: [1, 4, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [5, 7, 1], [14, 7, 1], [2, 5, 1], [17, 5, 1], [9, 5, 1],
          ],
          allied_setup: {
            "0" => [["11-19", 2], ["1-19", 3], ["1-20", 4], ["*", "5-10"]],
            "1" => [["2-18", 6], ["*", "7-10"]],
            "4" => [[0, "6-9"], ["0-15", 10], ["21-22", 10]],
          },
          axis_setup: {
            "0" => [
              ["0-10", 2], ["20-22", 2], [0, 3], ["20-22", 3], [0, 4], ["21-22", 4], ["*", "0-1"],
            ],
            "1" => [
              ["0-10", 2], ["20-22", 2], [0, 3], ["20-22", 3], [0, 4], ["21-22", 4], ["*", "0-1"],
            ],
          },
          base_terrain: "m",
          night: true,
        }
      end

      def hexes
        [
          [
            { t: "j", r: { t: "p", d: [1, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "j" },
          ],
          [
            { t: "j", r: { t: "p", d: [2, 4] } },
            { t: "j", r: { t: "p", d: [1, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j", r: { t: "p", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "j" },
            { t: "j" },
          ],
          [
            { t: "j" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "y" },
          ],
          [
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "y" },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 5] }, r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
          ],
          [
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "y" },
          ],
          [
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "j" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [2, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j", r: { t: "p", d: [3, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "o" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "p", d: [3, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "p", d: [2, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "y" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "j", r: { t: "p", d: [3, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { t: "p", d: [3, 6] } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "y" },
          ],
        ]
      end
    end
  end
end
