# frozen_string_literal: true

module Scenarios
  class Scenario211 < Base
    ID = "211"
    NAME = "Fischfang"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 2, 16].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_6_2,
        :uk_leader_5_1,
        :uk_leader_4_1,
        [7, :uk_line_s],
        [2, :uk_bren_lmg],
        [2, :uk_vickers_mg],
        :uk_ml_3inch_mortar,
        [2, :uk_piat],
        :uk_radio_140mm,
        [3, :uk_m4_sherman],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_5_1,
        :ger_leader_4_1,
        [5, :ger_rifle_s],
        [3, :ger_mg_42],
        :ger_radio_10_5cm,
        [3, :ger_tiger_i],
        [3, :ger_pzkpfw_iii_n],
        [2, :ger_pzkpfw_iv_g],
        [2, :ger_sdkfz_250_1],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Compoleone, Italy",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The success of an amphibious landing at Anzio, in a basin
          consisting substantially of reclaimed marshland and surrounded by
          mountains, depended on surprise and if the invaders could build up
          strength and move inland before the defenders could occupy the
          mountains the landing force. The initial landing achieved complete
          surprise with no opposition and a jeep patrol even made it as far as
          the outskirts of Rome. However Major General Lucas, commander of the
          invading force, had little confidence in the operation as planned
          and failed to capitalize on the element of surprise and delayed his
          advance until he judged his position was sufficiently
          consolidated.",
          "In that time Field Marshal Albert Kesselring, the German commander
          in the Italian theatre, moved every unit he could spare into a
          defensive ring around the beachhead. His artillery units had a clear
          view of every Allied position. The Germans also stopped the drainage
          pumps and flooded the reclaimed marsh with salt water, hoping to
          trap the Allies and destroy them by epidemic. For weeks a rain of
          shells fell on the beach, the marsh, the harbour, on anything else
          observable from the hills, with little distinction between forward
          and rear positions.",
          "Within a month, the Germans launched counter-offensives. The second
          (Operation Fischfang) advanced down the line of the Via Anziate,
          supported by Tiger tanks. They overran the defending British troops,
          reaching the original defensive line that tentative Allied advances
          had barely expanded while the German forces gathered, running out of
          steam mainly due to the massive use of artillery by the defenders
          who outshoot the Germans by a ratio of about ten to one, including
          heavy shelling of German assembly areas.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 4, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [7, 12, 1], [14, 8, 1], [6, 19, 1], [9, 13, 1], [13, 15, 1],
          ],
          allied_setup: {
            "0" => [["0-2", 4], ["0-4", 5], ["0-7", 6], ["0-9", 7], ["0-12", 8], ["*", "9-22"]],
          },
          axis_setup: {
            "0" => [["5-14", 1], ["10-14", 2], ["11-14", 3], ["12-14", 4], ["13-14", 5], ["*", 0]],
          },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 2 },
            { t: "d", d: 3, h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "b" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", st: { sh: "l", s: "f" }, d: 3, h: 2 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "b" },
            { t: "b" },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "o", h: 2 },
            { t: "o", r: { t: "t", d: [3, 5] }, h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2] },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 2 },
            { t: "o", r: { t: "t", d: [2, 5] }, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "d", d: 2, h: 2 },
            { t: "o", r: { t: "t", d: [2, 5] }, h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o", s: { t: "s", d: [5, 6] } },
            { t: "b" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2, h: 1 },
            { t: "o", r: { t: "t", d: [2, 5] }, h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 2, h: 1 },
            { t: "o", r: { t: "t", d: [2, 5] }, h: 1 },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2, 3], h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [2, 6] }, h: 1 },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
          ],
          [
            { t: "f" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "d", b: "f", be: [2, 3], d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "d", d: 3, h: 1 },
          ],
          [
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "d", d: 3, h: 1 },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "o", d: 1, h: 1, st: { sh: "c", s: "u" } },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f" },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 3, h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "t", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "t", d: [1, 3] }, h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l", r: 2 }, h: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r", r: 2 }, h: 1 },
            { t: "o", r: { t: "t", d: [1, 2, 4], c: "l", r: 2 }, h: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r", r: 2 }, h: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "d", d: 1, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [1, 4, 6], c: "l", r: 2 }, h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l", r: 2 }, h: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r", r: 2 }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2, 3], h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "d", b: "f", be: [1], d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l", r: 2 }, h: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 3, h: 1 },
            { t: "o", b: "f", be: [2], h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "d", b: "f", be: [3], d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 1 },
            { t: "d", b: "f", be: [3], d: 3, h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 3, h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 3, h: 1 },
            { t: "o", r: { t: "t", d: [1, 2, 4], c: "l", r: 2 }, h: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r", r: 2 }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l", r: 2 }, h: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r", r: 2 }, h: 2 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 2 },
            { t: "d", d: 3, h: 1 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l", r: 2 }, h: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r", r: 2 }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [3], h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "d", d: 3, h: 2 },
            { t: "o", r: { t: "t", d: [1, 4, 6], c: "l", r: 2 }, h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l", r: 2 }, h: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 3, h: 1 },
            { t: "o", b: "f", be: [2], h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 2 },
            { t: "d", b: "f", be: [3], d: 3, h: 2 },
            { t: "o", b: "f", be: [2, 3], h: 2 },
            { t: "o", b: "f", be: [1], h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", r: { t: "t", d: [3, 6] }, h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2 },
            { t: "o", b: "f", be: [3], h: 2 },
            { t: "o", b: "f", be: [2, 3], h: 1 },
            { t: "o", b: "f", be: [1], h: 1 },
            { t: "o", b: "f", be: [1, 2], h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
