# frozen_string_literal: true

module Scenarios
  class Scenario120 < Base
    ID = "120"
    NAME = "Hill 609"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 4, 30].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_5_1,
        [2, :usa_leader_4_1],
        [2, :usa_engineer_s],
        [7, :usa_rifle_s],
        [4, :usa_m1918_bar],
        :usa_m2_browning,
        :usa_m1_mortar,
        :usa_radio_155mm,
        [2, :usa_m3_half_track],
        :usa_m3a1_half_track,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_5_1,
        [5, :ger_fallschirmjager_s],
        [3, :ger_elite_crew_t],
        [3, :ger_mg_42],
        :ger_kz_8cm_grw_42,
        [2, :ger_10_5cm_gebh_40],
        :ger_15cm_sig_33,
        [4, :mines8],
        [8, :wire],
      ] },
    }.freeze

    INIT_AXIS_UNITS = [
      { data: :bunker, x: 9, y: 10, facing: 1 },
      { data: :bunker, x: 10, y: 12, facing: 6 },
      { data: :bunker, x: 11, y: 21, facing: 2 },
    ].freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Djebel Tahent, Tunesia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          init_axis_units:,
        }
      end

      def description
        [
          "Hill 609 in Tunesia was the key to the German defensive line facing
          the U.S. II Corps as they attempted to advance toward Tunis, and the
          Germans deployed the Paratroop regiment to fortify the hill.  Used
          for artillery fire and observation, the Germans could also prevent
          movement by U.S. infantry to both the north and south. Hill 609 was
          deemed one of the most difficult objectives in Tunisia, as it was
          not only protected by steep slopes but also by fire from nearby high
          ground, giving the Germans a cross fire on the slopes leading up to
          it.",
          "After heavy fighting and high casualties, the 34th Division managed
          to take the hill and repelled several German counterattacks the
          following day.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 5, false],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [9, 9, 2], [10, 11, 2], [10, 21, 2], [11, 9, 2], [9, 16, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-2", "0-1"], ["0-3", "2-3"], ["0-4", "4-5"], ["0-5", "6-8"], ["0-4", "9-11"],
              ["0-5", "12-13"], ["0-6", "14-16"], ["0-5", "17-18"], ["0-4", "19-21"], ["0-5", 22],
            ],
          },
          axis_setup: {
            "0" => [
              ["13-14", 5], ["12-14", 6], ["7-14", "7-8"], ["6-14", "9-11"], ["7-14", "12-13"],
              ["8-14", "14-15"], ["10-14", "16-17"], ["11-14", 18], ["10-14", 19], ["9-14", 20],
              ["8-14", "21-22"],
            ],
          },
          base_terrain: "d",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", h: 1, d: 3 },
            { t: "r", h: 2 },
            { t: "r", h: 3, b: "c", be: [2, 3] },
            { t: "r", h: 3, b: "c", be: [2, 3] },
            { t: "r", h: 3, b: "c", be: [2, 3] },
            { t: "r", h: 3, b: "c", be: [2, 3] },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "d", h: 1, d: 3 },
            { t: "r", h: 2 },
            { t: "r", h: 3, b: "c", be: [2] },
            { t: "o", h: 5, b: "c", be: [1, 2, 3], s: { t: "t", d: [4, 5] } },
            { t: "o", h: 5, b: "c", be: [2, 3] },
            { t: "o", h: 5, b: "c", be: [2, 3] },
            { t: "o", h: 4, b: "c", be: [2, 3, 4] },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4, b: "c", be: [2] },
            { t: "o", h: 5, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "r", h: 3 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 5, s: { t: "t", d: [2, 3] } },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "b", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "b", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "d", h: 1, d: 3 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "b" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, s: { t: "t", d: [4, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, s: { t: "t", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "b" },
          ],
        ]
      end
    end
  end
end
