# frozen_string_literal: true

module Scenarios
  class Scenario010 < Base
    ID = "010"
    NAME = "Fish in a Barrel"
    ALLIES = ["ussr"].freeze
    AXIS = ["hun"].freeze
    STATUS = "p"

    DATE = [1941, 8, 1].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": {
        list: [
          :ussr_leader_5_1,
          [6, :ussr_rifle_s],
          :ussr_pm_m1910,
          [2, :ussr_t_26_m39],
          [2, :ussr_bt_7],
        ],
      },
    }.freeze

    AXIS_UNITS = {
      "0": {
        list: [
          [2, :axm_leader_3_1],
          [8, :axm_conscript_s],
          [2, :axm_conscript_t],
          [2, :axm_mg_30],
          [2, :axm_3_7cm_pak_36],
          [3, :axm_38m_toldi_i],
          [2, :axm_fiat_l3],
        ],
      },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_setup: 1,
          first_move: 2,
          date:,
          location: "Permvomaysk, Ukraine",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "While Hungary was a enthusiastic member of the Axis powers,
          participating in the invasion of Yugoslavia and Operation Barbarossa
          (despite not Germans not particularly wanting their assistance in
          the later), their army was not particularly known for its military
          prowess.  Their participation was also noted by German observers for
          its excessive cruelty, with Hungarian volunteers sometimes referred
          to as \"murder tourists.\"  Neither was their equipment particularly
          cutting edge, and by the battle of Stalingrad it was wildly obsolete
          compared to the Soviet equipment it faced, and the Hungarian Army
          was largely eliminated as an effective fighting force in the field
          by the beginning of 1943.",
          "Earlier in the war, however, the Hungarian Army was involved in
          several larger successful German campaigns, including during the
          battle of Uman during Operation Barbarossa, where it contributed to
          the effort to encircle disorganized Soviet troops at Permvomaysk.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [0, 3, false],
          hexes:,
          layout:,
          allied_edge: "t",
          axis_edge: "b",
          victory_hexes: [
            [13, 2, 1], [5, 5, 1], [8, 7, 1], [12, 7, 1], [10, 18, 2],
          ],
          allied_setup: { "0" => [["*", "0-8"]] },
          axis_setup: { "0" => [["*", "14-22"]] },
          base_terrain: "g",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [2, 6] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", s: { d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", s: { d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "g", b: "f", be: [5] },
            { t: "g", b: "f", be: [5, 6] },
            { t: "g", b: "f", be: [5, 6] },
            { t: "g", b: "f", be: [5, 6] },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { d: [3, 5] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [4, 6] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o", s: { d: [2, 5] } },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", d: 1, st: { sh: "l2", s: "f" } },
            { t: "o", d: 1, st: { sh: "l2", s: "f" } },
            { t: "o", s: { d: [2, 5] } },
            { t: "o", d: 1, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [3, 4, 6] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 2, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4, 5] } },
            { t: "o", r: { d: [1, 4] }, s: { d: [2, 5] } },
            { t: "o", r: { d: [1, 3] } },
            { t: "o", d: 1, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "l2", s: "f" } },
            { t: "o", d: 1, st: { sh: "l2", s: "f" } },
            { t: "o", r: { d: [2, 5] } },
            { t: "o", s: { d: [2, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 6] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", s: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4] } },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6] } },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "f", be: [3, 4] },
            { t: "o", s: { d: [2, 5] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "f", be: [3, 4] },
            { t: "o", s: { d: [2, 4] } },
            { t: "o", s: { d: [1, 4] } },
            { t: "o", s: { d: [1, 4] } },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g", b: "f", be: [3, 4] },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", b: "f", be: [1, 2] },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "x", s: "f" } },
            { t: "o", r: { d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 4, 6] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6] } },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6] } },
            { t: "w" },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6] } },
            { t: "w" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { d: [2, 5] } },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
