# frozen_string_literal: true

module Scenarios
  class Scenario212 < Base
    ID = "212"
    NAME = "A Gela Affair"
    ALLIES = ["usa"].freeze
    AXIS = ["ita"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 7, 10].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_6_1,
        [2, :usa_leader_5_1],
        [7, :usa_ranger_s],
        [3, :usa_m1918_bar],
        :usa_m1919_browning,
        [2, :usa_sc],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ita_leader_4_1,
        [4, :ita_fucilieri_s],
        [2, :ita_breda_30],
        :ita_brixia_m35,
        [3, :ita_crew_t],
        [3, :ita_obice_da_75_18],
        [3, :pillbox],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Gela, Sicily",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Gela was the opening engagement of the American
          portion of the Allied Invasion of Sicily, where U.S. Navy ships
          landed Army troops along the eastern end of the south coast of
          Sicily. Suffering attacks by Luftwaffe and Regia Aeronautica
          aircraft while defending the beachhead against counterattacks by
          Livorno Division and German Göring Division, the US Army captured
          the Ponte Olivo Airfield for use by United States Army Air Forces
          planes. The battle convinced U.S. forces of the value of naval
          artillery support, and revealed problems coordinating air support
          during amphibious operations.",
          "Among the first ashore, U.S. Rangers were landed on either side of
          the Gela pier. As they landed, they were immediately taken under
          fire from the Italian pillboxes and coastal batteries. The Rangers'
          objective was to capture the Gela pier for offloading the LSTs and
          secure Gela, but Italian defenders destroyed the masonry pier with
          demolition charges. The Rangers captured the town by along with
          three artillery pieces and 200 prisoners, allowing additional
          infantry tasked to help in the capture of Gela to be redirected
          inland to support the capture the Ponte Olivo Airfield instead.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 3, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [12, 9, 2], [7, 9, 2], [13, 4, 2], [21, 4, 2], [18, 8, 2], [8, 3, 2], [2, 3, 2],
          ],
          allied_setup: {
            "0" => [
              ["6-12", 12], ["5-12", 13], ["5-13", 14], ["5-12", 15], ["6-12", 16], ["6-11", 17],
              ["7-11", 18], ["7-10", 19], ["8-10", 20], ["8-9", 21],
            ],
          },
          axis_setup: { "0" => [["0-4", 11], ["18-22", 11], [22, "12-13"], ["*", "0-10"]] },
        }
      end

      def hexes
        [
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
          ],
          [
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 2, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4, 6] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 2, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4, 6] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 3, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4, 5] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 3, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [3, 5] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 3, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, r: { t: "t", d: [2, 4, 5] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 2, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 3] } },
            { t: "o", h: 2 },
          ],
          [
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "b", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 5] } },
            { t: "b", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 2 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 5] } },
            { t: "b", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", h: 1, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
          ],
          [
            { t: "d", d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o", r: { t: "t", d: [2, 4] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "s" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "s" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
        ]
      end
    end
  end
end
