# frozen_string_literal: true

module Scenarios
  class Scenario302 < Base
    ID = "302"
    NAME = "Counterattack!"
    ALLIES = ["usa"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"

    DATE = [1944, 8, 7].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_5_1,
        [2, :usa_leader_4_1],
        [8, :usa_rifle_s],
        [2, :usa_m1918_bar],
        :usa_m2_browning,
        [2, :usa_m1a1_bazooka],
        :usa_m2_mortar,
        :usa_radio_155mm,
        [3, :foxhole],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_5_1,
        :ger_leader_4_1,
        [6, :ger_ss_s],
        [2, :ger_mg_42],
        [2, :ger_sdkfz_250_1],
        [4, :ger_pzkpfw_iv_h_j],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_setup: 1,
          first_move: 2,
          date:,
          location: "Mortain, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "Operation Lüttich was the codename of the Nazi German
          counter-attack near Mortain in northwestern France during the Battle
          of Normandy.  Despite initial success against the defending U.S. VII
          Corps, the Germans were soon halted, and the Allies inflicted severe
          losses on the attacking troops, eventually destroying most of the
          tanks the Germans committed.",
          "Ordered by Hitler despite protests from the German commanders on
          the spot, there was little chance of the attack succeeding, and the
          concentration of their armoured reserves at the western end of the
          front in Normandy soon led to disaster, as they were outflanked to
          their south and the front to their east collapsed, resulting in many
          of the German troops in Normandy being trapped in the Falaise
          Pocket.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [1, 5, true],
          hexes:,
          layout:,
          allied_edge: "l",
          axis_edge: "r",
          victory_hexes: [
            [2, 4, 1], [2, 10, 1], [4, 8, 1], [8, 5, 1], [8, 18, 1],
          ],
          allied_setup: { "0" => [["0-8", "0-18"]] },
          axis_setup: { "0" => [["12-14", "*"], ["*", "20-22"]] },
        }
      end

      def hexes
        [
          [
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", b: "b", be: [1, 6] },
            { t: "o", b: "b", be: [4, 5] },
            { t: "g" },
            { t: "g", b: "b", be: [4, 5] },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o", b: "b", be: [4, 5] },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", b: "b", be: [1, 4, 5, 6] },
            { t: "g" },
            { t: "g", b: "b", be: [4, 5] },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", b: "b", be: [1, 2, 5, 6] },
            { t: "o", b: "b", be: [5, 6] },
            { t: "o", b: "b", be: [4, 5, 6] },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "g", b: "b", be: [1, 6] },
            { t: "g", b: "b", be: [4, 5] },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "g", b: "b", be: [4, 5] },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "x", s: "f" } },
          ], [
            { t: "o", r: { d: [1, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 4, 5, 6] },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g", b: "b", be: [1, 2, 5, 6] },
            { t: "g", b: "b", be: [5, 6] },
            { t: "g", b: "b", be: [4, 5, 6] },
            { t: "o" },
            { t: "o" },
            { t: "f", r: { d: [4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
          ], [
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "s" } },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", d: 2, st: { sh: "s" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 5, st: { sh: "s" } },
            { t: "o", r: { d: [3, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "s" } },
            { t: "o", d: 4, st: { sh: "s" } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "s" } },
            { t: "o", d: 4, st: { sh: "s" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", d: 5, st: { sh: "s" } },
            { t: "o", r: { d: [2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 2, 4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { d: [4, 6] } },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "s" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "s" } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { d: [2, 5] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f", r: { d: [3, 6] } },
            { t: "f" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o", d: 6, st: { sh: "s" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 6, st: { sh: "s" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "c" } },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "f", r: { d: [1, 3] } },
            { t: "f" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "d", d: 2 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "f" },
            { t: "o" },
            { t: "o", r: { d: [3, 5, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "f" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "f" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", b: "b", be: [3] },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [1] },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "b", be: [1] },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "b", be: [1] },
            { t: "d", d: 5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "g", b: "b", be: [1] },
            { t: "g" },
            { t: "g", b: "b", be: [3] },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "b", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f" },
            { t: "o" },
            { t: "o", b: "b", be: [3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [2] },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "s" } },
            { t: "o", d: 4, st: { sh: "s" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2, 3] },
            { t: "g", b: "b", be: [2, 3] },
            { t: "o", b: "b", be: [1, 2, 3] },
            { t: "o", b: "b", be: [2, 3] },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "b", be: [1] },
            { t: "f" },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "f", r: { d: [2, 5], t: "t" } },
            { t: "f" },
          ], [
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "b", be: [1, 2] },
            { t: "g" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "o" },
            { t: "o", b: "b", be: [1, 2] },
            { t: "f" },
            { t: "f", r: { d: [2, 5], t: "t" } },
          ],
        ]
      end
    end
  end
end
