# frozen_string_literal: true

module Scenarios
  class Scenario616 < Base
    ID = "616"
    NAME = "A Savage Ground"
    ALLIES = ["chi"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 6, 28].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :chi_leader_5_1,
        [2, :chi_leader_4_1],
        [10, :chi_regular_s],
        [2, :chi_type_triple_ten],
        [2, :chi_type_24_maxim],
        [4, :pillbox],
        [6, :wire],
        [4, :mines8],
        :sniper5,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_1,
        [3, :jap_leader_4_1],
        [14, :jap_b_division_s],
        [2, :jap_type_92_hmg],
        [4, :jap_type_99_lmg],
        [2, :jap_type_97_81mm],
        [2, :jap_70mm_type_92],
        [2, :jap_ft],
        [4, :jap_sc],
        :jap_radio_10cm,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Hengyang, China",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Hengyang was a ferocious battle fought between the
          Chinese and Japanese in Hengyang. Although the city fell, Japanese
          casualties far exceeded the total number of Chinese troops defending
          the city. It was once described as \"the most savage battle ever
          fought in the smallest battlefield with the greatest casualties in
          the military history of the world.\"  The savagery of the fighting
          was made worse by the heavy use of chemical weapons on the part of
          the Japanese during the battle.",
          "In the late 1930's, the Japanese occupation of major eastern cities
          such as Shanghai, Nanjing, and Wuhan forced China's industries to
          relocate inland. The government of Chiang Kai-shek chose Hengyang to
          be a light industry center, and by the beginning of 1944, both banks
          of the Xiang River for ten miles had been built up with mills and
          factories, and gave the city the nickname of \"Little Shanghai\". In
          addition, the American Flying Tigers were based out of a nearby
          airfield along the Lei River, making capturing the city a priority
          for the Japanese. The air power concentrated there also ended up
          playing a significant role in disrupting Japanese logistics and
          supply, helping the city hold out for a total of 47 days.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 4, true],
          hexes:,
          layout:,
          allied_dir: 6,
          axis_dir: 3,
          victory_hexes: [
            [5, 17, 1], [9, 17, 1], [17, 3, 1], [17, 9, 1], [17, 14, 1], [6, 9, 1], [10, 7, 1],
            [13, 9, 1], [10, 13, 1],
          ],
          allied_setup: { "0" => [["*", "0-18"]] },
          axis_setup: { "0" => [["*", "20-22"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 6], c: "l" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "y" },
            { t: "y" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 2.5, st: { sh: "l2", s: "f" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", d: 2.5, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 6], c: "l" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o", d: 2.5, st: { sh: "l2", s: "f" } },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 2.5, st: { sh: "l2", s: "f" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", d: 2.5, st: { sh: "l2", s: "f" } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 4], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 6], c: "l" } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2.5 },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "y" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "g" },
            { t: "o" },
            { t: "b", h: 1, b: "c", be: [3] },
            { t: "o", h: 1, b: "c", be: [2, 3] },
            { t: "b", h: 1, b: "c", be: [2] },
            { t: "o", h: 1 },
            { t: "o", h: 1, b: "c", be: [3] },
            { t: "o", h: 1, b: "c", be: [2, 3] },
            { t: "o", h: 1, b: "c", be: [2] },
            { t: "b" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 6] } },
            { t: "f" },
            { t: "b" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 5] } },
          ],
        ]
      end
    end
  end
end
