# frozen_string_literal: true

module Scenarios
  class Scenario210 < Base
    ID = "210"
    NAME = "Smash and Grab"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 7, 14].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [1, :uk_leader_6_2],
        [1, :uk_leader_5_1],
        [6, :uk_airborne_s],
        [3, :uk_bren_lmg],
        [1, :uk_elite_crew_t],
        [1, :uk_qf_6pdr_mk_iv],
        [1, :uk_engineer_s],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :ger_rifle_s],
        [2, :ger_mg_42],
      ] },
      "4": { list: [
        [2, :ger_pzkpfw_iii_n],
        [2, :ger_pzkpfw_iv_e],
        [1, :ger_pzkpfw_ii_luchs],
      ] },
      "5": { list: [
        [1, :ger_leader_5_1],
        [1, :ger_leader_4_1],
        [6, :ger_rifle_s],
        [2, :ger_mg_42],
        [1, :ger_8cm_grw_34],
        [1, :ger_sdkfz_251_1],
        [1, :ger_stug_iii_b_e],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Ponte Primosole, Catania, Sicily",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "Operation Fustian was an airborne operation and part of the Allied
          invasion of Sicily.  Also known as the Battle of Primosole Bridge,
          the operation was carried out by the 1st Parachute Brigade of the
          British 1st Airborne Division. The objective was the Primosole
          Bridge across the Simeto River. The intention was for the
          paratroopers, with glider-borne forces in support, to land on both
          sides of the river and then capture the bridge and secure the
          surrounding area until relieved by the British XIII Corps, which had
          landed on the southeastern coast of Sicily three days before.
          Because the bridge was the only crossing on the river, its capture
          was critical to the ultimate success of the invasion.",
          "Many of the aircraft carrying the paratroopers from North Africa
          were shot down or damaged by friendly fire and enemy action, the
          landings scattered the brigade over a large area and only the
          equivalent of two companies of troops were landed in the correct
          locations. Despite this and local resistance, the paratroops
          captured the bridge and held out against increasing attacks until
          nightfall. The relief force led by the 50th (Northumbrian) Infantry
          Division was short of transport and  were still a mile away when
          they halted for the night.  By this time, with casualties mounting
          and supplies running short, the British withdrew from the bridge.
          The following day the British units joined forces with the 9th
          Battalion, Durham Light Infantry, and with tank support attempted to
          recapture the bridge. The bridge was not finally secured until three
          days after the start of the operation when another battalion of the
          Durham Light Infantry, led by the paratroopers, established a
          bridgehead on the north bank of the river.",
          "The capture of Primosole Bridge did not lead to the expected rapid
          advance, as by this time the Germans had succeeded in establishing a
          defensive line. It was not until early the following month that
          Catania was captured.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 2, true],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [7, 10, 2], [7, 12, 2], [7, 14, 2], [3, 18, 2], [7, 8, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-1", 3], ["13-14", 3], ["0-1", 4], ["13-14", 4], ["0-1", 5], ["13-14", 5],
              ["0-1", 6], ["13-14", 6], ["0-1", 7], ["13-14", 7], ["0-1", 8], ["13-14", 8],
              ["0-1", 9], ["13-14", 9], ["0-1", 10], ["13-14", 10], ["0-1", 11], ["13-14", 11],
              ["0-1", 12], ["13-14", 12], ["0-1", 13], ["13-14", 13], ["0-1", 14], ["13-14", 14],
              ["0-1", 15], ["13-14", 15], ["0-1", 16], ["13-14", 16], ["0-1", 17], ["13-14", 17],
              ["0-1", 18], ["13-14", 18], ["0-1", 19], ["13-14", 19], ["*", "0-2"], ["*", "20-22"],
            ],
          },
          axis_setup: {
            "0" => [
              ["4-10", 7], ["4-10", 8], ["4-10", 9], ["4-10", 10], ["4-10", 11], ["4-10", 12],
              ["4-10", 13], ["4-10", 14], ["4-10", 15],
            ],
            "4" => [["*", 0]],
            "5" => [["*", 0]],
          },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2.5 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "d", d: 2.5 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "d", d: 2.5 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 2, 4], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w", s: { t: "s", d: [4, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 4] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "s2", s: "u" } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "d", d: 2 },
          ],
          [
            { t: "d", d: 2 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
          ],
        ]
      end
    end
  end
end
