# frozen_string_literal: true

module Scenarios
  class Scenario124 < Base
    ID = "124"
    NAME = "Over the Line"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 3, 20].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_6_1,
        [2, :uk_leader_5_1],
        [8, :uk_line_s],
        [4, :uk_bren_lmg],
        :uk_vickers_mg,
        :uk_ml_3inch_mortar,
      ] },
      "2": { list: [
        [4, :uk_churchill_iii_iv],
        [2, :uk_crusader_ii_cs],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_5_1,
        [5, :ger_rifle_s],
        [3, :ger_mg_42],
        [3, :ger_sdkfz_250_1],
        [4, :ger_pzkpfw_iii_n],
        [4, :ger_pzkpfw_iv_f2],
      ] },
    }.freeze

    INIT_ALLIED_UNITS = [
      { data: :wire, x: 7, y: 14, facing: 1 },
      { data: :wire, x: 6, y: 14, facing: 1 },
      { data: :wire, x: 5, y: 14, facing: 1 },
      { data: :wire, x: 8, y: 13, facing: 1 },
      { data: :wire, x: 9, y: 12, facing: 1 },
      { data: :wire, x: 10, y: 12, facing: 1 },
      { data: :wire, x: 13, y: 11, facing: 1 },
      { data: :wire, x: 14, y: 10, facing: 1 },
      { data: :wire, x: 15, y: 10, facing: 1 },
      { data: :wire, x: 3, y: 15, facing: 1 },
      { data: :wire, x: 2, y: 15, facing: 1 },
      { data: :wire, x: 2, y: 16, facing: 1 },
      { data: :wire, x: 16, y: 9, facing: 1 },
      { data: :wire, x: 17, y: 9, facing: 1 },
      { data: :wire, x: 18, y: 9, facing: 1 },
      { data: :wire, x: 21, y: 8, facing: 1 },
    ].freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Zarat, Tunesia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          init_allied_units:,
        }
      end

      def description
        [
          "Operation Pugilist began in the opening phases of the the Battle of
          the Mareth Line in Tunesia. The operation consisted of two parts, a
          frontal assault on the Mareth Line and a left hook through the
          Tebaga Gap meant to bypass the line. Both parts of the operation
          were largely unsuccessful, and during the attack on the line, only
          the 50th Northumbrian Infantry Division managed to penetrate the
          line where it was held by the 136th Giovani Fascisti Armored
          Division near Zarat, but rain and the nature of the terrain
          prevented the deployment of tanks or anti-tank guns and
          left the infantry isolated.",
          "Soon after, the 15th Panzer division and Giovani Fascisti Division
          counterattacked and captured much of the bridgehead controlled by
          the 50th Northumbrian Division.  Eventually all of the British attacking
          forces were recalled, but not before losing
          several hundred prisoners.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [2, "rain"],
          wind: [4, 4, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [8, 8, 1], [14, 4, 1], [8, 6, 1], [11, 4, 1], [11, 11, 1], [5, 4, 1], [13, 14, 1],
          ],
          allied_setup: {
            "0" => [
              ["2-22", "2-6"], ["2-19", 7], ["2-14", 8], ["2-12", 9], ["2-9", 10], ["2-7", 11],
              ["2-6", 12], ["2-3", 13],
            ],
            "2" => [["*", 22]],
          },
          axis_setup: { "0" => [["0-15", 0], [0, "1-10"]] },
          base_terrain: "d",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 3, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "r", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [2, 4, 6] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "t" },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 5] }, h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] }, h: 1 },
            { t: "o", h: 1 },
          ],
        ]
      end
    end
  end
end
