# frozen_string_literal: true

module Scenarios
  class Scenario044 < Base
    ID = "044"
    NAME = "False Hope"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 7, 6].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :ussr_leader_5_1],
        [4, :ussr_rifle_s],
        [3, :ussr_smg_s],
        :ussr_dshk,
        [2, :ussr_sg_43],
        [2, :ussr_82_pm_41],
        :ussr_120_pm_38,
        [4, :ussr_crew_t],
        [2, :ussr_76mm_f_22],
        [2, :ussr_45mm_m_42],
        :ussr_su_76m,
        :ussr_su_85,
        [20, :wire],
        [3, :mines10],
        [8, :trench],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_5_2,
        [2, :ger_leader_5_1],
        [9, :ger_rifle_s],
        [2, :ger_pionier_s],
        [6, :ger_mg_42],
        [2, :ger_sc],
        :ger_radio_15cm,
        :ger_pzkpfw_ii_flamm,
        :ger_tiger_i,
        [5, :ger_pzkpfw_iii_n],
        [2, :ger_pzkpfw_iv_g],
        :ger_stuh_42,
        :ger_sdkfz_251_16,
        [3, :ger_sdkfz_250_1],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 9,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Belgorod, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "In late spring of 1943, the Germans had prepared Operation Citadel
          in an attempt to envelope and destroy the Soviet forces in the Kursk
          salient. This would be achieved by attacking and breaking through
          the base of the salient from north and south simultaneously.
          However, the German offensive was delayed several times due to
          indecisive German leadership as the Germans waiting for additional
          forces and equipment, particularly for Tiger tanks it was hoped
          would give the Germans a decisive technical advantage (they would
          not. Even had they been reliable and available in numbers, no single
          weapon could have ever been decisive on its own).",
          "Because of this, the Soviet high command, Stavka, had learned of
          the German intentions and so used the delay to prepare a series of
          defensive belts along the routes of the planned German offensive.
          Once the battle started, this resulted in the northern attack being
          stopped cold; in the south, however, made slow but steady progress
          for a week until the Russians counterattacked, ending any chance of
          German success.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 6, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [18, 13, 1], [13, 4, 1], [2, 4, 1], [5, 9, 1], [9, 12, 1], [20, 4, 1], [3, 19, 2],
          ],
          allied_setup: {
            "0" => [
              ["6-22", 13], ["8-18", 14], ["*", "0-12"],
            ],
          },
          axis_setup: {
            "0" => [
              ["19-22", 15], ["17-22", 16], ["14-22", 17], ["0-9", 18], ["14-22", 18], ["0-10", 19],
              ["13-22", 19], ["*", "20-22"],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] }, h: -1 },
            { t: "o" },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 5] }, h: -1 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] }, s: { t: "s", d: [3, 6] }, h: -1 },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1, 2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 5] }, h: -1 },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
          ],
          [
            { t: "f" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "f" },
            { t: "o", s: { t: "s", d: [2, 5] }, h: -1 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", s: { t: "s", d: [2, 5] }, h: -1 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", b: "f", be: [2, 3] },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] }, r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o", rr: { d: [[2, 6]] } },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", h: -1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [5, 6] }, h: -1 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", rr: { d: [[3, 6]] }, s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1] },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [2, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", b: "f", be: [3] },
            { t: "o", b: "f", be: [1], h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] }, h: -1 },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[3, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 5] }, h: -1 },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] }, h: -1 },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] }, h: -1 },
            { t: "f" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [4, 6] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 4] }, h: -1 },
            { t: "o", s: { t: "s", d: [1, 3] }, h: -1 },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] }, h: -1 },
            { t: "f" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 6] }, h: -1 },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
