# frozen_string_literal: true

module Scenarios
  class Scenario427 < Base
    ID = "427"
    NAME = "Backhander"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1943, 12, 29].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :usa_leader_5_1],
        :usa_leader_4_1,
        [6, :usa_marine_rifle_s],
        [2, :usa_m1918_bar],
        :usa_m1919_browning,
        :usa_m2_browning,
        :usa_radio_155mm,
      ] },
      "2": { list: [
        :usa_leader_6_1,
        [3, :usa_marine_rifle_s],
        [2, :usa_m1918_bar],
        [3, :usa_m4_sherman],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :jap_leader_5_1],
        [5, :jap_b_division_s],
        [2, :jap_type_92_hmg],
        :jap_type_97_90mm,
        [2, :jap_crew_t],
        :jap_type_94_75mm,
        :jap_type_1_47mm,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Cape Gloucester, New Britain",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Cape Gloucester was fought between Japanese and
          Allied forces on the island of New Britain, Territory of New Guinea.
          Codenamed Operation Backhander, the US landing formed part of the
          wider Operation Cartwheel, the main Allied operation in the
          Southwest Pacific. The primary objective of Operation Backhander was
          to capture the two Japanese airfields near Cape Gloucester. It was
          the second landing the US 1st Marine Division had conducted during
          the war thus far, after Guadalcanal.",
          "The main landing came when US Marines landed on either side of the
          peninsula. The western landing force acted as a diversion and cut
          the coastal road near Tauali to restrict Japanese freedom of
          movement, while the main force — landing on the eastern side —
          advanced north towards the airfields. The advance met light
          resistance at first but was slowed by the swampy terrain which
          channeled the US troops onto a narrow coastal trail. A Japanese
          counterattack briefly slowed the advance, but the airfields had been
          captured by the marines within the week.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [1, "rain"],
          wind: [2, 2, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [9, 12, 2], [13, 11, 2], [7, 9, 2], [15, 14, 2], [4, 5, 2], [7, 11, 2], [2, 8, 2],
          ],
          allied_setup: { "0" => [["20-22", "*"]], "2" => [[22, "*"]] },
          axis_setup: { "0" => [["0-16", "*"]] },
        }
      end

      def hexes
        [
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y", s: { t: "s", d: [2, 6] } },
            { t: "y" },
            { t: "y" },
            { t: "j" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "y" },
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "y" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "y", s: { t: "s", d: [3, 6] } },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "y" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "p" },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "y" },
            { t: "y" },
            { t: "y" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", r: { t: "a", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "o" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "p" },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "p" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "y" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "a", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "p" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "p" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", r: { t: "a", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", r: { t: "a", d: [2, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "j" },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "p" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", r: { t: "a", d: [2, 5] } },
            { t: "o", st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] }, s: { t: "s", d: [3, 6] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "p" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "p" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", r: { t: "a", d: [2, 5] } },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] }, s: { t: "s", d: [3, 5] } },
            { t: "o", r: { t: "d", d: [1, 3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] }, s: { t: "s", d: [3, 5] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "p" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] }, s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o", r: { t: "a", d: [1, 4] } },
            { t: "o" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "h", s: "f" }, d: 1 },
            { t: "o" },
            { t: "p" },
            { t: "o", s: { t: "s", d: [2, 4] } },
            { t: "o", s: { t: "s", d: [1, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", s: { t: "s", d: [3, 5] } },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "p" },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 6] } },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", s: { t: "s", d: [4, 5] } },
            { t: "o", s: { t: "s", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", s: { t: "s", d: [3, 6] } },
            { t: "j" },
            { t: "o" },
          ],
          [
            { t: "j" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o" },
            { t: "p" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 6] } },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [3, 5] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [2, 5] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] }, h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [2, 5] } },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "p", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, s: { t: "s", d: [2, 5] } },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
          ],
        ]
      end
    end
  end
end
