# frozen_string_literal: true

module Scenarios
  class Scenario016 < Base
    ID = "016"
    NAME = "Red October"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.5"

    DATE = [1942, 10, 14].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_4_1,
        [2, :ussr_leader_3_1],
        [8, :ussr_militia_s],
        :ussr_pm_m1910,
        :ussr_dshk,
        [4, :ussr_mc],
        [3, :ussr_decoy_leader6],
        [8, :ussr_decoy_squad3_s],
        [2, :ussr_decoy_weapon2],
        [4, :ussr_decoy_weapon0],
        :sniper5,
      ] },
      "2": { list: [
        :ussr_leader_5_1,
        [4, :ussr_rifle_s],
        [2, :ussr_smg_s],
        [2, :ussr_sc],
        :ussr_decoy_leader6,
        [8, :ussr_decoy_squad4_s],
        [2, :ussr_decoy_weapon0],
      ] },
      "4": { list: [
        :ussr_leader_4_1,
        [4, :ussr_rifle_s],
        [4, :ussr_smg_s],
        [2, :ussr_sc],
        :ussr_decoy_leader6,
        [8, :ussr_decoy_squad4_s],
        [2, :ussr_decoy_weapon0],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_5_1,
        [3, :ger_leader_4_1],
        [2, :ger_pionier_s],
        [12, :ger_rifle_s],
        [4, :ger_sc],
        [5, :ger_mg_34],
        :ger_ft,
        :sniper5,
      ] },
      "3": { list: [
        :ger_leader_6_1,
        :ger_leader_4_1,
        [2, :ger_pionier_s],
        [8, :ger_rifle_s],
        [4, :ger_sc],
        :ger_ft,
        [4, :ger_mg_34],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Stalingrad, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["allied_hidden_units"],
        }
      end

      def description
        [
          "After slowly advancing against strong Soviet resistance, the
          fighting shifted north to the industrial district where the Germans
          now faced the three giant factories of Stalingrad: the Stalingrad
          Tractor Factory, the Barrikady Arms Factory, and the Red October
          Steel Factory.  It took a few days for them to prepare for the most
          biggest offensive yet.  Exceptionally intense shelling and bombing
          preceded the first German assault groups; General Chuikov considered
          this to be the worst day of the battle.",
          "The German onslaught crushed the 37th Guards Rifle Division and in
          the afternoon the forward assault group reached the tractor factory
          before arriving at the Volga River, splitting the 62nd Army into
          two. In response to the German breakthrough to the Volga, the front
          headquarters committed three battalions from the 300th Rifle
          Division and the 45th Rifle Division, a substantial force of over
          2,000 men, to the fighting at the Red October Factory.",
          "The fighting in the Red October Plant went on for weeks, it had
          become a hell of shell and mortar fire, tank and air attacks, and
          hand-to-hand fighting where they fought for a workshop or half a
          workshop or for the end of a drain pipe.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 4, true],
          hexes:,
          layout:,
          allied_dir: 1.5,
          axis_dir: 4.5,
          victory_hexes: [
            [6, 8, 1], [8, 3, 1], [3, 13, 1], [9, 14, 1], [12, 7, 1], [7, 19, 1], [2, 5, 2],
          ],
          allied_setup: {
            "0" => [
              ["8-14", 0], ["7-14", "1-2"], ["6-14", "3-4"], ["5-14", "5-6"], ["4-14", "7-8"],
              ["3-14", "9-10"], ["2-14", "11-12"], ["1-14", "13-14"], ["*", "15-22"],
            ],
            "2" => [[14, "*"], ["10-13", 22]],
            "4" => [[14, "*"], ["10-13", 22]],
          },
          axis_setup: {
            "0" => [
              ["0-6", 0], ["0-5", "1-2"], ["0-4", "3-4"], ["0-3", "5-6"], ["0-2", "7-8"],
              ["0-1", "9-10"], [0, "11-12"],
            ],
            "3" => [[0, "0-8"]],
          },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "b" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "x" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "x" },
            { t: "x" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "b" },
            { t: "c" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "c" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
          ],
          [
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
            { t: "x" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [1, 4, 5], c: "r", r: 2 } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
          ],
          [
            { t: "o" },
            { t: "c" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "m2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
          ],
          [
            { t: "o" },
            { t: "c" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "x" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
          ],
          [
            { t: "b" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "c" },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "b" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "c" },
            { t: "o", st: { sh: "m2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "x" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 3 },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "x" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
          ],
          [
            { t: "o" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "c" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 6 },
          ],
          [
            { t: "o" },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "m2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 6 },
          ],
          [
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[6, 3]] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 6 },
          ],
          [
            { t: "o", rr: { d: [[6, 3], [6, 4]] } },
            { t: "x" },
            { t: "x" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 6 },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bic2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
          ],
          [
            { t: "x" },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [1, 3, 4], c: "r", r: 2 } },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "x" },
            { t: "x" },
            { t: "o" },
          ],
          [
            { t: "x" },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "x" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [1, 4, 6], c: "l", r: 2 } },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 6 },
            { t: "x" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 6 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l", r: 2 } },
            { t: "o", r: { t: "t", d: [3, 5], c: "r", r: 2 } },
            { t: "o" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 3 },
          ],
          [
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6], c: "l", r: 2 } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
          ],
          [
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "x" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
          ],
          [
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "c" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "x" },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
          ],
          [
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "x" },
            { t: "x" },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 6 },
          ],
        ]
      end
    end
  end
end
