# frozen_string_literal: true

module Scenarios
  class Scenario029 < Base
    ID = "029"
    NAME = "Italians on the Don"
    ALLIES = ["ussr"].freeze
    AXIS = ["ita"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 8, 4].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_4_1,
        :ussr_leader_3_1,
        [4, :ussr_rifle_s],
        :ussr_pm_m1910,
        :ussr_82_bm_37,
        :ussr_crew_t,
        :ussr_76mm_zis_3,
        :ussr_t_34_m41,
        [2, :foxhole],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :ita_leader_5_1],
        :ita_leader_4_1,
        [6, :ita_bersaglieri_s],
        :ita_elite_crew_t,
        :ita_breda_m37,
        [2, :ita_breda_30],
        :ita_81_14_m35,
        :ita_radio_75mm,
        :ita_cannone_da_75_46,
        [2, :ita_l6_40],
        [2, :ita_semovente_da_47_32],
        :ita_semovente_da_75_18,
        [2, :foxhole],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Serafimovich, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "When Benito Mussolini became aware of Adolf Hitler's intention to
          invade Russia a few months before the beginning of Operation
          Barbarossa, he committed the Italians to participate in the
          invasion. However, that commitment was only confirmed on the same
          day of the invasion, when the Italian dictator was informed that the
          operation had begun.",
          "Nonetheless, an expeditionary force was quickly made operational
          with three divisions. The Italian Expeditionary Corps in Russia
          (Corpo di Spedizione Italiano in Russia, CSIR) arrived on the
          eastern front in mid-July 1941. Initially integrated into the 11th
          German Army and then in the 1st Panzer Army, the CSIR participated
          in the campaign until April 1942, when two more Italian corps
          (together with the CSIR) were formed into the 8th Italian Army or
          Italian Army in Russia (Armata Italiana in Russia, ARMIR). Deployed
          in the Don river sector in the south, the 8th Italian Army together
          with the 2nd Hungarian Army and the 3rd Romanian Army were assigned
          to cover the left flank of the German forces advancing towards
          Stalingrad.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 3, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [7, 3, 1], [9, 7, 1], [8, 16, 1], [11, 10, 1], [7, 10, 1],
          ],
          allied_setup: {
            "0" => [
              ["4-14", "6-7"], ["5-14", "8-9"], ["6-14", "10-11"], ["7-14", 12], ["*", "0-5"],
            ],
          },
          axis_setup: {
            "0" => [
              [0, 9], ["0-1", 10], [0, 11], ["0-1", "12-13"], ["0-2", "14-15"], ["0-3", "16-17"],
              ["0-4", "18-19"], ["*", "20-22"],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 2 },
            { t: "d", h: 1, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 2 },
            { t: "d", h: 1, d: 2 },
            { t: "o", r: { t: "d", d: [2, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 4 },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 4 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 2, 4, 5] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 4 },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o" },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 2 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1, st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "d", h: 1, d: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "d", h: 1, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 2, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 3] }, h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "f", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 4, 5] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 3] }, h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
