# frozen_string_literal: true

module Scenarios
  class Scenario122 < Base
    ID = "122"
    NAME = "Ironclad"
    ALLIES = ["uk"].freeze
    AXIS = ["vcf"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 5, 6].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_5_1,
        [4, :uk_leader_4_1],
        [3, :uk_commando_s],
        [7, :uk_line_s],
        [5, :uk_bren_lmg],
        :uk_2inch_mortar,
        [2, :uk_valentine_i_vii],
        [2, :uk_tetrarch],
        [2, :uk_vickers_mg],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :vcf_leader_4_1],
        [6, :vcf_colonial_s],
        [2, :vcf_crew_t],
        [2, :vcf_75mm_m1897],
        [4, :vcf_m1915_hotchkiss],
      ] },
    }.freeze

    INIT_AXIS_UNITS = [
      { data: :pillbox, x: 7, y: 8, facing: 5 },
      { data: :pillbox, x: 10, y: 11, facing: 5 },
      { data: :pillbox, x: 12, y: 11, facing: 6 },
      { data: :pillbox, x: 16, y: 12, facing: 6 },
    ].freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Antsiranana, Madagascar",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          init_axis_units:,
        }
      end

      def description
        [
          "The Battle of Madagascar was an Allied campaign to capture the
          Vichy French-controlled island Madagascar. The seizure of the island
          by the British was to deny Madagascar's ports to the Imperial
          Japanese Navy and to prevent the loss or impairment of the Allied
          shipping routes to India, Australia and Southeast Asia. It began
          with Operation Ironclad, the seizure of the port of Diego-Suarez
          near the northern tip of the island.",
          "The initial beach landings met with virtually no resistance and
          these troops seized Vichy coastal batteries and barracks. The
          Courier Bay force, the British 17th Infantry Brigade, after toiling
          through mangrove swamp and thick bush, took the town of Diego-Suarez
          and captured a hundred prisoners. The Ambararata Bay force, the 29th
          Independent Brigade, headed towards the French naval base of
          Antisarane. With assistance from Valentine infantry tanks and
          Tetrarch light tanks, they advanced 21 miles, overcoming light
          resistance with bayonet charges. Antisarane was elaborately defended
          with trenches and pillboxes, and flanked on both sides by
          impenetrable swamps.",
          "The British were surprised by the strength of the French defenses,
          known as the Joffre line, and were greatly surprised at the level of
          resistance. An initial frontal assault failed, and
          by the end of the day, fierce resistance had resulted in the
          destruction of almost all of British tanks. Another assault by the
          South Lancashires worked its way around the Vichy defenses but the
          swamps and bad terrain broke it up; it managed to get behind the
          Vichy line and caused chaos but was eventually forced to withdraw.
          Finally, the old destroyer HMS Anthony broke the deadlock when it
          dashed straight past the Antisarane harbour defenses and landed
          fifty Royal Marines into the Vichy rear. The 17th Infantry Brigade
          then broke through and was soon in the town. Antisarane surrendered
          that evening.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 2, false],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [12, 13, 2], [10, 9, 2], [11, 5, 2], [14, 9, 2], [9, 7, 2], [5, 4, 2], [17, 8, 2],
          ],
          allied_setup: {
            "0" => [
              ["6-22", 8], ["8-22", 9], ["9-22", 10], ["10-22", 11], ["13-22", 12], ["*", "0-7"],
            ],
          },
          axis_setup: { "0" => [["*", "14-22"]] },
        }
      end

      def hexes
        [
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4, 6] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "s" },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
          ],
          [
            { t: "s" },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "s" },
          ],
          [
            { t: "w" },
            { t: "s" },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "d", h: 2, d: 1 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 2, st: { sh: "m2", s: "f" }, d: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
          ],
          [
            { t: "w" },
            { t: "s" },
            { t: "j", h: 1 },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, s: { t: "t", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 5 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 3 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "m2", s: "f" }, d: 3 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "s" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "m" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, s: { t: "t", d: [1, 5] } },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3, 5] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 4 },
            { t: "d", h: 2, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2, st: { sh: "m2", s: "f" }, d: 3 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 6 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "s" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "m" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4, 5] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 5] } },
            { t: "o", h: 2, st: { sh: "s2", s: "f" }, d: 6 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "m" },
            { t: "s" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, s: { t: "t", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "s" },
            { t: "m" },
            { t: "w" },
          ],
          [
            { t: "w", s: { t: "s", d: [2, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "s" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, s: { t: "t", d: [1, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "m" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "m", s: { t: "s", d: [2, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "s" },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2, s: { t: "t", d: [2, 4] } },
            { t: "o", h: 2, s: { t: "t", d: [1, 4] } },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "m" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "m" },
            { t: "m", s: { t: "s", d: [2, 6] } },
            { t: "m" },
            { t: "s" },
            { t: "s" },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "m" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "m" },
            { t: "m", s: { t: "s", d: [3, 6] } },
            { t: "m" },
            { t: "m" },
            { t: "s" },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "m" },
            { t: "m" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "m", s: { t: "s", d: [3, 5] } },
            { t: "m", s: { t: "s", d: [4, 6] } },
            { t: "m", s: { t: "s", d: [1, 5] } },
            { t: "m" },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "m" },
            { t: "m" },
            { t: "m" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "m" },
            { t: "m", s: { t: "s", d: [2, 3] } },
            { t: "m", s: { t: "s", d: [4, 5] } },
            { t: "m", s: { t: "s", d: [1, 2] } },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "m" },
            { t: "m" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "m" },
            { t: "m" },
            { t: "m", s: { t: "s", d: [2, 6] } },
            { t: "m" },
            { t: "m" },
            { t: "o", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "m" },
            { t: "m" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", h: 1 },
            { t: "m" },
            { t: "m", s: { t: "s", d: [3, 5] } },
            { t: "m" },
            { t: "m" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "m" },
            { t: "w" },
          ],
          [
            { t: "j", h: 1 },
            { t: "o" },
            { t: "m", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "s" },
            { t: "w" },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "j" },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "j" },
            { t: "j" },
            { t: "s" },
          ],
          [
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [3, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "m" },
            { t: "m" },
            { t: "s" },
          ],
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", s: { t: "s", d: [2, 5] } },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "m" },
            { t: "m" },
          ],
        ]
      end
    end
  end
end
