# frozen_string_literal: true

module Scenarios
  class Scenario504 < Base
    ID = "504"
    NAME = "Mixing It Up"
    ALLIES = ["fra"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"

    DATE = [1940, 5, 14].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :fra_leader_5_1,
        :fra_leader_4_1,
        [6, :fra_reservist_s],
        [2, :fra_crew_t],
        [2, :fra_fm_24_29],
        [2, :fra_75mm_m1897],
        :fra_radio_105mm,
        [2, :fra_char_b1],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_5_2,
        [2, :ger_leader_5_1],
        [9, :ger_rifle_s],
        :ger_elite_crew_t,
        [2, :ger_mg_34],
        :ger_8cm_grw_34,
        :ger_3_7cm_pak_36,
      ] },
      "2": { list: [
        :ger_leader_5_1,
        [2, :ger_rifle_s],
        :ger_elite_crew_t,
        :ger_mg_34,
        :ger_3_7cm_pak_36,
      ] },
      "4": { list: [
        :ger_elite_crew_t,
        :ger_3_7cm_pak_36,
      ] },
      "6": { list: [
        :ger_leader_4_1,
        [2, :ger_rifle_s],
        :ger_mg_34,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_setup: 1,
          first_move: 2,
          date:,
          location: "Thelonne, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "After Sedan fell, fighting continued to the south as the Germans
          continued to advance.  Mixed in with the French infantry were some
          smaller units of French tanks which the Germans had some trouble
          dealing with, having only smaller 3.7cm PaK 36 anti-tank guns
          available at first. However, the French tanks did not have radios,
          and were poorly coordinated with the infantry, and since French
          doctrine did not consider their tanks to be an offensive-oriented
          weapon, they were also quite slow.  The real problem for the
          Germans, though, was French artillery; the Germans, not having
          mobile artillery available had left theirs behind and depended on
          air support instead.  While effective, there was less weight of air
          support available than artillery may have been able to supply, and
          it was concentrated on the most critical targets.",
          "Nonetheless, the infantry of the German Armored fighting formations
          that were the spearhead of the advance were mobile infantry, which
          allowed them to concentrate forces at the point of attack, something
          the French in turn could not easily counter one their defensive
          lines were breached and they were forced onto the defensive
          piecemeal.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [1, 6, true],
          hexes:,
          layout:,
          allied_edge: "b",
          axis_edge: "t",
          victory_hexes: [
            [3, 3, 2], [6, 6, 2], [8, 4, 2], [10, 9, 1], [12, 10, 1], [8, 13, 1], [9, 15, 1],
            [11, 18, 1], [5, 21, 1],
          ],
          allied_setup: {
            "0" => [["*", "9-22"]],
          },
          axis_setup: {
            "0" => [["*", "0-7"]],
            "2" => [[0, "0-3"], ["*", 0]],
            "4" => [[0, "0-3"], ["*", 0]],
            "6" => [[0, "0-3"], ["*", 0]],
          },
          base_terrain: "g",
        }
      end

      def hexes
        [
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [4, 6], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g", b: "f", be: [2, 3] },
            { t: "g", b: "f", be: [2, 3] },
            { t: "g", b: "f", be: [2] },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { d: [2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 5], t: "t" } },
            { t: "o", d: 2, st: { sh: "l" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
          ], [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o", r: { d: [2, 4, 6], t: "t" } },
            { t: "o", r: { d: [1, 3, 4], t: "t" } },
            { t: "o", r: { d: [1, 4, 5], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 5], t: "t" } },
            { t: "g" },
            { t: "g" },
          ], [
            { t: "o" },
            { t: "o", r: { d: [4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3], t: "t" } },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
          ], [
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o", d: 1, st: { sh: "l" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 4], t: "t" } },
            { t: "o", r: { d: [1, 3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "l" } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "s" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 6, st: { sh: "l" } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 6, st: { sh: "s" } },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "s" } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "l" } },
            { t: "o", r: { d: [3, 5, 6], t: "t" } },
            { t: "o", d: 6, st: { sh: "s" } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "g" },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o", d: 3, st: { sh: "l" } },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "f", be: [3, 4] },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
          ], [
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 5], t: "t" }, b: "f", be: [3, 4] },
            { t: "o" },
            { t: "o" },
            { t: "g" },
          ], [
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [2, 6], t: "t" }, b: "f", be: [3, 4] },
            { t: "o" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", d: 3, st: { sh: "x" } },
            { t: "o", b: "f", be: [3] },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { d: [3, 6], t: "t" } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
        ]
      end
    end
  end
end
