# frozen_string_literal: true

module Scenarios
  class Scenario024 < Base
    ID = "024"
    NAME = "Karelian Crossroads"
    ALLIES = ["ussr"].freeze
    AXIS = ["fin"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1941, 9, 8].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :ussr_leader_4_1],
        [7, :ussr_rifle_s],
        [2, :ussr_pm_m1910],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :fin_leader_6_1,
        :fin_leader_5_1,
        :fin_leader_4_1,
        [5, :fin_regular_s],
        [2, :fin_ls_26],
        :fin_mg_08_15,
        :fin_81mm_tampella,
        [2, :fin_elite_s],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Pryazha, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Finnish invasion of East Karelia was part of the Continuation
          War. For over a month after the outbreak of the Continuation war,
          the Finnish Karelian Army reinforced and prepared while Soviet
          encirclements near Lake Ladoga and the invation of the Karelian
          Isthmus were resoved; once that was finished, the Finns began to
          advance against Soviet fortifications and troops that had been
          brought to the front and prepared to resist the Finnish invasion.
          The objective of the attack was to occupy all of East Karelia, once
          that was complete, the Finns stopped advancing and held their
          positions until the Soviets counter-invaded in 1944.",
          "The Finnish advance towards Pryazha met strong Soviet resistance
          but they were able to advance through the forests and encircle the
          defending Soviets. However, the advance was slow, and it took until
          September 5 before the road leading to Petrozavodsk was cut by the
          Finnish forces. Encircled Soviet units made repeated counterattacks
          against the Finnish roadblock but failed to clear it. Steadily
          advancing, the Finns finally captured Pryazha on September 8.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 3, false],
          hexes:,
          layout:,
          allied_dir: 1,
          axis_dir: 4,
          victory_hexes: [
            [7, 3, 1], [7, 8, 1], [10, 20, 1], [12, 11, 1], [13, 16, 1], [13, 4, 1], [8, 15, 1],
          ],
          allied_setup: {
            "0" => [
              ["8-14", 0], ["7-14", "1-2"], ["6-14", 3], ["7-14", "4-6"], ["6-14", "6-11"],
              ["7-14", "12-13"], ["8-14", 14], ["7-14", 15], ["8-14", "16-17"], ["9-14", 18],
              ["8-14", 19], ["9-14", "20-21"], ["10-14", 22],
            ],
          },
          axis_setup: {
            "0" => [
              ["0-6", 0], ["0-5", "1-2"], ["0-4", 3], ["0-5", "4-6"], ["0-4", "7-11"],
              ["0-5", "12-13"], ["0-6", 14], ["0-5", 15], ["0-6", "16-17"], ["0-7", 18],
              ["0-6", 19], ["0-7", "20-21"], ["0-8", 22],
            ],
          },
        }
      end

      def hexes
        [
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 5] } },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 6 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 6] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 6 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s", s: "f" }, d: 2 },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 5 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 3, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [2, 6] } },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "m", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s", s: "f" }, d: 6 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "w" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ],
        ]
      end
    end
  end
end
