# frozen_string_literal: true

module Scenarios
  class Scenario322 < Base
    ID = "322"
    NAME = "Verrières Ridge"
    ALLIES = ["can"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 7, 20].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        [2, :uk_leader_5_1],
        [2, :uk_leader_4_1],
        [10, :uk_line_s],
        [5, :uk_bren_lmg],
        :uk_vickers_mg,
        :uk_radio_152mm,
        [3, :uk_m4_sherman],
        [3, :uk_m10_achilles],
        [2, :uk_m5_half_track],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_4_1,
        [6, :ger_ss_s],
        [3, :ger_mg_42],
        :ger_8cm_grw_34,
        :ger_panzerfaust,
        :ger_panzerschreck,
        :ger_radio_15cm,
        :ger_sdkfz_166,
        :ger_marder_iii_h_m,
        [4, :wire],
        [2, :mines10],
        [4, :trench],
      ] },
      "2": { list: [
        :ger_leader_5_1,
        [2, :ger_ss_s],
        :ger_mg_42,
        [3, :ger_panther_a_g],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 5,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Caen, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "On the opening morning of Operation Atlantic, advance elements of
          the 3rd Canadian Infantry Division were able to capture Colombelles
          and Faubourg-de-Vaucelles, a series of industrial suburbs just south
          of Caen along the Orne River. Additional Battalions from 5th Brigade
          managed to push southward to Saint-André-sur-Orne. With the east
          bank of the Orne River secured, the 4th and 6th Canadian Infantry
          Brigades moved into position for the assault on Verrières Ridge.",
          "The German High Command had not missed the strategic importance of
          the ridge. Though nowhere more than 90 feet high, it dominated the
          Caen–Falaise road, blocking Allied forces from breaking out into the
          open country south of Caen. Canadian troops in Saint-André-sur-Orne
          were soon pinned down by German infantry and tanks. A direct attack
          up the slopes of Verrières Ridge fell apart as heavy rain prevented
          air support and turned the ground to muck, making it difficult for
          tanks to maneuver. Counterattacks by two Panzer divisions forced the
          Candadians back past their start line and crashed into a supporting
          British battalion, who lost over 300 men as they struggled to hold
          back the 1st SS Panzer Division. By the end of the day, the ridge
          was still in enemy hands despite heavy Canadian casualties.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [3, "rain"],
          wind: [1, 3, false],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [8, 4, 2], [9, 17, 2], [11, 17, 2], [4, 17, 2], [5, 15, 2], [6, 10, 2], [16, 17, 1],
          ],
          allied_setup: {
            "0" => [
              ["14-22", 3], ["15-22", "4-5"], ["16-22", "6-7"], ["17-22", 8], ["16-22", 9],
              ["17-22", "10-11"], ["18-22", "12-14"], ["17-22", "15-16"], ["16-22", "17-18"],
              ["15-22", "19-20"], ["14-22", "21-22"], ["*", "0-2"],
            ],
          },
          axis_setup: {
            "0" => [
              ["0-11", 4], ["0-10", 5], ["0-11", "6-12"], ["0-10", "13-16"], ["0-9", "17-18"],
              ["0-8", "19-22"],
            ],
            "2" => [[0, "16-21"], ["0-4", 22]],
          },
        }
      end

      def hexes
        [
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 2, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 2, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 1, r: { t: "t", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 3, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "t", d: [1, 4, 5] } },
            { t: "o", h: 3, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 3, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 2, 4, 6] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4, 6] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 3, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [2, 5] } },
            { t: "o", h: 3, st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "o", h: 1, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [2, 4] } },
            { t: "o", h: 3, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 3, 4, 6] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 3] } },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "w" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 2 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
          ],
          [
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "f" },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 5] } },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [2, 6] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 5] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [2, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 4] } },
          ],
          [
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 3, d: 3, st: { sh: "l", s: "u" } },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
          ],
          [
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "g", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 5] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [2, 4, 6] } },
            { t: "o", h: 3, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "t", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "w", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "w" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "u" }, d: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "o", st: { sh: "l", s: "u" }, d: 3 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3, r: { t: "t", d: [3, 6] } },
            { t: "d", h: 3, d: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
