# frozen_string_literal: true

module Scenarios
  class Scenario021 < Base
    ID = "021"
    NAME = "The Last Spring"
    ALLIES = ["ussr"].freeze
    AXIS = ["cro"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 5, 20].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_4_1,
        :ussr_leader_3_1,
        [5, :ussr_rifle_s],
        :ussr_dp_27,
        :ussr_pm_m1910,
        :ussr_82_pm_41,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [2, :axm_leader_4_1],
        [7, :axm_regular_s],
        [2, :axm_mg_34],
        :axm_81mm_mortar,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 6,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Lozovaya, Ukraine",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The 369th (Croatian) Reinforced Infantry Regiment, often referred
          to as the Croatian Legion, was a regiment of the German Army raised
          to fight on the Eastern Front. Formed in July 1941 by Croatian
          volunteers from the Independent State of Croatia, a German puppet
          formed after the fall of Yugoslavia. It also included a Bosniak
          battalion. The regiment fought in a number of battles, including in
          brutal conditions during the winter of 1941, and in the Second
          Battle of Kharkov, before finally fighting and ultimately being
          annihilated during the battle of Stalingrad.",
          "During the 2nd Kharkov, the regiment was involved in the final
          phases of the pincer attack on the Red Army bridgehead as part of
          the 100th Jäger Division, 17th Army.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 4, false],
          hexes:,
          layout:,
          allied_dir: 6,
          axis_dir: 3,
          victory_hexes: [
            [8, 4, 1], [12, 10, 1], [2, 8, 1], [8, 10, 1], [3, 14, 1],
          ],
          allied_setup: {
            "0" => [["1-14", 8], ["1-14", 9], ["4-14", 10], ["5-14", 11], ["*", "0-7"]],
          },
          axis_setup: { "0" => [["8-14", 17], ["*", "18-22"]] },
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
          ],
          [
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4, 6] } },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "w" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l", s: "f" }, d: 1 },
            { t: "o" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", st: { sh: "l", s: "f" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "b" },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", r: { t: "d", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
