# frozen_string_literal: true

module Scenarios
  class Scenario405 < Base
    ID = "405"
    NAME = "A Stonne Place"
    ALLIES = ["fra"].freeze
    AXIS = ["ger"].freeze
    STATUS = "a"

    class << self
      def generate
        {
          turns: 6,
          first_setup: 2,
          first_move: 1,
          date: [1940, 5, 15],
          location: "Stonne, France",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "
          As the initial German armored spearhead advanced into France, the
          French forces counter-attacked with tank formations of their own.
          Contrary to popular history, the French had more and tougher tanks
          than the Germans, where they came short was in doctrine and the fact
          that the doctrine called for tanks to be used in a defensive role,
          so they were also very slow.  Having the advantage of faster tanks
          and radios, and also concentrated their armored formations, the
          Germans still managed to destroy numerous French tank formations,
          though often at a heavy cost.
          ",
          "
          After Sedan fell, the Germans turned their attention to the
          northwest to drive towards the English Channel, and the French
          counter-attacked from the south at Stonne to try and take the high
          ground and threaten the German's advances.  The Germans couldn't
          allow this to happen, and what resulted was a vicious two-day battle
          where they faced the French Char B1 bis tank for the only time.
          ",
          "
          Ultimately the French attack was unsuccessful and the failure to
          eliminate the Sedan bridgeheads resulted in the Germans cutting off
          large parts of the French army and the entire British Expeditionary
          Force which then was forced to evacuate at Dunkirk.
          ",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [1, 5, true],
          hexes:,
          layout: [15, 23, "x"],
          allied_edge: "b",
          axis_edge: "t",
          victory_hexes: [
            [5, 1, 2], [7, 4, 2], [10, 4, 2], [8, 6, 2], [12, 7, 2], [10, 10, 2], [6, 18, 1],
          ],
          allied_setup: {
            "0" => [["*", "11-23"]],
          },
          axis_setup: {
            "0" => [
              ["2-14", "0-1"], ["3-14", "2-3"], ["4-14", "4-5"], ["5-14", "6-7"], ["6-14", "8-9"],
            ],
          },
          base_terrain: "g",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "o", r: { d: [2, 4], t: "t" } },
            { t: "o", r: { d: [1, 4, 6], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
            { t: "o", r: { d: [1, 4], t: "t" } },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1, r: { d: [3, 5], t: "t" } },
            { t: "f", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
            { t: "o" },
          ], [
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "f", h: 2 },
            { t: "f", h: 1 },
            { t: "f", h: 1, r: { d: [2, 4], t: "t" } },
            { t: "f", h: 1, r: { d: [1, 4], t: "t" } },
            { t: "f", h: 1, r: { d: [1, 4], t: "t" } },
            { t: "o", h: 1, r: { d: [1, 4], t: "t" } },
            { t: "f", h: 1, r: { d: [1, 4], t: "t" } },
            { t: "f", h: 1, r: { d: [1, 4], t: "t" } },
            { t: "f", h: 1, r: { d: [1, 5], t: "t" } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
          ], [
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, d: 3, st: { sh: "l" } },
            { t: "o", h: 2 },
            { t: "o", h: 2, d: 1, st: { sh: "s" } },
            { t: "o", h: 2, d: 4, st: { sh: "s" } },
            { t: "o", h: 2 },
            { t: "f", h: 1, r: { d: [2, 6], t: "t" } },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, d: 3, st: { sh: "l" } },
            { t: "o", h: 2, r: { d: [4, 6], t: "t" } },
            { t: "o", h: 2, r: { d: [1, 4], t: "t" } },
            { t: "o", h: 2, r: { d: [1, 4], t: "t" } },
            { t: "o", h: 2, r: { d: [1, 4, 5], t: "t" } },
            { t: "o", h: 2, r: { d: [1, 3], t: "t" } },
            { t: "f", h: 1 },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2, d: 5, st: { sh: "x" } },
            { t: "o", h: 2 },
            { t: "o", h: 2, d: 5, st: { sh: "l" } },
            { t: "o", h: 2, r: { d: [2, 5], t: "t" } },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "f" },
          ], [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2, b: "f", be: [2, 3] },
            { t: "o", h: 2, b: "f", be: [2, 3] },
            { t: "o", h: 2, b: "f", be: [2, 3] },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2, r: { d: [2, 6], t: "t" } },
            { t: "o", h: 2, d: 5, st: { sh: "l" } },
            { t: "b", h: 1 },
            { t: "o" },
          ], [
            { t: "o", h: 3 },
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "o" },
          ], [
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "d", d: 3, h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f", h: 3 },
            { t: "f", h: 3 },
            { t: "g", h: 2, b: "f", be: [2, 3] },
            { t: "g", h: 2, b: "f", be: [2, 3] },
            { t: "g", h: 2, b: "f", be: [2, 3] },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [3, 5, 6], t: "t" } },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f", h: 3 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "f", h: 3 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "g", h: 2, b: "f", be: [2, 3] },
            { t: "g", h: 2, b: "f", be: [2, 3] },
            { t: "g", h: 2, b: "f", be: [2, 3] },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, d: 1, st: { sh: "c" } },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
            { t: "f" },
            { t: "f" },
          ], [
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
            { t: "o" },
            { t: "o" },
          ], [
            { t: "g", h: 2, b: "f", be: [2, 3] },
            { t: "g", h: 2, b: "f", be: [2, 3] },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
            { t: "o" },
          ], [
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
            { t: "o" },
          ], [
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [3, 5], t: "t" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
          ], [
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [2, 5], t: "t" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1, r: { d: [2, 5], t: "t" } },
          ], [
            { t: "o", h: 2, r: { d: [3, 6], t: "t" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [2, 5], t: "t" } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [2, 5], t: "t" } },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "f", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "g", h: 2 },
            { t: "o", h: 2, r: { d: [2, 5], t: "t" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
          ],
        ]
      end

      def allied_units
        {
          "0": { list: [
            :fra_leader_5_2,
            [2, :fra_leader_5_1],
            [2, :fra_bar_s],
            [4, :fra_reservist_s],
            [2, :fra_fm_24_29],
            [6, :fra_char_b1_bis],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
        }
      end

      def axis_units
        {
          "0": { list: [
            :ger_leader_6_2,
            :ger_leader_5_1,
            [4, :ger_rifle_s],
            [2, :ger_elite_crew_t],
            [2, :ger_mg_34],
            [2, :ger_3_7cm_pak_36],
            [3, :ger_pzkpfw_ii_a_e],
            [3, :ger_pzkpfw_iii__39],
          ].map { |u| Utility::Scenarios::Units.unit_definition(u) } },
        }
      end
    end
  end
end
