# frozen_string_literal: true

module Scenarios
  class Scenario415 < Base
    ID = "415"
    NAME = "Death Valley"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1944, 6, 22].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_5_1,
        [2, :usa_leader_4_1],
        [8, :usa_rifle_s],
        [3, :usa_m1918_bar],
        :usa_radio_155mm,
        :usa_ft,
        :usa_m4105_sherman,
        [2, :usa_sc],
      ] },
      "2": { list: [
        :usa_leader_5_1,
        :usa_leader_4_1,
        [2, :usa_engineer_s],
        [2, :usa_rifle_s],
        :usa_ft,
        :usa_sc,
        [2, :usa_m3a1_stuart_ft],
      ] },
      "3": { list: [
        :usa_leader_4_1,
        [3, :usa_rifle_s],
        :usa_ft,
        [2, :usa_sc],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_4_1,
        [8, :jap_a_division_s],
        :jap_type_94_90mm,
        [3, :jap_type_92_hmg],
        :jap_radio_10cm,
        [2, :jap_sc],
        :sniper5,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Saipan, Mariana Islands",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "After over a week of fighting over the island of Saipan, the
          Japanese had established a defensive line from Garapan on the west
          coast of the island to Mount Tapatchou to Magicienne Bay on the east
          coast. It held most of the high ground, allowing the Japanese to
          observe the American movements and the rough terrain and brush hid
          numerous caves.",
          "The American forces prepared for a frontal assault on the line
          using three divisions, two Marine divisions on the flanks and the
          27th Infantry Division in the center. The Marine Divisions attacked
          first, leaving a gap, and that evening the 27th (less a regiment to
          reduce Nafutan point) was ordered to move up into the difficult
          terrain between the Marine divisions.",
          "The next day, the Marine divisions on the flanks made progress, but
          the 27th Infantry Division, which started its attack late, stalled
          in its assault on a valley surrounding a low-lying ridge. Defended
          by about four thousand Japanese soldiers, it came to be nicknamed
          \"Death Valley\" and \"Purple Heart Ridge\" and took more than a
          week to clear, involving heavy use of flame tanks and personal
          flamethrowers in places where the flame tanks couldn't reach.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [1, "rain"],
          wind: [2, 2, true],
          hexes:,
          layout:,
          allied_dir: 2.5,
          axis_dir: 5.5,
          victory_hexes: [
            [0, 9, 2], [12, 11, 2], [4, 11, 2], [3, 7, 2], [4, 4, 2],
          ],
          allied_setup: { "0" => [["*", "20-22"]], "2" => [["*", 22]], "3" => [["*", 22]] },
          axis_setup: { "0" => [["*", "0-18"]] },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "j", h: 5 },
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [2, 5] } },
          ],
          [
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "j", h: 4 },
            { t: "r", h: 4 },
            { t: "r", h: 3 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [2, 6] } },
          ],
          [
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
          ],
          [
            { t: "j", h: 4 },
            { t: "j", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 4, b: "c", be: [4, 5] },
            { t: "r", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j" },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 3] } },
            { t: "o" },
          ],
          [
            { t: "o", h: 3 },
            { t: "r", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 3 },
            { t: "v", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "r", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "j", h: 3 },
            { t: "r", h: 4 },
            { t: "o", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 5] } },
            { t: "o", h: 1 },
            { t: "o", h: 3, b: "c", be: [1, 2, 3] },
            { t: "o", h: 3, b: "c", be: [2] },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4, b: "c", be: [5, 6] },
            { t: "r", h: 2 },
            { t: "o", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "r", h: 3 },
            { t: "v", h: 3 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 3, b: "c", be: [3, 4] },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 6] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
          ],
          [
            { t: "j", h: 3 },
            { t: "j", h: 2 },
            { t: "r", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3, b: "c", be: [3, 4] },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 3 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "j", h: 2 },
          ],
          [
            { t: "v", h: 2 },
            { t: "b", h: 3 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 2 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 3 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
          ],
          [
            { t: "b", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "v", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
          ],
          [
            { t: "b", h: 4 },
            { t: "r", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [3, 6] } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
          ],
          [
            { t: "r", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "j", h: 3 },
            { t: "o", h: 2 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] }, h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [4, 6] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 4] }, h: 1 },
            { t: "o", r: { t: "d", d: [1, 3] }, h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", r: { t: "d", d: [3, 6] } },
            { t: "o" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ],
        ]
      end
    end
  end
end
