# frozen_string_literal: true

module Scenarios
  class Scenario032 < Base
    ID = "032"
    NAME = "Red Banner"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 4, 30].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_5_2,
        [2, :ussr_leader_5_1],
        [2, :ussr_assault_s],
        [4, :ussr_guards_rifle_s],
        [3, :ussr_dp_27],
        :ussr_ft,
        [2, :ussr_sc],
        :ussr_isu_152,
        :ussr_isu_122,
        :ussr_radio_152mm,
      ] },
      "5": { list: [
        [2, :ussr_leader_6_1],
        [2, :ussr_guards_rifle_s],
        [2, :ussr_smg_s],
        [2, :ussr_dp_27],
        :ussr_is_2,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_4_1,
        :ger_leader_3_1,
        [6, :ger_volksgrenadier_s],
        [2, :ger_ss_s],
        [5, :ger_mg_42],
        :ger_kz_8cm_grw_42,
        :ger_crew_t,
        :ger_12_8cm_pak_44,
        [4, :tanktrap],
        [4, :mines12],
        [6, :wire],
        :sniper5,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Berlin, Germany",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "Six days after entering Berlin, the Soviet 3rd Shock Army crossed
          the Moltke Bridge and started to fan out into the surrounding
          streets and buildings. The initial assault on the buildings were
          hampered by the lack of supporting artillery, and it wasn't until
          the damaged bridges were repaired that artillery could be moved up
          in support.  At dawn, the Soviets pressed on with their assault. To
          the southwest, the 8th Guards Army attacked north across the
          Landwehr canal into the Tiergarten.",
          "While the Soviets placed great importance in its capture, the
          Reichstag had not been in use since it had burned in February 1933
          and had been left in ruins ever since. The Germans did not regard
          the location as especially vital, but nonetheless deployed a
          substantial garrison force to defend it.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 4, true],
          hexes:,
          layout:,
          allied_dir: 4.5,
          axis_dir: 1.5,
          victory_hexes: [
            [6, 14, 2], [6, 11, 2], [13, 11, 2], [14, 14, 2], [18, 18, 2], [5, 7, 1], [16, 20, 2],
            [10, 10, 2], [14, 7, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-9", "0-2"], ["0-5", 3], ["0-4", "4-5"], ["0-5", "6-7"], ["0-6", "8-9"], [0, 10],
            ],
            "5" => [[0, "15-21"], ["0-12", 22]],
          },
          axis_setup: {
            "0" => [
              ["7-12", 5], ["7-14", 6], ["7-15", 7], ["8-16", "8-9"], ["8-17", 10], ["2-17", 11],
              ["2-18", 12], ["1-18", 13], ["1-19", 14], ["0-20", 15], ["*", "16-22"],
            ],
          },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "w" },
            { t: "w" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", rr: { d: [[2, 5]] }, r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", rr: { d: [[3, 6]] }, r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "w", r: { t: "t", d: [1, 4] } },
            { t: "w", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
          ],
          [
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", rr: { d: [[2, 5]] }, r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[3, 1]] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 3, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "o", s: { t: "t", d: [4, 6] } },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", s: { t: "t", d: [3, 5] } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "w", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", s: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", rr: { d: [[2, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
            { t: "o", rr: { d: [[1, 4]] } },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", s: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 2 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2 },
            { t: "o", s: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s", s: "u" }, d: 5 },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", s: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "w" },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "d", d: 2.5 },
            { t: "o" },
            { t: "d", d: 2.5 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
          ],
          [
            { t: "w" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "d", d: 2.5 },
            { t: "o" },
            { t: "d", d: 2.5 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 4 },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 4 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", st: { sh: "s", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bs3", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 1 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l", s: "u" }, d: 2.5 },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "d", d: 2.5 },
            { t: "o", r: { t: "t", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "bs3", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 4, 6], c: "l" } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4], c: "r" } },
            { t: "o", r: { t: "t", d: [1, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "s", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s", s: "u" }, d: 4 },
            { t: "o" },
          ],
          [
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
