# frozen_string_literal: true

module Scenarios
  class Scenario612 < Base
    ID = "612"
    NAME = "Taierzhuang"
    ALLIES = ["chi"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1938, 4, 5].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :chi_leader_4_1,
        [2, :chi_leader_3_1],
        [10, :chi_regular_s],
        [4, :chi_sc],
        :chi_m1915_hotchkiss,
        :chi_type_24_maxim,
        :sniper5,
      ] },
      "2": { list: [
        :chi_leader_5_1,
        :chi_leader_3_1,
        [6, :chi_regular_s],
        [4, :chi_sc],
        :chi_fn_m1930,
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_2,
        :jap_leader_4_1,
        [8, :jap_b_division_s],
        :jap_crew_t,
        :jap_type_92_hmg,
        [2, :jap_type_96_lmg],
        :jap_70mm_type_92,
        [2, :jap_sc],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Taierzhuang, Shandong, China",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battle of Taierzhuang was fought during the peak of the Xuzhou
          Campaign, and was the first major Chinese victory of the Second
          Sino-Japanese war. Beyond the actual outcome of the battle, it was
          also a blow to the Japanese military's reputation as an invincible
          force and a tremendous morale boost for the Chinese.",
          "The battle was characterized by vicious close quarters combat. The
          cramped conditions of urban warfare neutralized Japanese advantages
          in artillery and air power and the Chinese were able to fight the
          Japanese on fairly even terms. Unlike previous engagements, the
          Chinese managed to resupply their troops while also preventing the
          Japanese from doing the same. After two weeks of heavy fighting, the
          Japanese were in short supply of men and material and encircled by a
          Chinese counterattack, and were forced out of Taierzhuang with heavy
          casualties.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 4, true],
          hexes:,
          layout:,
          allied_dir: 5.5,
          axis_dir: 2.5,
          victory_hexes: [
            [11, 18, 2], [7, 10, 2], [2, 18, 2], [8, 3, 1], [1, 12, 2], [12, 7, 2], [12, 13, 2],
            [2, 7, 2], [7, 7, 2],
          ],
          allied_setup: {
            "0" => [["*", "0-5"]],
            "2" => [[0, "1-10"], [14, "1-10"], ["*", 0]],
          },
          axis_setup: { "0" => [["*", "7-22"]] },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4, 5], c: "r" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 4, 6], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "d", d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "f" },
            { t: "f", r: { t: "p", d: [3, 5] } },
            { t: "o", r: { t: "t", d: [2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 2, 4], c: "l" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "b" },
            { t: "o" },
            { t: "b" },
            { t: "o" },
            { t: "f" },
            { t: "f", r: { t: "p", d: [2, 6] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
          ],
          [
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "b" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "f", r: { t: "p", d: [3, 6] } },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "b" },
            { t: "b" },
            { t: "b" },
            { t: "f" },
            { t: "f", r: { t: "p", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
          ],
          [
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "o", r: { t: "d", d: [3, 5], c: "r" } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2.5 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "d", d: 1 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "d", d: 1 },
          ],
          [
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "d", d: [2, 6], c: "l" } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 2 },
            { t: "d", d: 2 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "f" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "s2", s: "f" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "f" }, d: 1 },
          ],
          [
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 3, 4, 5], c: "r" } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 5] } },
            { t: "o", st: { sh: "m2", s: "f" }, d: 2 },
            { t: "d", d: 2 },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "d", d: [4, 6] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "d", d: [1, 4] } },
          ],
        ]
      end
    end
  end
end
