# frozen_string_literal: true

module Scenarios
  class Scenario615 < Base
    ID = "615"
    NAME = "The Tightening Noose"
    ALLIES = ["ind"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 2, 28].freeze
    LAYOUT = [23, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_5_2,
        [3, :uk_leader_4_1],
        [8, :uk_indian_s],
        [3, :uk_bren_lmg],
        :uk_radio_152mm,
        [6, :uk_m4_sherman],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        [3, :jap_leader_4_1],
        [7, :jap_conscript_s],
        :jap_type_92_hmg,
        [4, :jap_sc],
        [2, :jap_70mm_type_92],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Meiktila, Burma",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "The Battles of Meiktila and Mandalay were were decisive battles
          fought simultaneously near the end of the Burma camplaign. Together
          they are sometimes referred to as the Battle of Central Burma.
          Despite logistical difficulties, the Allies were able to deploy
          large armored and mechanized forces (largely consisting of Indian
          divisions, as well as a British infantry division and some American
          support elements) in Central Burma, and also possessed air
          supremacy.",
          "Japanese losses in Burma and India in 1944 had been catastrophic,
          and the remaining Japanese formations were severely understrength
          and made up with drafts of conscripts, and few tanks or aircraft
          were left. Most of the remaining Japanese forces in Burma were
          destroyed during the battles, allowing the Allies to recapture the
          capital, Rangoon, and reoccupy most of the rest of the country with
          little remaining organized Japanese opposition.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [3, 3, true],
          hexes:,
          layout:,
          allied_dir: 4,
          axis_dir: 1,
          victory_hexes: [
            [6, 7, 2], [6, 17, 2], [9, 11, 2], [13, 9, 2], [14, 15, 2], [18, 14, 2], [15, 12, 2],
          ],
          allied_setup: {
            "0" => [
              ["0-4", "0-14"], ["0-3", "15-16"], ["0-2", "17-19"], ["0-3", "20-21"], ["0-4", 22],
            ],
          },
          axis_setup: {
            "0" => [
              ["6-22", "0-14"], ["5-22", "15-16"], ["4-22", "17-19"], ["5-22", "20-21"],
              ["6-22", 22],
            ],
          },
          base_terrain: "",
        }
      end

      def hexes
        [
          [
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [3, 6] } },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "w", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 4, 5] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 3 },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [2, 5] } },
          ],
          [
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 3 },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 2, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 3 },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "w", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "g" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 2 },
            { t: "o" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "f" }, d: 1 },
            { t: "o" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "d", d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "f" },
            { t: "o", r: { t: "t", d: [2, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "o" },
            { t: "g" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "o", r: { t: "t", d: [1, 3] } },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1 },
            { t: "f" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "d", d: 3 },
            { t: "o", r: { t: "t", d: [3, 4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "f" },
            { t: "f" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
          [
            { t: "g" },
            { t: "g" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "d", d: 1 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ],
        ]
      end
    end
  end
end
