# frozen_string_literal: true

module Scenarios
  class Scenario022 < Base
    ID = "022"
    NAME = "Enemy at the Gates"
    ALLIES = ["ussr"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1942, 10, 15].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :ussr_leader_4_1,
        :ussr_leader_3_1,
        [4, :ussr_rifle_s],
        [2, :ussr_smg_s],
        [2, :ussr_pm_m1910],
        :ussr_rm_38,
        [4, :ussr_decoy_leader6],
        [6, :ussr_decoy_squad4_s],
        [3, :ussr_decoy_weapon1],
        :ussr_decoy_weapon0,
        :sniper5,
      ] },
      "4": { list: [
        :ussr_leader_5_1,
        [2, :ussr_leader_4_1],
        [3, :ussr_rifle_s],
        [3, :ussr_smg_s],
        :ussr_ft,
        [2, :ussr_sc],
        [2, :ussr_dp_27],
        :ussr_radio_152mm,
        :ussr_decoy_leader6,
        [2, :ussr_decoy_squad4_s],
        :ussr_decoy_weapon1,
        [2, :ussr_decoy_weapon0],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_1,
        :ger_leader_5_1,
        [2, :ger_leader_4_1],
        [8, :ger_rifle_s],
        [4, :ger_mg_34],
        :ger_5cm_legrw_36,
        :ger_radio_15cm,
        [2, :ger_decoy_leader6],
        [4, :ger_decoy_squad4_s],
        [3, :ger_decoy_weapon0],
        :sniper5,
      ] },
      "3": { list: [
        :ger_leader_6_2,
        :ger_leader_5_2,
        [2, :ger_sturm_s],
        [2, :ger_pionier_s],
        [2, :ger_ft],
        [2, :ger_sc],
        :ger_decoy_leader6,
        [2, :ger_decoy_squad5_s],
        :ger_decoy_weapon1,
        :ger_decoy_weapon0,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 8,
          first_deploy: 1,
          first_action: 2,
          date:,
          location: "Stalingrad, Russia",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["allied_hidden_units", "axis_hidden_units"],
        }
      end

      def description
        [
          "When the fighting in Stalingrad shifted north to the industrial
          district, much of it centered on the Barrikady Arms factory.  Along
          with the Red October steel complex, the Barrikady had been turned
          into a fortress by the Soviets. The fighting for the Barrikady may
          have been some of the most brutal combat ever, often devolving to
          savage hand-to-hand fighting for the smallest of gains.",
          "The Barrikady fuel tanks, located near the Volga River, were a
          particularly important strategic location within the factory.  The
          tanks were the site of some of that ferocious hand-to-hand combat,
          changing hands multiple times between the German and the Soviets.
          The burning fuel from these tanks served as a visible beacon for
          Luftwaffe bombers, particularly Stuka dive-bombers, aiding them in
          targeting Soviet positions across the city. Control of the oil depot
          was so vital that it was directly defended by Lieutenant General
          Vasily Chuikov’s headquarters, which was located in the nearby water
          pump station, underscoring the tactical importance of holding this
          narrow strip of land along the riverbank.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [1, 3, true],
          hexes:,
          layout:,
          allied_dir: 6.5,
          axis_dir: 3.5,
          victory_hexes: [
            [9, 16, 1], [11, 7, 1], [7, 8, 1], [8, 5, 1], [8, 12, 1], [2, 9, 2], [4, 17, 2],
          ],
          allied_setup: {
            "0" => [
              ["6-14", 0], ["5-14", "1-2"], ["4-14", "3-4"], ["3-14", 5], ["4-14", "6-7"],
              ["5-14", "8-9"], ["6-14", "10-11"], ["7-14", "12-13"], ["8-14", "14-15"],
              ["9-14", 16], ["8-14", "17-18"], ["7-14", "19-20"], ["6-14", "21-22"],
            ],
            "4" => [[14, "0-17"]],
          },
          axis_setup: {
            "0" => [
              ["0-4", 0], ["0-3", "1-2"], ["0-2", "3-4"], ["0-1", 5], ["0-2", "6-7"],
              ["0-3", "8-9"], ["0-4", "10-11"], ["0-5", "12-13"], ["0-6", "14-15"], ["0-7", 16],
              ["0-6", "17-18"], ["0-5", "19-20"], ["0-4", "21-22"],
            ],
            "3" => [[0, "*"]],
          },
          base_terrain: "u",
        }
      end

      def hexes
        [
          [
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "x" },
            { t: "o", st: { sh: "m2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "x" },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "x" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "x" },
            { t: "c" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1.5 },
            { t: "o" },
            { t: "o", st: { sh: "l2", s: "u" }, d: 1.5 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", r: { t: "t", d: [3, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "c" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "x" },
            { t: "o" },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 3 },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "x" },
            { t: "o", st: { sh: "m2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", st: { sh: "m2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 3 },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[3, 5]] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [2, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bs4", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 3 },
            { t: "o" },
            { t: "x" },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
          ],
          [
            { t: "x" },
            { t: "o" },
            { t: "c" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o" },
            { t: "o", st: { sh: "m2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "x" },
            { t: "o" },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
          ],
          [
            { t: "x" },
            { t: "o" },
            { t: "c" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bm", s: "u" }, d: 3 },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "x" },
            { t: "o" },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 6 },
            { t: "x" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [3, 5, 6] } },
            { t: "o" },
            { t: "o", st: { sh: "bs1", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "bs2", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] }, r: { t: "t", d: [3, 6] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [4, 6] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o", st: { sh: "bc4", s: "u" }, d: 6 },
            { t: "o", st: { sh: "bc2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "c" },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "c" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "x" },
            { t: "o", st: { sh: "bc1", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "x" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", st: { sh: "bc3", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "x" },
          ],
          [
            { t: "o", st: { sh: "m2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o" },
            { t: "o" },
            { t: "c" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "x" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 3, 5] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [2, 3, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "c" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o", st: { sh: "m2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o", r: { t: "t", d: [2, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "o", rr: { d: [[2, 5]] } },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", r: { t: "t", d: [2, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "o", r: { t: "t", d: [1, 4] } },
            { t: "x" },
            { t: "c" },
            { t: "o", rr: { d: [[2, 6]] } },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
          ],
          [
            { t: "o", h: -1 },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o", st: { sh: "s2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "m2", s: "u" }, d: 1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 4 },
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "c" },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
          ],
          [
            { t: "x" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
          ],
          [
            { t: "x" },
            { t: "c" },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "c" },
            { t: "o", h: -1 },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o", st: { sh: "t", s: "u" }, d: 1 },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
          ],
          [
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 3 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o" },
            { t: "x" },
            { t: "o" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
          ],
          [
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", r: { t: "t", d: [3, 6] } },
            { t: "o", st: { sh: "s2", s: "u" }, d: 6 },
            { t: "o", rr: { d: [[3, 6]] } },
            { t: "x" },
            { t: "x" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "x" },
            { t: "x" },
            { t: "o" },
            { t: "o", h: -1 },
            { t: "o", h: -1 },
          ],
        ]
      end
    end
  end
end
