# frozen_string_literal: true

module Scenarios
  class Scenario107 < Base
    ID = "107"
    NAME = "Hellfire Pass"
    ALLIES = ["uk"].freeze
    AXIS = ["ger"].freeze
    STATUS = "p"

    DATE = [1941, 6, 15].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :uk_leader_5_1,
        :uk_leader_4_1,
        [4, :uk_line_s],
        [2, :uk_line_t],
        :uk_bren_lmg,
        :uk_2inch_mortar,
        [5, :uk_matilda_ii],
        [2, :uk_matilda_ii_cs],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :ger_leader_6_2,
        [3, :ger_rifle_s],
        :ger_rifle_t,
        [3, :ger_elite_crew_t],
        :ger_mg_34,
        [3, :ger_8_8cm_flak_36],
        [2, :ger_pzkpfw_ii_f],
        :ger_pzkpfw_iii__40,
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Halfaya Pass, Libya",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
        }
      end

      def description
        [
          "Halfaya Pass was of great strategic importance; the only ways
          westwards into Libya were along the narrow passage along the coast,
          or to assault the pass or flank it to the south.  The British had
          captured the pass both during the initial assault on Libya and
          during Operation Brevity, but neither time had the British
          ultimately held it before being driven back farther east.",
          "By the time the British next assaulted the pass during Operation
          Battleaxe, Rommel had realized the strategic significance of it, and
          fortified it with 88mm guns.  During the battle, the Germans
          attempted to draw in British tanks by deploying a small tank force
          as a decoy to draw British armor into an ambush; the ambush was
          executed successfully and all but one of the attacking British tank
          were destroyed.",
        ]
      end

      def map_data
        {
          start_weather: 0,
          base_weather: 0,
          precip: [0, 2],
          wind: [2, 5, true],
          hexes:,
          layout:,
          allied_dir: 3.5,
          axis_dir: 6.5,
          victory_hexes: [
            [13, 4, 1], [2, 11, 2], [2, 18, 2], [4, 20, 2], [10, 21, 2],
          ],
          allied_setup: { "0" => [
            ["10-14", "0-7"], ["*", 0], ["*", 0], ["1-14", 1], ["3-14", 2],
            ["6-14", 3], [9, 4],
          ] },
          axis_setup: { "0" => [
            ["*", "10-22"], ["0-3", 9], ["0-1", 8],
          ] },
          base_terrain: "d",
        }
      end

      def hexes
        [
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "w" },
            { t: "w" },
            { t: "w" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
            { t: "s" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "s" },
            { t: "s" },
          ], [
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4] } },
            { t: "o", r: { d: [1, 5] } },
            { t: "o", d: 1, st: { sh: "h", s: "f" } },
            { t: "o", d: 1, st: { sh: "h", s: "f" } },
            { t: "s" },
          ], [
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 4] } },
            { t: "o", r: { d: [1, 4, 6] } },
            { t: "s", r: { d: [1, 4] } },
          ], [
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", d: 3, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", d: 3, st: { sh: "h", s: "f" } },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "s" },
            { t: "o" },
          ], [
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 5], t: "p" } },
            { t: "s" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 5], t: "p" } },
            { t: "o" },
            { t: "o", h: 1 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5, b: "c", be: [2, 3] },
            { t: "o", h: 5, b: "c", be: [2, 3, 4] },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [2, 6], t: "p" } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
          ], [
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5, b: "c", be: [3] },
            { t: "o", h: 5, b: "c", be: [2, 3, 4] },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", r: { d: [3, 6], t: "p" } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5, b: "c", be: [3, 4, 5] },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { d: [6, 4], t: "p" } },
            { t: "o", h: 1, r: { d: [1, 3], t: "p" } },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5, b: "c", be: [4] },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { d: [3, 5], t: "p" } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5, b: "c", be: [3, 4, 5] },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 1, r: { d: [4, 5], t: "p" } },
            { t: "o", h: 1, r: { d: [1, 2], t: "p" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5, b: "c", be: [4, 5] },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { d: [4, 5], t: "p" } },
            { t: "o", h: 1, r: { d: [1, 2], t: "p" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { d: [5, 6], t: "p" } },
            { t: "o", h: 2, r: { d: [4, 6], t: "p" } },
            { t: "o", h: 2, r: { d: [1, 2], t: "p" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 2, r: { d: [4, 6], t: "p" } },
            { t: "o", h: 2, r: { d: [1, 3], t: "p" } },
            { t: "o", h: 2, r: { d: [2, 3], t: "p" } },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3, r: { d: [3, 6], t: "p" } },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "r", h: 3 },
            { t: "r", h: 4 },
            { t: "r", h: 4 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4, d: 1, st: { sh: "h", s: "f" } },
            { t: "o", h: 4, d: 1, st: { sh: "h", s: "f" } },
            { t: "o", h: 3, r: { d: [4, 6], t: "p" } },
            { t: "o", h: 3, r: { d: [1, 3], t: "p" } },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 5 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4, r: { d: [4, 6], t: "p" } },
            { t: "o", h: 4, r: { d: [1, 4], t: "p" } },
            { t: "o", h: 4, r: { d: [1, 3], t: "p" } },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "r", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
          ], [
            { t: "o", h: 4, r: { d: [1, 4], t: "p" } },
            { t: "o", h: 4, r: { d: [1, 3], t: "p" } },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4, d: 2, st: { sh: "h", s: "f" } },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
          ], [
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 4 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
            { t: "o", h: 5 },
          ],
        ]
      end
    end
  end
end
