# frozen_string_literal: true

module Scenarios
  class Scenario420 < Base
    ID = "420"
    NAME = "The Meatgrinder"
    ALLIES = ["usa"].freeze
    AXIS = ["jap"].freeze
    STATUS = "p"
    VERSION = "0.1"

    DATE = [1945, 2, 27].freeze
    LAYOUT = [15, 23, "x"].freeze

    ALLIED_UNITS = {
      "0": { list: [
        :usa_leader_6_1,
        [2, :usa_leader_5_1],
        [9, :usa_marine_rifle_s],
        [2, :usa_ft],
        [2, :usa_sc],
        [4, :usa_m1918_bar],
        :usa_radio_8inch,
        [2, :usa_m4_sherman_flame],
      ] },
      "4": { list: [
        :usa_leader_6_1,
        [3, :usa_marine_rifle_s],
        :usa_m1918_bar,
        :usa_leader_5_1,
        :usa_ft,
        :usa_sc,
        [2, :usa_m4a3e2_sherman],
      ] },
    }.freeze

    AXIS_UNITS = {
      "0": { list: [
        :jap_leader_5_1,
        [2, :jap_leader_4_1],
        [7, :jap_b_division_s],
        [3, :jap_crew_t],
        [3, :jap_type_92_hmg],
        [2, :jap_type_92_10cm],
        :jap_type_89_15cm,
        :jap_type_97_90mm,
        :sniper5,
      ] },
      "2": { list: [
        :jap_leader_5_1,
        [2, :jap_b_division_s],
        :jap_type_99_lmg,
        [2, :jap_type_95_ha_go],
      ] },
    }.freeze

    class << self
      def generate
        {
          turns: 7,
          first_deploy: 2,
          first_action: 1,
          date:,
          location: "Hill 382, Iwo Jima",
          author: "The Establishment",
          description:,
          map_data:,
          allied_units:,
          axis_units:,
          special_rules: ["axis_cave_movement"],
        }
      end

      def description
        [
          "Despite the loss of Mount Suribachi on the south end of the Iwo
          Jima, the Japanese still held strong positions on the north end of
          the island. The rocky terrain favored defense, even more so than
          Mount Suribachi, which was much more vulnerable to naval artillery
          fire. The fortifications on the northern section of Iwo Jima were
          also more developed than those at the southern end of the island.
          The biggest task for to the Marines was seizing the Motoyama
          Plateau, with its distinctive Hill 382 and Turkey Knob, as well as
          the area in between referred to as The Amphitheater. These obstacles
          formed the basis of what came to be known as the meatgrinder. While
          these Japanese positions were being reduced on the right flank,
          American units on the left were clearing out Hill 362 with just as
          much difficulty.",
          "The Marines' overall objective at this point was to take control of
          Airfield No. 2 in the center of the island. However, constant pop-up
          attacks by the Japanese from caves and concealed positions raked the
          Americans flanks, chewing up and sometimes wiping out the attackers.
          Tanks were destroyed by interlocking fire or destroyed by mines. As
          a result, the fighting bogged down, and American casualties piled up
          rapidly. Even capturing these points did not guarantee that the
          captured territory was secure, since a previously cleared
          fortification could be reoccupied by Japanese troops utilizing the
          island's tunnel system.",
        ]
      end

      def map_data
        {
          start_weather: "dry",
          base_weather: "dry",
          precip: [0, "rain"],
          wind: [2, 6, true],
          hexes:,
          layout:,
          allied_dir: 3,
          axis_dir: 6,
          victory_hexes: [
            [6, 11, 2], [9, 7, 2], [7, 8, 2], [10, 14, 2], [3, 6, 2], [8, 3, 2], [12, 6, 2],
          ],
          allied_setup: {
            "0" => [
              [0, "14-15"], ["0-1", "16-17"], ["0-2", "18-19"], ["0-3", "20-21"], ["0-4", 22],
            ],
            "4" => [[0, "14-21"], ["0-4", 22]],
          },
          axis_setup: {
            "0" => [[11, 1], [2, 2], [12, 4], [6, 7], [8, 9], [9, 13], [5, 15], [11, 16], [9, 21]],
            "2" => [["8-14", 0], [14, "1-19"]],
          },
          base_terrain: "b",
        }
      end

      def hexes
        [
          [
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "v", h: 2 },
            { t: "o", h: 3 },
            { t: "j", h: 3 },
            { t: "j", h: 3 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "v", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "d", d: [4, 6] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 2, 5] } },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 3 },
          ],
          [
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "d", d: [1, 3] } },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 2 },
            { t: "o", h: 1, r: { t: "d", d: [2, 5] } },
            { t: "j", h: 2 },
            { t: "v", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2, r: { t: "d", d: [2, 5] } },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "a", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 5] } },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1, r: { t: "a", d: [3, 6] } },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "v", h: 2 },
            { t: "r", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 3 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2, r: { t: "d", d: [2, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
            { t: "o", h: 2, r: { t: "d", d: [1, 4] } },
          ],
          [
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1, r: { t: "a", d: [3, 6] } },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "o", h: 3 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "a", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1, st: { sh: "h", s: "f" }, d: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 2 },
            { t: "r", h: 2 },
            { t: "v", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1, r: { t: "a", d: [3, 6] } },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1, r: { t: "a", d: [1, 3, 4, 6] } },
            { t: "o", h: 1, r: { t: "a", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "a", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "a", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "a", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "a", d: [1, 4] } },
            { t: "o", h: 1, r: { t: "a", d: [1, 4] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1, r: { t: "a", d: [3, 6] } },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "v", h: 2 },
            { t: "o", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 3 },
            { t: "r", h: 3 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "v", h: 1 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "r", h: 2 },
            { t: "r", h: 2 },
            { t: "o", h: 2 },
            { t: "o", h: 2 },
            { t: "j", h: 2 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "v", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 2 },
            { t: "o", h: 2 },
          ],
          [
            { t: "o", h: 1 },
            { t: "b", h: 1 },
            { t: "b", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
          ],
          [
            { t: "o" },
            { t: "r" },
            { t: "r" },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "r" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "r", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
            { t: "v" },
            { t: "j" },
            { t: "j" },
            { t: "j", h: 1 },
            { t: "o", h: 1 },
            { t: "o", h: 1 },
          ],
          [
            { t: "o" },
            { t: "o" },
            { t: "r" },
            { t: "r" },
            { t: "o" },
            { t: "j" },
            { t: "j" },
            { t: "j" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
            { t: "o" },
          ],
        ]
      end
    end
  end
end
