import { HexData } from "../engine/Hex"
import { Direction, UnitStatus, unitStatus } from "../utilities/commonTypes"

const testUnitData: { [index: string]: string } = {
  ginf: "ger_Rifle_sqd", gldr: "ger_Leader_ldr_6_2", gcrew: "ger_Crew_tm_1",
  gmg: "ger_MG 42_sw", gps: "ger_Panzerschreck_sw", gpf: "ger_Panzerfaust_sw",
  gtank: "ger_Panther D_tank", gspg: "ger_StuG III-F/G_spg", gscout: "ger_SdKfz 221_ac",
  ght: "ger_SdKfz 250/11_ht",
  rinf: "ussr_Guards SMG_sqd", rldr: "ussr_Leader_ldr_4_1", rmg: "ussr_DShK_sw",
  rft: "ussr_Flamethrower_sw", rmc: "ussr_Molotov Cocktail_sw", rmort: "ussr_RM-38_sw",
  rgun: "ussr_76mm M1927_gun", rcrew: "ussr_Crew_tm_2", rat: "ussr_57mm ZiS-2_gun",
  rtank: "ussr_T-34-85_tank", rgrant: "ussr_M3 Grant_tank",
  rm2cs: "uk_Matilda II CS_spg", croc: "uk_Churchill Crocodile_spg",
  flak88: "ger_8.8cm Flak 36_gun", radio: "ussr_Radio 85mm_sw",
  usldr: "usa_Leader_ldr_5_2", usldr2: "usa_Leader_ldr_4_1", useng: "usa_Engineer_sqd", usinf: "usa_Green_sqd",
  uscrew: "usa_Crew_tm_2", usft: "usa_Flamethrower_sw", usmg: "usa_M1918 BAR_sw", usmg2: "usa_M2 Browning_sw",
  ussc: "usa_Satchel Charge_sw", usradio: "usa_Radio 155mm_sw", usmort: "usa_M2 Mortar_sw",
  usmort2: "usa_M1 Mortar_sw", usmort3: "usa_M2 4.2inch Mortar_sw", usbaz: "usa_M1 Bazooka_sw",
  usgun: "usa_75mm M1 Pack_gun", usat: "usa_37mm M3_gun", usac: "usa_M3A1 Scout Car_ac",
  ustank: "usa_M4 Sherman_tank", ussg: "usa_M3 Lee_tank", usspg: "usa_M8 Scott_spg",
  usspat: "usa_M18 Hellcat_spg", usftt: "usa_M3A1 Stuart FT_spg", usftt2: "usa_M4A3R5 Sherman_spg",
  usht: "usa_M2 Half-track_ht", usht2: "usa_T12 GMC_ht", usht3: "usa_T19/M21 MMC_ht",
  usht4: "usa_LVT-1_ht", usht5: "usa_LVT-2_ht", usht6: "usa_LVT(A)-4_ht", ustruck: "usa_GMC CCKW_truck",
  ustruck2: "usa_GMC DUKW_truck", usjeep: "usa_Jeep_truck", usjeep2: "usa_Jeep .50 MG_truck",
  usmoto: "usa_H-D WLA_cav", hcav: "ger_Horse_cav", bcav: "jap_Bicycle_cav", htm: "ger_Kettenkrad_truck",
  htsm: "ger_SdKfz 7_truck", tspag: "ger_Marder I_spg", tft: "ger_SdKfz 251/16_ht", atr: "uk_Boys AT Rifle_sw",
  uc: "uk_Universal Carrier_ht", tkt: "ita_L3/33_spg", amt: "jap_Type 2 Ka-Mi_tank",
  ukinf: "uk_Guard_sqd", ac: "fra_Schneider P16_ac", rtr: "uk_Chevy C30 AT_truck"
}

const testFeatureData: { [index: string]: string } = {
  smoke: "f_Smoke_2", fire: "f_Blaze", wire: "f_Wire", apmines: "f_AP Minefield", mixedmines: "f_Minefield",
  atmines: "f_AT Minefield", fox: "f_Foxhole", pillbox: "f_Pillbox", bunker: "f_Bunker",
  strongpoint: "f_Strong Point", trench: "f_Trench", scrape: "f_Shell Scrape", roadblock: "f_Road Block",
  rubble: "f_Rubble", tanktrap: "f_Hedgehog",
}

export const mapDebugData: {
  x: number, y: number,
  features: { u: string, x: number, y: number, f?: Direction }[],
  units: {
    u: string, x: number, y: number, f?: Direction, tf?: Direction, v?: number,
    imm?: boolean, trt?: boolean, st?: UnitStatus, brk?: boolean, wpn?: boolean,
  }[],
  hexes: HexData[][]
}[] = [
  {
    x: 15, y: 15,
    features: [
      { u: testFeatureData.smoke, x: 6, y: 5 },
      { u: testFeatureData.fire, x: 7, y: 5 },
      { u: testFeatureData.wire, x: 0, y: 9 },
      { u: testFeatureData.apmines, x: 0, y: 11 },
      { u: testFeatureData.mixedmines, x: 1, y: 11 },
      { u: testFeatureData.atmines, x: 2, y: 11 },
      { u: testFeatureData.fox, x: 7, y: 6 },
      { u: testFeatureData.pillbox, x: 0, y: 13, f: 2 },
      { u: testFeatureData.bunker, x: 7, y: 14, f: 2 },
      { u: testFeatureData.strongpoint, x: 3, y: 14, f: 3 },
    ],
    units: [
      { u: testUnitData.ginf, x: 6, y: 0 },
      { u: testUnitData.gpf, x: 6, y: 0 },
      { u: testUnitData.rgrant, x: 14, y: 1, f: 1, tf: 2 },
      { u: testUnitData.rinf, x: 13, y: 1 },
      { u: testUnitData.rmort, x: 13, y: 1 },
      { u: testUnitData.rinf, x: 12, y: 1 },
      { u: testUnitData.rmc, x: 12, y: 1 },
      { u: testUnitData.rinf, x: 11, y: 1 },
      { u: testUnitData.rft, x: 11, y: 1 },
      { u: testUnitData.rinf, x: 8, y: 1 },
      { u: testUnitData.ght, x: 1, y: 1, f: 4 },
      { u: testUnitData.rtank, x: 10, y: 2, f: 1, tf: 6 },
      { u: testUnitData.rinf, x: 9, y: 2 },
      { u: testUnitData.rmg, x: 9, y: 2 },
      { u: testUnitData.rldr, x: 9, y: 2 },
      { u: testUnitData.gtank, x: 2, y: 1, f: 5, tf: 5, v: -1 },
      { u: testUnitData.gtank, x: 3, y: 2, f: 5, tf: 4, v: 1 },
      { u: testUnitData.rcrew, x: 10, y: 3 },
      { u: testUnitData.rgun, x: 10, y: 3, f: 6 },
      { u: testUnitData.ginf, x: 5, y: 3 },
      { u: testUnitData.rinf, x: 11, y: 4 },
      { u: testUnitData.ginf, x: 6, y: 4 },
      { u: testUnitData.gmg, x: 6, y: 4 },
      { u: testUnitData.gldr, x: 6, y: 4 },
      { u: testUnitData.gtank, x: 4, y: 4, f: 5, tf: 5, imm: true },
      { u: testUnitData.gtank, x: 2, y: 3, f: 3, tf: 3, trt: true },
      { u: testUnitData.gtank, x: 2, y: 7, f: 3, tf: 4, wpn: true },
      {
        u: testUnitData.rtank, x: 10, y: 5, f: 1, tf: 1, imm: true, st: unitStatus.Activated,
        brk: true, trt: true
      },
      { u: testUnitData.rinf, x: 11, y: 6, st: unitStatus.Activated },
      { u: testUnitData.ginf, x: 7, y: 6, st: unitStatus.Broken },
      { u: testUnitData.rm2cs, x: 14, y: 7, f: 1, tf: 1 },
      { u: testUnitData.ginf, x: 6, y: 7, st: unitStatus.Pinned },
      { u: testUnitData.gspg, x: 0, y: 7, f: 4 },
      { u: testUnitData.ginf, x: 6, y: 8, st: unitStatus.Tired },
      { u: testUnitData.gscout, x: 4, y: 8, f: 4, tf: 3 },
      { u: testUnitData.ginf, x: 0, y: 8 },
      { u: testUnitData.gmg, x: 0, y: 8, brk: true },
      { u: testUnitData.ginf, x: 6, y: 10, st: unitStatus.Exhausted },
      { u: testUnitData.gtank, x: 5, y: 11, f: 5, tf: 4, st: unitStatus.Wreck },
      { u: testUnitData.rcrew, x: 14, y: 14 },
      { u: testUnitData.rat, x: 14, y: 14, f: 1 },
      { u: testUnitData.ginf, x: 7, y: 14 },
      { u: testUnitData.gps, x: 7, y: 14 },
      { u: testUnitData.croc, x: 14, y: 11, f: 1, tf: 2 },
      { u: testUnitData.rinf, x: 14, y: 4 },
      { u: testUnitData.radio, x: 14, y: 4 },
      { u: testUnitData.gcrew, x: 3, y: 13 },
      { u: testUnitData.flak88, x: 3, y: 13, f: 3 },
    ],
    hexes: [
      [
        { t: "s" },
        { t: "s", r: { d: [2, 5], t: "d" } },
        { t: "s" },
        { t: "o", r: { d: [3, 6], t: "d" } },
        { t: "f" },
        { t: "f" },
        { t: "f" },
        { t: "o" },
        { t: "o", b: "b", be: [1], d: 1, st: { sh: "h" } },
        { t: "o", d: 2, st: { sh: "h", s: "f" }  },
        { t: "o", r: { d: [2, 6], t: "t", c: "l" } },
        { t: "o", b: "w", be: [1] },
        { t: "o", d: 3, st: { sh: "s" } },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "t" } },
      ], [
        { t: "s" },
        { t: "s", r: { d: [2, 4], t: "d" } },
        { t: "o", r: { d: [1, 3, 5], t: "d" } },
        { t: "f" },
        { t: "f" },
        { t: "o" },
        { t: "d", d: 3, b: "b", be: [2, 3] },
        { t: "o", b: "b", be: [2, 3], st: { sh: "c" } },
        { t: "o", d: 2, b: "b", be: [1, 2], st: { sh: "s", s: "f" } },
        { t: "o", r: { d: [3, 5], t: "t", c: "r" } },
        { t: "o", b: "w", be: [1, 2] },
        { t: "o", d: 6, st: { sh: "s" } },
        { t: "o", d: 3, st: { sh: "l" } },
        { t: "o", d: 1, st: { sh: "l" } },
        { t: "o" },
      ], [
        { t: "w" },
        { t: "w" },
        { t: "f" },
        { t: "o", r: { d: [2, 5], t: "d" } },
        { t: "b" },
        { t: "b" },
        { t: "o" },
        { t: "d", d: 2 },
        { t: "d", d: 1 },
        { t: "o", d: 5, st: { sh: "s", s: "f" } },
        { t: "o", r: { d: [2, 4, 6], t: "t", c: "l" }, b: "w", be: [3] },
        { t: "o", r: { d: [1, 4], t: "t" }, b: "w", be: [2, 3] },
        { t: "o", r: { d: [1, 4], t: "t" }, b: "w", be: [2, 3] },
        { t: "o", r: { d: [1, 4], t: "t" }, b: "w", be: [2, 3] },
        { t: "o", r: { d: [1, 4], t: "t" }, b: "w", be: [2, 3] },
      ], [
        { t: "w", s: { d: [1, 4] } },
        { t: "o", s: { d: [1, 5] } },
        { t: "o" },
        { t: "o", r: { d: [2, 5], t: "d" } },
        { t: "f" },
        { t: "f", r: { t: "p", d: [4, 6] } },
        { t: "o" },
        { t: "g", b: "f", be: [1, 2, 3] },
        { t: "g", b: "f", be: [2, 3] },
        { t: "o", r: { d: [3, 5], t: "t", c: "r" }, b: "f", be: [1] },
        { t: "o", d: 1, st: { sh: "s" } },
        { t: "o", d: 1, st: { sh: "m" } },
        { t: "o", d: 4, st: { sh: "s" } },
        { t: "o", d: 2, st: { sh: "x", s: "f" } },
        { t: "o" },
      ], [
        { t: "w" },
        { t: "b" },
        { t: "o", s: { d: [2, 6] } },
        { t: "o" },
        { t: "o", r: { d: [2, 5], t: "d" } },
        { t: "f", r: { t: "p", d: [1, 3] } },
        { t: "f" },
        { t: "o", b: "f", be: [3] },
        { t: "g", b: "f", be: [1] },
        { t: "g", b: "f", be: [3] },
        { t: "o", r: { d: [2, 6], t: "t", c: "l" }, b: "f", be: [1] },
        { t: "o", d: 1, st: { sh: "s" } },
        { t: "o", d: 4, st: { sh: "s" } },
        { t: "o", d: 1, st: { sh: "x" } },
        { t: "o", d: 3, st: { sh: "x" } },
      ], [
        { t: "m" },
        { t: "m", s: { d: [3, 4] } },
        { t: "m", s: { d: [1, 5] } },
        { t: "b" },
        { t: "o", r: { d: [2, 5], t: "d" } },
        { t: "f" },
        { t: "o" },
        { t: "o", b: "f", be: [3] },
        { t: "o", r: { d: [4, 6], t: "d" }, b: "f", be: [2, 3] },
        { t: "o", r: { d: [1, 3, 4], t: "t", c: "r" }, b: "f", be: [2] },
        { t: "o", r: { d: [1, 4], t: "t" } },
        { t: "o", r: { d: [1, 4], t: "t" } },
        { t: "o", r: { d: [1, 4], t: "t" } },
        { t: "o", r: { d: [1, 4], t: "t" } },
        { t: "o", r: { d: [1, 4], t: "t" }, s: { d: [3, 5] } },
      ], [
        { t: "o" },
        { t: "w" },
        { t: "m" },
        { t: "o", s: { d: [2, 5] } },
        { t: "b" },
        { t: "o", r: { d: [2, 5], t: "d" } },
        { t: "f" },
        { t: "o" },
        { t: "o", r: { d: [3, 6], t: "d" } },
        { t: "f" },
        { t: "f" },
        { t: "o", d: 2, st: { sh: "l", s: "f" } },
        { t: "o", d: 2.5, st: { sh: "l", s: "f" } },
        { t: "o", d: 3, st: { sh: "s" } },
        { t: "o" },
      ], [
        { t: "o", r: { d: [1, 4], t: "d" } },
        { t: "o", r: { d: [1, 4], t: "d" } },
        { t: "o", r: { d: [1, 4], t: "d" } },
        { t: "o", s: { d: [2, 5] }, r: { d: [1, 4], t: "d" } },
        { t: "o", r: { d: [1, 4], t: "d" } },
        { t: "o", r: { d: [1, 2, 4], t: "d" } },
        { t: "o", r: { d: [1, 4], t: "d" } },
        { t: "o", r: { d: [1, 3, 5], t: "d" } },
        { t: "f" },
        { t: "f" },
        { t: "f" },
        { t: "o" },
        { t: "o", d: 6, st: { sh: "s" } },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "j" },
        { t: "o", h: 1 },
        { t: "o", s: { d: [2, 6] } },
        { t: "j" },
        { t: "j" },
        { t: "r" },
        { t: "o", r: { d: [2, 4], t: "d" } },
        { t: "f", r: { d: [1, 4], t: "d" } },
        { t: "f", r: { d: [1, 5], t: "d" } },
        { t: "f" },
        { t: "o", h: 1 },
        { t: "o", h: 1 },
        { t: "o", h: 1 },
      ], [
        { t: "o" },
        { t: "o", h: 1 },
        { t: "o", h: 1 },
        { t: "o", s: { d: [3, 5] } },
        { t: "o" },
        { t: "j" },
        { t: "j", h: 1 },
        { t: "r", h: 1 },
        { t: "o", h: 1 },
        { t: "f", h: 1 },
        { t: "f", h: 1, r: { d: [2, 5], t: "d" } },
        { t: "o", h: 1 },
        { t: "f", h: 1 },
        { t: "o", h: 1 },
        { t: "o", h: 2 },
      ], [
        { t: "o", h: 1 },
        { t: "o", h: 1 },
        { t: "o", h: 2 },
        { t: "o", h: 1 },
        { t: "o", s: { d: [2, 5] } },
        { t: "o", h: 1 },
        { t: "j", h: 1 },
        { t: "o", h: 1 },
        { t: "r", h: 1 },
        { t: "r", h: 2 },
        { t: "o", h: 2 },
        { t: "o", h: 1, r: { d: [2, 6], t: "d" } },
        { t: "f", h: 2 },
        { t: "o", h: 2 },
        { t: "o", h: 2 },
      ], [
        { t: "o", h: 1 },
        { t: "o", h: 1 },
        { t: "o", h: 1 },
        { t: "o", h: 2, b: "c", be: [3, 4] },
        { t: "o", s: { d: [2, 5] } },
        { t: "o", h: 2, b: "c", be: [1, 6] },
        { t: "o", h: 2 },
        { t: "o", h: 2 },
        { t: "r", h: 2 },
        { t: "r", h: 2 },
        { t: "o", h: 2, r: { d: [3, 6], t: "d" } },
        { t: "f", h: 2 },
        { t: "o", h: 2 },
        { t: "f", h: 3 },
        { t: "o", h: 3 },
      ], [
        { t: "o", h: 1 },
        { t: "o", h: 1 },
        { t: "b", h: 2 },
        { t: "o", h: 2 },
        { t: "o", h: 2, b: "c", be: [3, 4, 5] },
        { t: "o", s: { d: [2, 6] } },
        { t: "o", h: 2, b: "c", be: [1] },
        { t: "o", h: 3 },
        { t: "r", h: 3 },
        { t: "r", h: 3 },
        { t: "o", h: 3, r: { d: [3, 5], t: "d" } },
        { t: "r", h: 3 },
        { t: "o", h: 3 },
        { t: "f", h: 3 },
        { t: "f", h: 3 },
      ], [
        { t: "o", h: 2 },
        { t: "o", h: 2 },
        { t: "b", h: 2 },
        { t: "o", h: 3, b: "c", be: [4, 5] },
        { t: "o", s: { d: [3, 6] } },
        { t: "o", h: 3, b: "c", be: [1, 2] },
        { t: "o", h: 3 },
        { t: "o", h: 3 },
        { t: "o", h: 3 },
        { t: "o", h: 3 },
        { t: "o", h: 3, r: { d: [2, 5], t: "d" } },
        { t: "r", h: 4 },
        { t: "o", h: 4 },
        { t: "o", h: 4 },
        { t: "o", h: 4 },
      ], [
        { t: "o", h: 2 },
        { t: "o", h: 2 },
        { t: "b", h: 2 },
        { t: "o", h: 3, b: "c", be: [4] },
        { t: "o", h: 1, s: { d: [3, 5] } },
        { t: "o", h: 3, b: "c", be: [1, 2] },
        { t: "o", h: 3 },
        { t: "o", h: 4 },
        { t: "o", h: 3 },
        { t: "o", h: 4 },
        { t: "o", h: 4 },
        { t: "o", h: 4, r: { d: [2, 5], t: "d" } },
        { t: "o", h: 4 },
        { t: "r", h: 5 },
        { t: "o", h: 5 },
      ]
    ],
  },
  {
    x: 15, y: 15,
    features: [
      { u: testFeatureData.smoke, x: 4, y: 14 },
      { u: testFeatureData.fire, x: 5, y: 14 },
    ],
    units: [
      { u: testUnitData.ginf, x: 0, y: 0 },
      { u: testUnitData.ginf, x: 0, y: 1 },
      { u: testUnitData.ginf, x: 0, y: 2 },
      { u: testUnitData.ginf, x: 0, y: 3 },
      { u: testUnitData.ginf, x: 0, y: 4 },
      { u: testUnitData.ginf, x: 0, y: 14 },
      { u: testUnitData.ginf, x: 10, y: 0 },
      { u: testUnitData.ginf, x: 9, y: 1 },
      { u: testUnitData.ginf, x: 10, y: 1 },
      { u: testUnitData.ginf, x: 10, y: 2 },
      { u: testUnitData.ginf, x: 10, y: 3 },
      { u: testUnitData.ginf, x: 10, y: 4 },
      { u: testUnitData.ginf, x: 14, y: 0 },
      { u: testUnitData.ginf, x: 14, y: 1 },
      { u: testUnitData.ginf, x: 14, y: 2 },
      { u: testUnitData.ginf, x: 14, y: 3 },
      { u: testUnitData.ginf, x: 14, y: 4 },
      { u: testUnitData.ginf, x: 14, y: 6 },
      { u: testUnitData.ginf, x: 14, y: 14 },
      { u: testUnitData.ginf, x: 3, y: 3 },
      { u: testUnitData.ginf, x: 8, y: 1 },
      { u: testUnitData.ginf, x: 4, y: 2 },
      { u: testUnitData.ginf, x: 8, y: 2 },
      { u: testUnitData.ginf, x: 10, y: 6 },
      { u: testUnitData.ginf, x: 0, y: 11 },
      { u: testUnitData.ginf, x: 0, y: 13 },
      { u: testUnitData.ginf, x: 2, y: 11 },
      { u: testUnitData.ginf, x: 2, y: 13 },
      { u: testUnitData.ginf, x: 0, y: 12 },
      { u: testUnitData.ginf, x: 3, y: 10 },
      { u: testUnitData.ginf, x: 6, y: 10 },
      { u: testUnitData.ginf, x: 7, y: 10 },
      { u: testUnitData.ginf, x: 8, y: 10 },
      { u: testUnitData.ginf, x: 9, y: 10 },
      { u: testUnitData.ginf, x: 5, y: 11 },
      { u: testUnitData.ginf, x: 5, y: 12 },
      { u: testUnitData.ginf, x: 8, y: 12 },
      { u: testUnitData.ginf, x: 5, y: 13 },
      { u: testUnitData.ginf, x: 6, y: 14 },
      { u: testUnitData.ginf, x: 3, y: 11 },
      { u: testUnitData.ginf, x: 4, y: 11 },
      { u: testUnitData.ginf, x: 6, y: 9 },
      { u: testUnitData.ginf, x: 10, y: 14 },
      { u: testUnitData.ginf, x: 9, y: 13 },
      { u: testUnitData.ginf, x: 10, y: 12 },
      { u: testUnitData.ginf, x: 9, y: 11 },
      { u: testUnitData.ginf, x: 11, y: 13 },
      { u: testUnitData.ginf, x: 14, y: 10 },
      { u: testUnitData.ginf, x: 14, y: 9 },
      { u: testUnitData.ginf, x: 14, y: 13 },
    ],
    hexes: [
      [
        { t: "o", h: 5 },
        { t: "o", h: 4 },
        { t: "o", h: 3 },
        { t: "o", h: 2 },
        { t: "o", h: 1 },
        { t: "o" },
        { t: "f" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o", h: 4 },
        { t: "o", h: 3 },
        { t: "o", h: 2 },
        { t: "o", h: 1 },
        { t: "o" },
        { t: "o" },
        { t: "f" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o", h: 3 },
        { t: "o", h: 2 },
        { t: "o", h: 1 },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "f" },
        { t: "o" },
        { t: "o", b: "w", be: [1, 2, 3, 4, 5, 6] },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o", h: 2 },
        { t: "o", h: 1 },
        { t: "o" },
        { t: "o", b: "f", be: [1, 2, 3, 4, 5, 6] },
        { t: "o" },
        { t: "o" },
        { t: "f" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o", h: 1 },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "f" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "f", h: 1  },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "l" } },
        { t: "o", d: 1, st: { sh: "l" } },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", h: 1 },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "s" } },
        { t: "o", d: 4, st: { sh: "s" } },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o", b: "w", be: [5] },
        { t: "o" },
        { t: "o" },
        { t: "o", b: "w", be: [3] },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "s" } },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bc1" } },
        { t: "o", d: 1, st: { sh: "bc3" } },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 4, st: { sh: "bc3" } },
        { t: "o", d: 4, st: { sh: "bc1" } },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bc1" } },
        { t: "o", d: 1, st: { sh: "bc2" } },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bs3" } },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bc1" } },
        { t: "o", d: 1, st: { sh: "bs2" } },
        { t: "o", d: 1, st: { sh: "bc2" } },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bs1" } },
        { t: "o", d: 1, st: { sh: "bm" } },
        { t: "o", d: 4, st: { sh: "bs1" } },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bs1" } },
        { t: "o", d: 4, st: { sh: "bs1" } },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bs1" } },
        { t: "o", d: 1, st: { sh: "bm" } },
        { t: "o", d: 1, st: { sh: "bm" } },
        { t: "o", d: 4, st: { sh: "bs1" } },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bs4" } },
        { t: "o", d: 4, st: { sh: "bs4" } },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "l" } },
      ], [
        { t: "o" },
        { t: "o", d: 4, st: { sh: "bs3" } },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 4, st: { sh: "bc2" } },
        { t: "o", d: 4, st: { sh: "bs2" } },
        { t: "o", d: 4, st: { sh: "bc1" } },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "bs1" } },
        { t: "o", d: 1, st: { sh: "bm" } },
        { t: "o", d: 4, st: { sh: "bs1" } },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 4, st: { sh: "bc2" } },
        { t: "o", d: 4, st: { sh: "bc1" } },
        { t: "o" },
        { t: "o" },
      ]
    ],
  },
  {
    x: 15, y: 15,
    features: [
      { u: testFeatureData.fire, x: 0, y: 3 },
      { u: testFeatureData.fire, x: 1, y: 3 },
      { u: testFeatureData.smoke, x: 2, y: 3 },
      { u: testFeatureData.smoke, x: 3, y: 3 },
      { u: testFeatureData.smoke, x: 11, y: 3 },
      { u: testFeatureData.rubble, x: 12, y: 1},
      { u: testFeatureData.tanktrap, x: 13, y: 1},
      { u: testFeatureData.roadblock, x: 11, y: 1},
      { u: testFeatureData.trench, x: 10, y: 1},
      { u: testFeatureData.scrape, x: 9, y: 1},
    ],
    units: [
      { u: testUnitData.ginf, x: 0, y: 0 },
      { u: testUnitData.ginf, x: 1, y: 0 },
      { u: testUnitData.ginf, x: 2, y: 0 },
      { u: testUnitData.ginf, x: 3, y: 0 },
      { u: testUnitData.ginf, x: 4, y: 0 },
      { u: testUnitData.ginf, x: 11, y: 3 },
      { u: testUnitData.ginf, x: 0, y: 6 },
      { u: testUnitData.ginf, x: 1, y: 6 },
      { u: testUnitData.ginf, x: 2, y: 6 },
      { u: testUnitData.ginf, x: 3, y: 6 },
      { u: testUnitData.ginf, x: 4, y: 6 },
      { u: testUnitData.ginf, x: 0, y: 8 },
      { u: testUnitData.ginf, x: 1, y: 8 },
      { u: testUnitData.ginf, x: 2, y: 8 },
      { u: testUnitData.ginf, x: 3, y: 8 },
      { u: testUnitData.ginf, x: 4, y: 8 },
      { u: testUnitData.ginf, x: 9, y: 13 },
      { u: testUnitData.ginf, x: 12, y: 13 },
      { u: testUnitData.ginf, x: 13, y: 14 },
      { u: testUnitData.useng, x: 0, y: 9 },
      { u: testUnitData.usft, x: 0, y: 9 },
      { u: testUnitData.usldr, x: 0, y: 9 },
      { u: testUnitData.usradio, x: 0, y: 9 },
      { u: testUnitData.usinf, x: 1, y: 9 },
      { u: testUnitData.usmg, x: 1, y: 9 },
      { u: testUnitData.usldr2, x: 1, y: 9 },
      { u: testUnitData.usinf, x: 2, y: 9 },
      { u: testUnitData.usmg2, x: 2, y: 9 },
      { u: testUnitData.usinf, x: 3, y: 9 },
      { u: testUnitData.usmort, x: 3, y: 9 },
      { u: testUnitData.usinf, x: 4, y: 9 },
      { u: testUnitData.usmort2, x: 4, y: 9 },
      { u: testUnitData.usinf, x: 5, y: 9 },
      { u: testUnitData.usmort3, x: 5, y: 9 },
      { u: testUnitData.useng, x: 6, y: 9 },
      { u: testUnitData.ussc, x: 6, y: 9 },
      { u: testUnitData.usinf, x: 7, y: 9 },
      { u: testUnitData.usbaz, x: 7, y: 9 },
      { u: testUnitData.uscrew, x: 8, y: 9 },
      { u: testUnitData.usgun, x: 8, y: 9, f: 2 },
      { u: testUnitData.uscrew, x: 9, y: 9 },
      { u: testUnitData.usat, x: 9, y: 9, f: 2 },
      { u: testUnitData.usac, x: 10, y: 9, f: 2, tf: 2 },
      { u: testUnitData.ustank, x: 11, y: 9, f: 2, tf: 2 },
      { u: testUnitData.ussg, x: 12, y: 9, f: 2, tf: 2 },
      { u: testUnitData.usspg, x: 13, y: 9, f: 2, tf: 2 },
      { u: testUnitData.usspat, x: 14, y: 9, f: 2, tf: 2 },
      { u: testUnitData.usftt, x: 0, y: 10, f: 2 },
      { u: testUnitData.usftt2, x: 1, y: 10, f: 2, tf: 2 },
      { u: testUnitData.usht, x: 2, y: 10, f: 2 },
      { u: testUnitData.usht2, x: 3, y: 10, f: 2 },
      { u: testUnitData.usht3, x: 4, y: 10, f: 2 },
      { u: testUnitData.usht4, x: 5, y: 10, f: 2 },
      { u: testUnitData.usht5, x: 6, y: 10, f: 2 },
      { u: testUnitData.usht6, x: 7, y: 10, f: 2, tf: 2 },
      { u: testUnitData.ustruck, x: 8, y: 10, f: 2 },
      { u: testUnitData.ustruck2, x: 9, y: 10, f: 2 },
      { u: testUnitData.usjeep, x: 10, y: 10, f: 2 },
      { u: testUnitData.usjeep2, x: 11, y: 10, f: 2 },
      { u: testUnitData.usmoto, x: 12, y: 10 },
      { u: testUnitData.bcav, x: 13, y: 10 },
      { u: testUnitData.htm, x: 14, y: 10, f: 2 },
      { u: testUnitData.htsm, x: 0, y: 11, f: 2 },
      { u: testUnitData.tspag, x: 1, y: 11, f: 2 },
      { u: testUnitData.tft, x: 2, y: 11, f: 2 },
      { u: testUnitData.ukinf, x: 3, y: 11 },
      { u: testUnitData.atr, x: 3, y: 11 },
      { u: testUnitData.uc, x: 4, y: 11, f: 2 },
      { u: testUnitData.tkt, x: 5, y: 11, f: 2 },
      { u: testUnitData.amt, x: 6, y: 11, f: 2, tf: 2 },
      { u: testUnitData.ginf, x: 7, y: 11 },
      { u: testUnitData.gpf, x: 7, y: 11 },
      { u: testUnitData.rm2cs, x: 8, y: 11, f: 2, tf: 2 },
      { u: testUnitData.croc, x: 9, y: 11, f: 2, tf: 2 },
      { u: testUnitData.rinf, x: 10, y: 11 },
      { u: testUnitData.rmc, x: 10, y: 11 },
      { u: testUnitData.ac, x: 11, y: 11, f: 2, tf: 2 },
      { u: testUnitData.hcav, x: 12, y: 11 },
      { u: testUnitData.rtr, x: 13, y: 11, f: 2 },
      { u: testUnitData.usjeep, x: 0, y: 13, f: 4 },
      { u: testUnitData.usldr, x: 0, y: 13 },
      { u: testUnitData.usinf, x: 0, y: 13 },
      { u: testUnitData.usjeep2, x: 1, y: 13, f: 4 },
      { u: testUnitData.usat, x: 1, y: 13, f: 1 },
      { u: testUnitData.usinf, x: 1, y: 13 },
      { u: testUnitData.ustruck, x: 2, y: 13, f: 4 },
      { u: testUnitData.usat, x: 2, y: 13, f: 1 },
      { u: testUnitData.usinf, x: 2, y: 13 },
      { u: testUnitData.usmg, x: 2, y: 13 },
      { u: testUnitData.usldr, x: 2, y: 13 },
      { u: testUnitData.usradio, x: 2, y: 13 },
      { u: testUnitData.htsm, x: 3, y: 13, f: 4 },
      { u: testUnitData.usat, x: 3, y: 13, f: 1 },
      { u: testUnitData.uscrew, x: 3, y: 13 },
      { u: testUnitData.usldr, x: 3, y: 13 },
    ],
    hexes: [
      [
        { t: "o", h: 5 },
        { t: "o", h: 4 },
        { t: "o", h: 3 },
        { t: "o", h: 2 },
        { t: "o", h: 1 },
        { t: "g" },
        { t: "g" },
        { t: "g" },
        { t: "g" },
        { t: "g" },
        { t: "g" },
        { t: "g" },
        { t: "g" },
        { t: "g" },
        { t: "g" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o", h: -1 },
        { t: "o", h: -1, s: { d: [1, 4], t: "g" } },
        { t: "o", s: { d: [2, 6], t: "t" } },
        { t: "o", rr: { d: [[1, 3], [1, 5]] } },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "t" },
        { t: "p" },
        { t: "x" },
        { t: "y" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", b: "f", be: [4] },
        { t: "o" },
        { t: "o", b: "w", be: [1] },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o", h: 5 },
        { t: "o", h: 4 },
        { t: "o", h: 3 },
        { t: "o", h: 2 },
        { t: "o", h: 1 },
        { t: "o" },
        { t: "o", b: "f", be: [1] },
        { t: "o", b: "f", be: [1] },
        { t: "o", b: "f", be: [1] },
        { t: "o", b: "f", be: [1] },
        { t: "o", b: "f", be: [1] },
        { t: "o", b: "f", be: [1] },
        { t: "o", b: "f", be: [1] },
        { t: "o", b: "f", be: [1] },
        { t: "o", b: "f", be: [1] },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o", h: 5 },
        { t: "o", h: 4 },
        { t: "o", h: 3 },
        { t: "o", h: 2 },
        { t: "o", h: 1 },
        { t: "o" },
        { t: "d", d: 1, h: 1 },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", d: 1, st: { sh: "x" }, h: 1 },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
      ], [
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "g", b: "f", be: [1, 2, 3] },
        { t: "o", b: "f", be: [1] },
        { t: "o" },
      ], [
        { t: "o", st: { sh: "s2" }, d: 1 },
        { t: "o", st: { sh: "m2" }, d: 1 },
        { t: "o", st: { sh: "s2" }, d: 4 },
        { t: "o" },
        { t: "o", st: { sh: "l2" }, d: 1 },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o" },
        { t: "o", b: "f", be: [3] },
        { t: "o", b: "f", be: [2] },
        { t: "o" },
      ]
    ],
  },
  {
    // Minitest map, to visually verify LOS integration tests
    x: 5,
    y: 5,
    units: [
      { u: testUnitData.ginf, x: 4, y: 2 },
    ],
    features: [],
    hexes: [
      [{ t: "o" }, { t: "o" }, { t: "o", s: { d: [3, 5] } }, { t: "o" }, { t: "o" }],
      [{ t: "o" }, { t: "o" }, { t: "o", s: { d: [2, 6] } }, { t: "o" }, { t: "o" }],
      [
        { t: "o", rr: { d: [[1, 4]]} },
        { t: "o", rr: { d: [[1, 4]]} },
        { t: "o", s: { d: [3, 5] }, rr: { d: [[1, 4]]} },
        { t: "o", rr: { d: [[1, 4]]} },
        { t: "o", rr: { d: [[1, 4]]} },
      ],
      [{ t: "o" }, { t: "o" }, { t: "o", s: { d: [2, 6] } }, { t: "f" }, { t: "o" }],
      [{ t: "o" }, { t: "o" }, { t: "o", s: { d: [3, 5] } }, { t: "o" }, { t: "o" }],
    ],
  },
]
